import ChineseExperienceActions from '@/components/ChineseExperienceActions';
import ChineseVoiceSlot from '@/components/ChineseVoiceSlot';
import IndonesianAudioProvider from '@/components/IndonesianAudioProvider';
import type { ChineseExperience } from '@/lib/chinese-experiences';

export default function ChineseExperienceDetail({ experience }: { experience: ChineseExperience }) {
  return <IndonesianAudioProvider><article className="mt-7 rounded-2xl border border-stone-200 bg-white px-5 py-6 shadow-sm sm:px-8"><p className="text-xs font-medium text-stone-400">{experience.id}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-stone-950">{experience.title}</h1><p className="mt-2 text-lg text-stone-500">{experience.pinyin}</p><ChineseVoiceSlot text={experience.title} />
    <section className="mt-7"><p className="text-xs font-medium text-stone-400">场景介绍（Konteks）</p><p className="mt-2 text-sm leading-7 text-stone-700">{experience.scenario}</p></section>
    <section className="mt-7"><p className="text-xs font-medium text-stone-400">场景对话（Dialog）</p><div className="mt-3 space-y-3">{experience.dialogue.map((item, index) => <div key={`${item.speaker}-${index}`} className={`rounded-xl px-4 py-4 ${item.speaker === '中国同事' ? 'bg-stone-900 text-white' : 'bg-stone-50 text-stone-900'}`}><p className={`text-xs ${item.speaker === '中国同事' ? 'text-stone-300' : 'text-stone-400'}`}>{item.speaker}</p><p className="mt-2 text-lg leading-7">{item.chinese}</p><p className={`mt-1 text-sm ${item.speaker === '中国同事' ? 'text-stone-300' : 'text-stone-500'}`}>{item.pinyin}</p><p className={`mt-2 text-sm leading-6 ${item.speaker === '中国同事' ? 'text-stone-200' : 'text-stone-600'}`}>{item.indonesian}</p><ChineseVoiceSlot text={item.chinese} compact /></div>)}</div></section>
    <section className="mt-7 grid gap-6 lg:grid-cols-2"><div><p className="text-xs font-medium text-stone-400">高频词汇（Kosakata penting）</p><ul className="mt-3 space-y-2">{experience.vocabulary.map((item) => <li key={item.chinese} className="rounded-lg bg-stone-50 px-3 py-3 text-sm"><span className="font-medium">{item.chinese}</span><span className="ml-2 text-stone-500">{item.pinyin}</span><span className="mt-1 block text-stone-600">{item.indonesian}</span><ChineseVoiceSlot text={item.chinese} compact /></li>)}</ul></div><div><p className="text-xs font-medium text-stone-400">常用物品（Benda terkait）</p><ul className="mt-3 space-y-2">{experience.objects.map((item) => <li key={item.chinese} className="rounded-lg bg-stone-50 px-3 py-3 text-sm"><span className="font-medium">{item.chinese}</span><span className="ml-2 text-stone-500">{item.pinyin}</span><span className="mt-1 block text-stone-600">{item.indonesian}</span><ChineseVoiceSlot text={item.chinese} compact /></li>)}</ul></div></section>
    <section className="mt-7 rounded-xl border border-stone-200 p-4"><p className="text-xs font-medium text-stone-400">Pattern（句型）</p><p className="mt-2 text-lg font-medium">{experience.pattern.chinese}</p><p className="mt-1 text-sm text-stone-500">{experience.pattern.pinyin}</p><p className="mt-2 text-sm text-stone-600">{experience.pattern.indonesian}</p><ChineseVoiceSlot text={experience.pattern.chinese} compact /><div className="mt-4 space-y-2">{experience.pattern.examples.map((item) => <div key={item.chinese} className="border-l-2 border-stone-300 pl-3 text-sm"><p>{item.chinese}</p><p className="mt-1 text-stone-500">{item.pinyin}</p><p className="mt-1 text-stone-600">{item.indonesian}</p><ChineseVoiceSlot text={item.chinese} compact /></div>)}</div></section>
    <section className="mt-7 grid gap-3 md:grid-cols-2"><div className="rounded-xl bg-stone-50 p-4"><p className="text-xs font-medium text-stone-400">中国小知识</p><p className="mt-2 text-sm leading-7 text-stone-700">{experience.chinaKnowledge}</p></div><div className="rounded-xl bg-stone-50 p-4"><p className="text-xs font-medium text-stone-400">文化提醒</p><p className="mt-2 text-sm leading-7 text-stone-700">{experience.cultureTip}</p></div></section>
    <ChineseExperienceActions experienceId={experience.id} />
  </article></IndonesianAudioProvider>;
}
