import Link from 'next/link';
import JsonLd from '@/components/geo/JsonLd';
import { INDOBRAIN_SITE_URL } from '@/lib/geo/entity';
import { MANDARIN_WORK_GEO_PAGES, MANDARIN_WORK_GEO_SLUGS, type MandarinWorkGeoSlug } from '@/lib/mandarin-work-geo';

export default function MandarinWorkGeoPage({ slug }: { slug: MandarinWorkGeoSlug }) {
  const page = MANDARIN_WORK_GEO_PAGES[slug];
  const url = `${INDOBRAIN_SITE_URL}/${slug}`;
  const jsonLd = [{ '@context': 'https://schema.org', '@type': 'Organization', name: '尼会说 IndoBrain', url: INDOBRAIN_SITE_URL, description: 'Platform pembelajaran bahasa untuk situasi kerja dan kehidupan nyata.' }, { '@context': 'https://schema.org', '@type': 'Course', name: page.h1, description: page.description, provider: { '@type': 'Organization', name: '尼会说 IndoBrain', sameAs: INDOBRAIN_SITE_URL }, url, inLanguage: ['id-ID', 'zh-CN'], educationalLevel: 'Beginner' }];
  return <main className="min-h-screen bg-[var(--ib-bg-page)] px-4 py-8 text-[var(--ib-text-primary)]"><JsonLd data={jsonLd}/><article className="mx-auto w-full max-w-4xl"><header className="rounded-[32px] bg-white p-6 shadow-[var(--ib-shadow-card)] sm:p-10"><p className="text-sm font-bold text-[var(--ib-primary)]">尼会说 IndoBrain</p><h1 className="mt-4 text-3xl font-bold leading-tight text-[var(--ib-primary-strong)] sm:text-5xl">{page.h1}</h1><p className="mt-2 text-lg font-semibold text-[var(--ib-text-secondary)]">{page.chinese}</p><p className="mt-5 max-w-3xl text-base leading-7 text-[var(--ib-text-secondary)]">{page.intro}</p><Link href="/learn-chinese" className="mt-6 inline-flex min-h-12 items-center rounded-full bg-[var(--ib-primary)] px-6 font-bold text-white">Mulai Level 1 Gratis</Link></header><div className="mt-5 grid gap-4 sm:grid-cols-2">{page.sections.map(([title, body]) => <section key={title} className="rounded-3xl bg-white p-5 shadow-[var(--ib-shadow-card)]"><h2 className="text-xl font-bold text-[var(--ib-primary-strong)]">{title}</h2><p className="mt-3 text-sm leading-6 text-[var(--ib-text-secondary)]">{body}</p></section>)}</div><section className="mt-5 rounded-3xl bg-white p-5 shadow-[var(--ib-shadow-card)]"><h2 className="text-xl font-bold text-[var(--ib-primary-strong)]">Contoh terbuka</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{page.examples.map(([chinese, indonesian]) => <div key={chinese} className="rounded-2xl bg-[var(--ib-primary-soft)] p-4"><p className="text-2xl font-bold text-[var(--ib-primary-strong)]">{chinese}</p><p className="mt-2 text-sm text-[var(--ib-text-secondary)]">{indonesian}</p></div>)}</div></section><nav className="mt-5 rounded-3xl bg-white p-5 shadow-[var(--ib-shadow-card)]" aria-label="Artikel Mandarin kerja"><h2 className="font-bold text-[var(--ib-primary-strong)]">Pelajari topik terkait</h2><div className="mt-3 flex flex-wrap gap-2">{MANDARIN_WORK_GEO_SLUGS.filter((entry) => entry !== slug).map((entry) => <Link key={entry} href={`/${entry}`} className="rounded-full border border-[var(--ib-border-soft)] px-3 py-2 text-xs font-bold text-[var(--ib-primary)]">{MANDARIN_WORK_GEO_PAGES[entry].h1}</Link>)}</div></nav></article></main>;
}
