import type { GoldenSceneContent } from '@/lib/golden-scenes';

export type GoldenExperiencePatch = {
  task: string;
  indonesian: string;
  explanation: string;
  harvest: string[];
  goldenScene: GoldenSceneContent;
};

const line = (speaker: string, indonesian: string, chinese: string) => ({ speaker, indonesian, chinese });
const pair = (indonesian: string, chinese: string) => ({ indonesian, chinese });

export const lifeGoldenBatch5: Record<string, GoldenExperiencePatch> = {
  'EXP-LIF-144': {
    task: '员工汇报了半天，我还是没听懂',
    indonesian: 'Maaf, saya potong dulu. Intinya apa, hasilnya bagaimana, dan sekarang butuh keputusan apa dari saya?',
    explanation: '员工汇报太长太散时，把他拉回结果、问题、卡点、下一步和需要老板决定的事项。',
    harvest: ['intinya apa', 'hasilnya bagaimana', 'masalah utamanya', 'butuh keputusan apa'],
    goldenScene: {
      situation: '员工讲了很多过程，你听了三分钟还是不知道结果。你需要礼貌打断，让汇报变清楚。',
      goal: '成功把模糊长汇报变成“结果—问题—卡点—下一步—需要决定”的结构。',
      dialogue: [
        line('员工', 'Pak, jadi kemarin saya sudah coba hubungi orang gudang, terus katanya datanya belum lengkap, lalu saya cek lagi...', 'Pak，昨天我试着联系仓库的人，然后他说数据还不完整，我又查了一下……'),
        line('我', 'Maaf, saya potong dulu. Intinya apa?', '不好意思，我先打断一下。重点是什么？'),
        line('员工', 'Intinya laporan belum selesai, Pak.', '重点是报告还没完成，Pak。'),
        line('我', 'Hasil yang sudah ada bagaimana?', '现在已有结果怎么样？'),
        line('员工', 'Data penjualan sudah ada, tapi data stok belum cocok.', '销售数据有了，但库存数据还没对上。'),
        line('我', 'Masalah utamanya apa dan sekarang mandek di mana?', '主要问题是什么，现在卡在哪里？'),
        line('员工', 'Mandek di data stok dari gudang. Mereka belum konfirmasi angka final.', '卡在仓库库存数据。他们还没确认最终数字。'),
        line('我', 'Sekarang butuh keputusan apa dari saya?', '现在需要我决定什么？'),
        line('员工', 'Perlu Bapak putuskan: laporan dikirim hari ini dengan catatan, atau tunggu data final besok pagi.', '需要您决定：今天带备注发送，还是等明早最终数据。'),
      ],
      replies: [
        pair('Intinya masalahnya ada di data stok.', '重点是问题在库存数据。'),
        pair('Hasil sementara sudah ada, tapi belum final.', '临时结果有了，但还不是最终版。'),
        pair('Saya butuh keputusan soal deadline laporan.', '我需要您决定报告截止时间。'),
      ],
      variations: [
        pair('Tolong mulai dari hasil dulu.', '请先从结果开始说。'),
        pair('Jangan cerita proses terlalu panjang dulu.', '先不要讲太长过程。'),
        pair('Apa yang sudah selesai dan apa yang belum?', '哪些完成了，哪些还没完成？'),
        pair('Langkah berikutnya apa?', '下一步是什么？'),
      ],
      decisions: [
        {
          situation: '员工又开始从头讲过程。',
          options: [
            pair('Stop dulu. Jawab tiga hal: hasil, masalah, keputusan.', '先停。回答三件事：结果、问题、决定。'),
            pair('Kirim ringkasan tiga poin di WhatsApp setelah ini.', '之后把三点总结发 WhatsApp。'),
          ],
        },
      ],
      localUsage: pair('Intinya apa? 是印尼职场里很自然的“说重点”。语气要平稳，不要像在骂人。', '打断不是羞辱，是让沟通有效。'),
      easyMistake: pair('不要一直忍到最后才说“不懂”。越早建立汇报结构，越省时间。', '结果先行。'),
      trySay: pair('Intinya apa, hasilnya bagaimana, dan sekarang butuh keputusan apa dari saya?', '重点是什么，结果怎么样，现在需要我决定什么？'),
    },
  },
  'EXP-LIF-145': {
    task: '员工说“已经做了”，但其实还没真正完成',
    indonesian: 'Sudah itu maksudnya sudah mulai, sudah sebagian, atau benar-benar selesai?',
    explanation: '不要只听 sudah。要确认是真开始、做了一部分，还是按照最终标准完成。',
    harvest: ['sudah mulai', 'sudah sebagian', 'benar-benar selesai', 'standar selesai'],
    goldenScene: {
      situation: '你问资料做好没有，员工马上回答 sudah。你打开一看，发现只做了前半部分。',
      goal: '成功区分“开始做/部分完成/真正完成”，并确认最终完成时间。',
      dialogue: [
        line('我', 'File laporan kemarin sudah selesai?', '昨天的报告文件完成了吗？'),
        line('员工', 'Sudah, Pak.', '已经了，Pak。'),
        line('我', 'Saya cek dulu ya. Ini baru bagian penjualan, bagian stok belum ada.', '我先看一下。这只有销售部分，库存部分还没有。'),
        line('员工', 'Iya Pak, maksud saya sudah mulai dikerjakan.', '是的 Pak，我的意思是已经开始做了。'),
        line('我', 'Kalau begitu jangan bilang selesai. Bilang sudah mulai atau sudah sebagian.', '那就不要说完成。说已经开始或完成一部分。'),
        line('员工', 'Baik Pak, yang selesai baru lima puluh persen.', '好的 Pak，现在只完成 50%。'),
        line('我', 'Standar selesai itu semua data masuk, dicek, dan format sudah rapi.', '完成标准是所有数据录入、检查过、格式整理好。'),
        line('员工', 'Saya bisa selesaikan jam empat sore.', '我可以下午四点完成。'),
        line('我', 'Jam empat saya cek lagi. Kalau belum selesai, kasih tahu sebelum jam tiga.', '四点我再检查。如果还没完成，三点前告诉我。'),
      ],
      replies: [
        pair('Sudah mulai, tapi belum selesai.', '已经开始，但还没完成。'),
        pair('Yang selesai baru bagian penjualan.', '完成的只有销售部分。'),
        pair('Saya update sebelum jam tiga kalau ada kendala.', '如果有问题，我三点前更新。'),
      ],
      variations: [
        pair('Selesai menurut kamu artinya apa?', '你说完成，具体是什么意思？'),
        pair('Berapa persen yang sudah selesai?', '已经完成百分之多少？'),
        pair('Bagian mana yang belum?', '哪一部分还没做？'),
        pair('Kapan benar-benar selesai?', '什么时候真正完成？'),
      ],
      decisions: [
        {
          situation: '员工坚持说 sudah，但标准没达到。',
          options: [
            pair('Saya anggap belum selesai sampai semua bagian lengkap.', '所有部分完整前，我认为还没完成。'),
            pair('Tolong pakai kata “sebagian selesai”, bukan “selesai”.', '请用“部分完成”，不要说“完成”。'),
          ],
        },
      ],
      localUsage: pair('Sudah 在印尼语里很常见，但职场管理要追问 sudah apa。', '不要被一个 sudah 结束沟通。'),
      easyMistake: pair('不要直接说 kamu bohong。更好的方式是重新定义完成标准。', '批标准，不扣帽子。'),
      trySay: pair('Sudah itu maksudnya sudah mulai, sudah sebagian, atau benar-benar selesai?', '你说已经，是开始了、做了一部分，还是真正完成？'),
    },
  },
  'EXP-LIF-146': {
    task: 'WhatsApp 工作消息一直没人回复',
    indonesian: 'Kalau pesan kerja sudah dibaca, minimal balas “baik” atau “saya cek dulu”.',
    explanation: '工作群消息已读不回时，建立紧急消息和普通消息的回应规则。',
    harvest: ['pesan kerja', 'sudah dibaca', 'minimal balas', 'pesan urgent'],
    goldenScene: {
      situation: '你在 WhatsApp 发了重要工作消息，员工已读但一直没回，导致事情卡住。',
      goal: '成功建立“收到要确认、紧急要快回、不确定也要说明”的沟通纪律。',
      dialogue: [
        line('我', 'Pesan saya tadi pagi sudah kamu lihat?', '我早上的消息你看到了吗？'),
        line('员工', 'Sudah lihat, Pak, tapi belum sempat balas.', '看到了 Pak，但还没来得及回。'),
        line('我', 'Kalau pesan kerja sudah dibaca, jangan dibiarkan tanpa respons.', '工作消息看到了，不要不回应。'),
        line('员工', 'Saya kira kalau belum ada jawaban, nanti saja balasnya.', '我以为还没有答案，就晚点再回。'),
        line('我', 'Kalau belum tahu jawabannya, balas “saya cek dulu”. Kalau urgent, balas lebih cepat.', '如果还不知道答案，就回“我先查”。如果紧急，要更快回。'),
        line('员工', 'Baik Pak. Untuk pesan biasa bagaimana?', '好的 Pak。普通消息呢？'),
        line('我', 'Pesan biasa maksimal hari itu dibalas. Pesan urgent maksimal tiga puluh menit.', '普通消息当天回复。紧急消息最多 30 分钟。'),
        line('员工', 'Baik, Pak. Nanti saya balas dulu walaupun masih cek.', '好的 Pak。以后即使还在查，我也先回复。'),
      ],
      replies: [
        pair('Maaf Pak, tadi saya sedang di lapangan.', '抱歉 Pak，刚才我在现场。'),
        pair('Saya sudah baca, tapi belum cek datanya.', '我看到了，但还没查数据。'),
        pair('Ke depan saya balas dulu kalau sudah baca.', '以后我看到了会先回复。'),
      ],
      variations: [
        pair('Kalau sedang sibuk, cukup balas singkat dulu.', '如果忙，先简短回复也可以。'),
        pair('Untuk hal urgent, jangan tunggu sampai malam.', '紧急事情不要等到晚上。'),
        pair('Tolong bedakan pesan biasa dan pesan urgent.', '请区分普通消息和紧急消息。'),
        pair('Saya tes lagi nanti, tolong langsung konfirmasi.', '我晚点再测试，请马上确认。'),
      ],
      decisions: [
        {
          situation: '员工担心没答案时回复会显得没能力。',
          options: [
            pair('Tidak apa-apa belum tahu. Yang penting konfirmasi dulu.', '不知道没关系。重要的是先确认收到。'),
            pair('Balas “saya cek dulu” lebih baik daripada diam.', '回“我先查”比沉默好。'),
          ],
        },
      ],
      localUsage: pair('印尼职场 WhatsApp 很常用，balas dulu 是管理沟通节奏的关键。', '先确认，再处理。'),
      easyMistake: pair('不要只说 “harus cepat balas”。要定义普通和紧急的规则。', '规则要具体。'),
      trySay: pair('Kalau pesan kerja sudah dibaca, minimal balas “baik” atau “saya cek dulu”.', '工作消息已读后，至少回复“好的”或“我先查”。'),
    },
  },
  'EXP-LIF-147': {
    task: '我要员工今天把资料发给我',
    indonesian: 'Tolong kirim file versi terbaru dalam format PDF ke email saya sebelum jam tiga.',
    explanation: '指定文件、版本、格式、发送渠道和截止时间，并处理找不到/发错版本。',
    harvest: ['file versi terbaru', 'format PDF', 'sebelum jam tiga', 'kirim ulang'],
    goldenScene: {
      situation: '你需要员工今天把正确版本的资料发给你，但以前他经常发错版本或只发截图。',
      goal: '成功拿到正确文件版本、格式和发送渠道。',
      dialogue: [
        line('我', 'Tolong kirim file proposal versi terbaru hari ini.', '请今天把最新版 proposal 文件发给我。'),
        line('员工', 'Yang versi minggu lalu ya, Pak?', '上周那个版本吗，Pak？'),
        line('我', 'Bukan. Versi terbaru yang ada revisi harga.', '不是。是有价格修改的最新版。'),
        line('员工', 'Formatnya Word atau PDF?', '格式 Word 还是 PDF？'),
        line('我', 'Kirim PDF ke email saya, lalu WhatsApp saya setelah terkirim.', '发 PDF 到我邮箱，发完后 WhatsApp 通知我。'),
        line('员工', 'Saya cari dulu filenya, Pak. Sepertinya ada di Drive.', '我先找文件，Pak。好像在 Drive。'),
        line('我', 'Deadline jam tiga. Kalau tidak ketemu jam dua, kabari saya.', '截止三点。如果两点还找不到，告诉我。'),
        line('员工', 'Pak, saya sudah kirim, tapi ternyata versi lama.', 'Pak，我发了，但发现是旧版本。'),
        line('我', 'Tolong kirim ulang versi terbaru. Nama file-nya tambahkan “final”.', '请重发最新版。文件名加上“final”。'),
      ],
      replies: [
        pair('File terbaru ada di folder Drive marketing.', '最新版文件在 Drive 的 marketing 文件夹。'),
        pair('Saya kirim ulang dalam format PDF.', '我用 PDF 格式重发。'),
        pair('Saya kabari setelah email terkirim.', '邮件发出后我通知您。'),
      ],
      variations: [
        pair('Kirim ke WhatsApp juga sebagai backup.', '也发 WhatsApp 作为备份。'),
        pair('Jangan kirim screenshot, kirim file asli.', '不要发截图，发原文件。'),
        pair('Pastikan itu versi terbaru.', '确认是最新版。'),
        pair('Tolong cek nama file sebelum kirim.', '发送前检查文件名。'),
      ],
      decisions: [
        {
          situation: '员工两点还找不到文件。',
          options: [
            pair('Cari di Drive dulu. Kalau belum ketemu, minta bantuan marketing.', '先在 Drive 找。如果还找不到，请 marketing 帮忙。'),
            pair('Kirim versi yang ada dulu, tapi tulis jelas belum final.', '先发已有版本，但写清楚还不是最终版。'),
          ],
        },
      ],
      localUsage: pair('Versi terbaru 和 kirim ulang 是办公室非常高频表达。', '文件沟通要说版本。'),
      easyMistake: pair('不要只说 kirim file。要说版本、格式、渠道、时间。', '要求越清楚，返工越少。'),
      trySay: pair('Tolong kirim file versi terbaru dalam format PDF ke email saya sebelum jam tiga.', '请三点前把最新版 PDF 发到我邮箱。'),
    },
  },
  'EXP-LIF-148': {
    task: '会议要开始了，人还没到齐',
    indonesian: 'Siapa yang belum datang? Kalau lima menit lagi belum sampai, kita mulai dulu.',
    explanation: '会议快开始但人没到齐时，确认缺席人、位置、等待时间，并决定是否先开始。',
    harvest: ['belum datang', 'lima menit lagi', 'kita mulai dulu', 'tolong kabari'],
    goldenScene: {
      situation: '会议时间到了，但还有几个人没到。你需要决定等不等，并让已到的人先开始。',
      goal: '成功确认人员状态，通知迟到者，并正式开始会议。',
      dialogue: [
        line('我', 'Siapa yang belum datang?', '谁还没来？'),
        line('员工', 'Pak Rudi dan Bu Sari belum datang.', 'Rudi 先生和 Sari 女士还没来。'),
        line('我', 'Mereka di mana sekarang?', '他们现在在哪里？'),
        line('员工', 'Pak Rudi masih parkir, Bu Sari katanya di jalan.', 'Rudi 还在停车，Sari 说在路上。'),
        line('我', 'Masih berapa lama?', '还要多久？'),
        line('员工', 'Pak Rudi lima menit, Bu Sari mungkin lima belas menit.', 'Rudi 五分钟，Sari 可能十五分钟。'),
        line('我', 'Kalau lima menit lagi belum lengkap, kita mulai dulu.', '如果五分钟后还没齐，我们先开始。'),
        line('员工', 'Baik Pak, saya kabari Bu Sari supaya langsung masuk saat sampai.', '好的 Pak，我通知 Sari 到了直接进来。'),
        line('我', 'Yang sudah hadir, kita mulai dari update masing-masing dulu.', '已经到的人，我们先从各自更新开始。'),
      ],
      replies: [
        pair('Bu Sari masih di jalan, Pak.', 'Sari 女士还在路上，Pak。'),
        pair('Kita tunggu lima menit lagi?', '我们再等五分钟吗？'),
        pair('Yang sudah hadir bisa mulai update dulu.', '已经到的人可以先开始汇报。'),
      ],
      variations: [
        pair('Tolong hubungi yang belum datang sekarang.', '请现在联系还没到的人。'),
        pair('Jangan tunggu terlalu lama, waktu kita terbatas.', '不要等太久，我们时间有限。'),
        pair('Kalau terlambat, dia bisa menyusul.', '如果迟到，他可以后面加入。'),
        pair('Kita mulai dari agenda pertama.', '我们从第一个议程开始。'),
      ],
      decisions: [
        {
          situation: '有人建议继续等 20 分钟。',
          options: [
            pair('Tidak perlu tunggu semua. Kita mulai bagian yang bisa dibahas dulu.', '不用等所有人。我们先开始能讨论的部分。'),
            pair('Kita tunggu maksimal lima menit, setelah itu mulai.', '最多等五分钟，然后开始。'),
          ],
        },
      ],
      localUsage: pair('Kita mulai dulu 很自然，表示“不等了，先开始”，语气比“不管他们”更得体。', '控制会议节奏。'),
      easyMistake: pair('不要一直等到会议失控。先确认 ETA，再决定。', '迟到也要有规则。'),
      trySay: pair('Kalau lima menit lagi belum sampai, kita mulai dulu.', '如果五分钟后还没到，我们先开始。'),
    },
  },
  'EXP-LIF-149': {
    task: '员工一直说问题，却不给解决方案',
    indonesian: 'Saya sudah paham masalahnya. Sekarang solusi yang kamu usulkan apa?',
    explanation: '员工只报告问题时，引导他说已试过什么、建议方案、需要资源和需要老板决定什么。',
    harvest: ['paham masalahnya', 'solusi yang diusulkan', 'sudah coba apa', 'butuh resource apa'],
    goldenScene: {
      situation: '员工连续讲了很多困难：系统慢、客户催、仓库忙。但没有给任何解决方案。',
      goal: '成功把“问题汇报”转成“带方案汇报”。',
      dialogue: [
        line('员工', 'Pak, masalahnya banyak. Sistem lambat, gudang belum siap, customer juga tanya terus.', 'Pak，问题很多。系统慢，仓库没准备好，客户也一直问。'),
        line('我', 'Saya sudah paham masalahnya. Sekarang solusi yang kamu usulkan apa?', '我已经理解问题。现在你建议的解决方案是什么？'),
        line('员工', 'Saya belum tahu, Pak. Saya cuma lapor dulu.', '我还不知道，Pak。我只是先汇报。'),
        line('我', 'Sebelum lapor, minimal pikirkan satu atau dua opsi.', '汇报前，至少想一两个选项。'),
        line('我', 'Kamu sudah coba apa?', '你已经试过什么？'),
        line('员工', 'Saya sudah minta gudang prioritaskan order ini, tapi belum ada orang.', '我已经让仓库优先这个订单，但还没人手。'),
        line('我', 'Kalau begitu, resource apa yang kamu butuhkan?', '那你需要什么资源？'),
        line('员工', 'Butuh dua orang tambahan sampai jam enam.', '需要两个人加到六点。'),
        line('我', 'Baik. Keputusan dari saya: tambah dua orang hari ini. Besok lapor dengan opsi solusi.', '好。我的决定：今天加两个人。明天汇报要带解决选项。'),
      ],
      replies: [
        pair('Saya baru lapor masalahnya dulu, Pak.', '我只是先汇报问题，Pak。'),
        pair('Solusi sementara: tambah orang di gudang.', '临时方案：仓库加人。'),
        pair('Saya butuh keputusan soal tambahan orang.', '我需要您决定是否加人。'),
      ],
      variations: [
        pair('Apa opsi pertama dan opsi kedua?', '第一个和第二个选项是什么？'),
        pair('Kalau solusi ini gagal, plan B-nya apa?', '如果这个方案失败，B 计划是什么？'),
        pair('Mana yang paling cepat dijalankan hari ini?', '今天最快能执行的是哪个？'),
        pair('Apa risiko dari solusi itu?', '那个方案的风险是什么？'),
      ],
      decisions: [
        {
          situation: '员工只想把问题交给老板。',
          options: [
            pair('Saya bantu putuskan, tapi kamu harus bawa opsi.', '我可以帮忙决定，但你要带选项来。'),
            pair('Tulis masalah, solusi, kebutuhan, dan deadline dalam satu pesan.', '把问题、方案、需求和截止时间写在一条消息里。'),
          ],
        },
      ],
      localUsage: pair('Solusi yang kamu usulkan apa? 比 kamu mau saya bagaimana? 更能训练团队主动思考。', '汇报要带方案。'),
      easyMistake: pair('不要把“报问题”当成“完成工作”。', '管理要把问题推进到下一步。'),
      trySay: pair('Saya sudah paham masalahnya. Sekarang solusi yang kamu usulkan apa?', '我已经理解问题。现在你建议的解决方案是什么？'),
    },
  },
  'EXP-LIF-150': {
    task: '几个部门互相推责任',
    indonesian: 'Stop dulu. Kita jangan saling menyalahkan. Kita urutkan fakta berdasarkan timeline.',
    explanation: '多部门推责任时，停止争论，按时间线确认事实、断点、负责人、修复 deadline。',
    harvest: ['jangan saling menyalahkan', 'urutkan fakta', 'berdasarkan timeline', 'siapa PIC'],
    goldenScene: {
      situation: '销售说仓库的问题，仓库说采购的问题，采购说供应商的问题，会议开始变成互相指责。',
      goal: '成功停止推责任，按事实时间线确认断点和修复负责人。',
      dialogue: [
        line('销售', 'Ini terlambat karena gudang tidak siap.', '这是因为仓库没准备好才延误。'),
        line('仓库', 'Bukan kami, barang dari purchasing belum lengkap.', '不是我们，采购的货还没齐。'),
        line('采购', 'Supplier yang telat, bukan purchasing.', '是供应商晚了，不是采购。'),
        line('我', 'Stop dulu. Kita jangan saling menyalahkan.', '先停。我们不要互相指责。'),
        line('我', 'Kita urutkan fakta berdasarkan timeline. Kapan sales terima order?', '我们按时间线梳理事实。销售什么时候接到订单？'),
        line('销售', 'Hari Senin jam sepuluh.', '周一十点。'),
        line('我', 'Kapan PO ke supplier dikirim?', 'PO 什么时候发给供应商？'),
        line('采购', 'Senin sore, tapi supplier konfirmasi Selasa siang.', '周一下午，但供应商周二中午确认。'),
        line('我', 'Jadi titik putusnya di konfirmasi supplier. Siapa PIC follow up sekarang?', '所以断点在供应商确认。现在谁负责跟进？'),
        line('采购', 'Saya yang follow up, deadline update jam tiga sore.', '我负责跟进，下午三点更新。'),
      ],
      replies: [
        pair('Kalau lihat timeline, masalah mulai dari konfirmasi supplier.', '看时间线，问题从供应商确认开始。'),
        pair('Kami perlu satu PIC untuk follow up.', '我们需要一个 PIC 跟进。'),
        pair('Setelah ini dibuat aturan update antar-departemen.', '之后要做部门间更新规则。'),
      ],
      variations: [
        pair('Kita bahas fakta dulu, bukan siapa yang salah.', '我们先谈事实，不是谁错。'),
        pair('Langkah mana yang putus?', '哪一步断了？'),
        pair('Siapa yang memperbaiki hari ini?', '今天谁来修复？'),
        pair('Deadline update berikutnya jam berapa?', '下一次更新时间几点？'),
      ],
      decisions: [
        {
          situation: '大家继续争论谁的问题。',
          options: [
            pair('Kalau terus debat, masalah tidak selesai. Kita tetapkan PIC sekarang.', '如果继续争，问题解决不了。我们现在指定 PIC。'),
            pair('Tanggung jawab nanti dibahas, sekarang fokus perbaikan dulu.', '责任之后再谈，现在先修复。'),
          ],
        },
      ],
      localUsage: pair('Jangan saling menyalahkan 是很实用的控场句，能保护面子，也能拉回事情。', '不羞辱，先解决。'),
      easyMistake: pair('不要把跨部门问题变成吵架。用 timeline 比用情绪更有效。', '事实先于情绪。'),
      trySay: pair('Kita urutkan fakta berdasarkan timeline.', '我们按时间线梳理事实。'),
    },
  },
  'EXP-LIF-151': {
    task: '员工没有主动汇报，出问题我最后才知道',
    indonesian: 'Kalau ada risiko seperti ini, saya harus tahu lebih awal, bukan setelah masalahnya besar.',
    explanation: '员工怕被骂或觉得能自己解决而不汇报时，建立什么必须立刻汇报、什么可以自己处理。',
    harvest: ['risiko seperti ini', 'tahu lebih awal', 'lapor lebih cepat', 'batas keputusan'],
    goldenScene: {
      situation: '问题已经发生两天，你今天才知道。员工说他以为自己能处理，不想打扰你。',
      goal: '成功建立早汇报规则，避免“出事先藏着”的文化。',
      dialogue: [
        line('我', 'Masalah ini kamu tahu sejak kapan?', '这个问题你什么时候知道的？'),
        line('员工', 'Sejak dua hari lalu, Pak.', '两天前，Pak。'),
        line('我', 'Kenapa baru lapor sekarang?', '为什么现在才汇报？'),
        line('员工', 'Saya pikir bisa saya selesaikan sendiri. Saya juga takut dimarahi.', '我以为自己能解决。我也怕被骂。'),
        line('我', 'Kalau ada risiko seperti ini, saya harus tahu lebih awal.', '如果有这种风险，我必须更早知道。'),
        line('员工', 'Berarti semua masalah harus langsung lapor, Pak?', '那是不是所有问题都要马上汇报，Pak？'),
        line('我', 'Masalah kecil boleh kamu selesaikan. Tapi kalau berdampak ke customer, uang, stok, atau deadline, wajib lapor.', '小问题你可以处理。但影响客户、钱、库存或 deadline 的，必须汇报。'),
        line('员工', 'Baik Pak, nanti saya lapor lebih cepat.', '好的 Pak，以后我更早汇报。'),
        line('我', 'Lapor bukan berarti dimarahi. Lapor supaya kita bisa bantu sebelum terlambat.', '汇报不是等于被骂。汇报是为了太晚前我们能帮忙。'),
      ],
      replies: [
        pair('Saya takut kalau lapor nanti dianggap gagal.', '我怕汇报会被认为失败。'),
        pair('Saya kira masih bisa saya handle sendiri.', '我以为自己还能处理。'),
        pair('Ke depan kalau menyangkut customer, saya langsung lapor.', '以后涉及客户，我马上汇报。'),
      ],
      variations: [
        pair('Kalau ragu, lebih baik lapor dulu.', '如果不确定，最好先汇报。'),
        pair('Kamu boleh bawa solusi saat lapor.', '你汇报时可以带方案。'),
        pair('Jangan tunggu masalahnya membesar.', '不要等问题变大。'),
        pair('Kita buat titik update setiap sore.', '我们设每天傍晚更新节点。'),
      ],
      decisions: [
        {
          situation: '员工担心汇报后会被责怪。',
          options: [
            pair('Saya tidak marah kalau kamu lapor cepat. Saya marah kalau disembunyikan.', '你早汇报我不会生气。藏着不说我才会生气。'),
            pair('Lapor dengan fakta dan opsi solusi, itu yang saya butuhkan.', '带事实和方案汇报，这才是我需要的。'),
          ],
        },
      ],
      localUsage: pair('在印尼团队里，保护面子很重要。明确说“早汇报不是挨骂”，能减少隐藏问题。', '安全感换来透明。'),
      easyMistake: pair('不要只骂为什么不说。要建立“哪些必须说”的边界。', '规则比情绪更可靠。'),
      trySay: pair('Lapor bukan berarti dimarahi. Lapor supaya kita bisa bantu sebelum terlambat.', '汇报不是等于被骂。汇报是为了太晚前我们能帮忙。'),
    },
  },
  'EXP-LIF-152': {
    task: '面试一个印尼员工',
    indonesian: 'Boleh ceritakan pengalaman kerja sebelumnya dan kenapa tertarik melamar di sini?',
    explanation: '中国老板完成一次基础面试：经历、离职原因、强项、处理问题、薪资、到岗时间和候选人提问。',
    harvest: ['pengalaman kerja sebelumnya', 'kenapa melamar', 'kelebihan kamu', 'ekspektasi gaji'],
    goldenScene: {
      situation: '你要面试一个印尼员工，不需要 HR 教材，只要能完成真实基础面试。',
      goal: '成功了解候选人的经历、能力、期望和可到岗时间。',
      dialogue: [
        line('我', 'Selamat pagi. Boleh perkenalkan diri dulu?', '早上好。可以先自我介绍一下吗？'),
        line('候选人', 'Pagi Pak. Nama saya Andi, sebelumnya kerja di bagian admin gudang.', '早上好 Pak。我叫 Andi，之前做仓库行政。'),
        line('我', 'Boleh ceritakan pengalaman kerja sebelumnya?', '可以讲一下之前的工作经验吗？'),
        line('候选人', 'Saya urus data stok, surat jalan, dan koordinasi dengan tim pengiriman.', '我处理库存数据、送货单，并和发货团队协调。'),
        line('我', 'Kenapa berhenti dari pekerjaan sebelumnya?', '为什么离开上一份工作？'),
        line('候选人', 'Kontrak saya selesai, Pak, dan saya cari tempat yang lebih berkembang.', '合同结束了，Pak，我想找更有发展的地方。'),
        line('我', 'Kelebihan kamu yang paling kuat apa?', '你最强的优点是什么？'),
        line('候选人', 'Saya teliti di data dan cukup cepat belajar sistem baru.', '我做数据比较细，也学新系统比较快。'),
        line('我', 'Ekspektasi gaji berapa dan kapan bisa mulai kerja?', '薪资期望多少，什么时候能开始上班？'),
        line('候选人', 'Saya berharap lima juta, dan bisa mulai minggu depan.', '我希望 500 万，下周可以开始。'),
      ],
      replies: [
        pair('Saya pernah menangani stok harian.', '我处理过每日库存。'),
        pair('Kalau ada masalah, saya biasanya cek data dulu.', '如果有问题，我通常先查数据。'),
        pair('Saya ingin tahu jam kerja dan masa percobaan di sini.', '我想了解这里的工作时间和试用期。'),
      ],
      variations: [
        pair('Apa yang kamu lakukan kalau data stok tidak cocok?', '如果库存数据不一致，你会怎么做？'),
        pair('Kamu lebih nyaman kerja sendiri atau dalam tim?', '你更习惯独立工作还是团队工作？'),
        pair('Apa pertanyaan kamu tentang perusahaan kami?', '你对我们公司有什么问题？'),
        pair('Kalau diterima, kapan paling cepat bisa mulai?', '如果录用，最快什么时候能开始？'),
      ],
      decisions: [
        {
          situation: '候选人薪资期望高于预算。',
          options: [
            pair('Budget kami di angka empat juta lima ratus. Apakah masih bisa dipertimbangkan?', '我们的预算是 450 万。还可以考虑吗？'),
            pair('Kalau performa bagus setelah masa percobaan, gaji bisa dibicarakan lagi.', '如果试用期后表现好，薪资可以再谈。'),
          ],
        },
      ],
      localUsage: pair('面试里 berhenti 听起来比 keluar/dipecat 更中性，适合问离职原因。', '问得自然，对方更愿意说真话。'),
      easyMistake: pair('不要一开始就只问工资。先问经历和能力，再谈条件。', '面试先判断匹配度。'),
      trySay: pair('Boleh ceritakan pengalaman kerja sebelumnya dan kenapa tertarik melamar di sini?', '可以讲一下之前工作经验，以及为什么想应聘这里吗？'),
    },
  },
  'EXP-LIF-153': {
    task: '员工准备离职，我要了解真正原因',
    indonesian: 'Saya ingin paham alasan sebenarnya. Apakah ini soal gaji, beban kerja, tim, atau keluarga?',
    explanation: '员工想离职时，不把它当背叛；了解真实原因，判断是否挽留，如果离开就安排交接。',
    harvest: ['alasan sebenarnya', 'beban kerja', 'bisa dipertimbangkan', 'serah terima'],
    goldenScene: {
      situation: '员工说想 resign。你不想马上生气，而是想了解真实原因并安排好下一步。',
      goal: '成功了解离职原因、判断是否挽留，并确认交接。',
      dialogue: [
        line('员工', 'Pak, saya mau bicara. Saya rencana resign bulan depan.', 'Pak，我想谈一下。我计划下个月离职。'),
        line('我', 'Baik, terima kasih sudah bicara langsung. Saya ingin paham alasan sebenarnya.', '好，谢谢你直接说。我想了解真实原因。'),
        line('我', 'Apakah ini soal gaji, beban kerja, tim, atau keluarga?', '是工资、工作压力、团队，还是家庭原因？'),
        line('员工', 'Lebih ke beban kerja dan keluarga, Pak.', '更多是工作压力和家庭，Pak。'),
        line('我', 'Bagian mana dari beban kerja yang paling berat?', '工作压力里哪一部分最重？'),
        line('员工', 'Jam pulang sering tidak pasti, saya sulit urus anak.', '下班时间经常不确定，我很难照顾孩子。'),
        line('我', 'Kalau jadwal lebih jelas, apakah masih bisa dipertimbangkan?', '如果时间更明确，还可以考虑留下吗？'),
        line('员工', 'Saya pikir dulu, Pak, tapi kemungkinan tetap resign.', '我先想想，Pak，但可能还是离职。'),
        line('我', 'Kalau begitu kita atur serah terima dengan baik supaya hubungan tetap baik.', '那我们好好安排交接，保持好关系。'),
      ],
      replies: [
        pair('Saya bukan tidak suka perusahaan, Pak.', '我不是不喜欢公司，Pak。'),
        pair('Kalau jadwal lebih jelas, mungkin bisa dipikirkan.', '如果时间更明确，也许可以考虑。'),
        pair('Saya siap bantu serah terima sampai selesai.', '我愿意帮忙交接到完成。'),
      ],
      variations: [
        pair('Saya tidak anggap ini sebagai pengkhianatan.', '我不把这看成背叛。'),
        pair('Apa yang bisa kami perbaiki dari sisi perusahaan?', '公司这边有什么可以改善？'),
        pair('Kapan hari terakhir yang kamu rencanakan?', '你计划最后一天是哪天？'),
        pair('Tolong buat daftar pekerjaan yang harus diserahterimakan.', '请列出需要交接的工作清单。'),
      ],
      decisions: [
        {
          situation: '员工还在犹豫是否留下。',
          options: [
            pair('Kamu pikirkan dua hari. Setelah itu kita bicara lagi dengan opsi yang jelas.', '你考虑两天。之后我们带明确选项再谈。'),
            pair('Kalau sudah keputusan final, kita fokus serah terima yang rapi.', '如果已经最终决定，我们就专注做好交接。'),
          ],
        },
      ],
      localUsage: pair('员工离职谈话里，hubungan tetap baik 很重要。印尼职场关系常会延续。', '人走，关系不一定断。'),
      easyMistake: pair('不要马上说“不准走”或“你不忠诚”。先问原因和交接。', '离职不是背叛。'),
      trySay: pair('Saya ingin paham alasan sebenarnya.', '我想了解真实原因。'),
    },
  },
  'EXP-LIF-154': {
    task: '今天销量突然下降，叫运营查原因',
    indonesian: 'GMV kemarin berapa, hari ini berapa, dan penurunannya paling besar di produk mana?',
    explanation: '销量突然下降时，用简单印尼语问 GMV、流量、转化、广告、价格和主要原因。',
    harvest: ['GMV kemarin', 'penurunan terbesar', 'traffic turun', 'conversion turun'],
    goldenScene: {
      situation: '今天电商销售突然下降，运营只说“sepi”。你需要用数据追原因。',
      goal: '成功找到销量下降的主要原因，并确认今天调整方案和复盘时间。',
      dialogue: [
        line('我', 'GMV kemarin berapa, hari ini berapa?', '昨天 GMV 多少，今天多少？'),
        line('运营', 'Kemarin seratus juta, hari ini baru enam puluh juta, Pak.', '昨天一亿，今天才六千万，Pak。'),
        line('我', 'Penurunannya paling besar di produk mana?', '下降最大的是哪个产品？'),
        line('运营', 'Produk A turun paling besar.', '产品 A 下降最大。'),
        line('我', 'Traffic turun atau conversion yang turun?', '是流量下降，还是转化下降？'),
        line('运营', 'Traffic masih mirip, tapi conversion turun.', '流量差不多，但转化下降。'),
        line('我', 'Iklan, harga, atau stok ada perubahan?', '广告、价格或库存有变化吗？'),
        line('运营', 'Harga naik sedikit kemarin, dan voucher mati pagi ini.', '昨天价格涨了一点，优惠券今天早上停了。'),
        line('我', 'Oke, aktifkan voucher lagi dan cek harga kompetitor. Jam lima kita review ulang.', '好，重新打开优惠券，并查竞品价格。五点我们再复盘。'),
      ],
      replies: [
        pair('Traffic tidak turun banyak, conversion yang turun.', '流量没降很多，是转化降了。'),
        pair('Voucher mati sejak pagi.', '优惠券从早上停了。'),
        pair('Kompetitor sedang promo harga.', '竞品正在做价格促销。'),
      ],
      variations: [
        pair('Produk mana yang paling turun?', '哪个产品下降最多？'),
        pair('Apakah ads ada perubahan budget?', '广告预算有变化吗？'),
        pair('Cek harga dan voucher sekarang.', '现在查价格和优惠券。'),
        pair('Jam berapa kita lihat data lagi?', '几点再看数据？'),
      ],
      decisions: [
        {
          situation: '运营说还要观察，但没有动作。',
          options: [
            pair('Observasi boleh, tapi hari ini harus ada adjustment.', '观察可以，但今天必须有调整。'),
            pair('Aktifkan voucher dulu, lalu lihat conversion dua jam lagi.', '先打开优惠券，两小时后看转化。'),
          ],
        },
      ],
      localUsage: pair('印尼电商团队常混用 GMV、traffic、conversion。老板不用讲课，只要会问数据。', '用数据替代感觉。'),
      easyMistake: pair('不要只问 kenapa sepi。要拆成流量、转化、价格、广告、库存。', '销量下降要拆指标。'),
      trySay: pair('Traffic turun atau conversion yang turun?', '是流量下降，还是转化下降？'),
    },
  },
  'EXP-LIF-155': {
    task: '广告花很多钱，但订单很少',
    indonesian: 'Spend iklan hari ini berapa, GMV berapa, dan ROAS-nya masih masuk atau tidak?',
    explanation: '广告烧钱订单少时，问 spend、GMV、ROAS、CTR、conversion，决定停哪条、留哪条、何时复盘。',
    harvest: ['spend iklan', 'ROAS masih masuk', 'CTR turun', 'stop campaign'],
    goldenScene: {
      situation: '广告今天花费很高，但订单很少。运营只说“algoritma lagi jelek”。你要看数据决定。',
      goal: '成功判断哪条广告烧钱、哪条保留、调整什么、何时再看。',
      dialogue: [
        line('我', 'Spend iklan hari ini berapa?', '今天广告花了多少？'),
        line('运营', 'Sudah dua belas juta, Pak.', '已经 1200 万，Pak。'),
        line('我', 'GMV dari iklan berapa dan ROAS-nya berapa?', '广告带来的 GMV 多少，ROAS 多少？'),
        line('运营', 'GMV sekitar dua puluh juta, ROAS cuma 1,6.', 'GMV 大概 2000 万，ROAS 只有 1.6。'),
        line('我', 'CTR dan conversion bagaimana?', 'CTR 和转化怎么样？'),
        line('运营', 'CTR lumayan, tapi conversion rendah.', 'CTR 还可以，但转化低。'),
        line('我', 'Campaign mana yang paling boros tapi order sedikit?', '哪条 campaign 最烧钱但订单少？'),
        line('运营', 'Campaign video kedua, spend besar tapi order cuma lima.', '第二条视频 campaign，花费大但只有 5 单。'),
        line('我', 'Stop campaign itu dulu. Budget pindah ke campaign yang ROAS di atas tiga. Jam delapan kita cek lagi.', '先停那条。预算转到 ROAS 超过 3 的 campaign。八点再看。'),
      ],
      replies: [
        pair('CTR masih oke, tapi conversion turun.', 'CTR 还可以，但转化下降。'),
        pair('Campaign ini banyak klik, tapi sedikit checkout.', '这条点击多，但结账少。'),
        pair('ROAS campaign pertama masih bagus.', '第一条 campaign 的 ROAS 还好。'),
      ],
      variations: [
        pair('Jangan tambah budget sebelum ROAS jelas.', 'ROAS 清楚前不要加预算。'),
        pair('Mana iklan yang harus kita stop?', '哪条广告应该停？'),
        pair('Creative atau landing page yang bermasalah?', '是素材还是落地页有问题？'),
        pair('Kita lihat data lagi dua jam lagi.', '我们两小时后再看数据。'),
      ],
      decisions: [
        {
          situation: '运营想继续烧预算等算法学习。',
          options: [
            pair('Boleh test, tapi batasi budget. Jangan biarkan spend bocor.', '可以测试，但限制预算。不要让花费失控。'),
            pair('Kalau ROAS di bawah dua sampai jam delapan, stop dulu.', '如果八点前 ROAS 低于 2，先停。'),
          ],
        },
      ],
      localUsage: pair('ROAS 在印尼电商运营里常直接说。可以问 masih masuk 吗，意思是还划算吗。', '老板问结果，不上广告课。'),
      easyMistake: pair('不要只问订单少为什么。广告要看 spend、GMV、ROAS、CTR、conversion。', '烧钱要看效率。'),
      trySay: pair('ROAS-nya masih masuk atau tidak?', 'ROAS 还划算吗？'),
    },
  },
  'EXP-LIF-156': {
    task: '产品突然爆单，但库存快没了',
    indonesian: 'Stok sekarang tinggal berapa, dan dengan speed jual sekarang masih cukup berapa jam?',
    explanation: '爆单库存不足时，确认库存、销售速度、备用库存、在途、补货、广告和限量，避免超卖。',
    harvest: ['stok tinggal berapa', 'speed jual', 'stok cadangan', 'hindari oversell'],
    goldenScene: {
      situation: '一个产品突然爆单，运营很高兴，但仓库说库存快没了。',
      goal: '成功判断还能卖多久，并采取补货、降广告或限量措施避免超卖。',
      dialogue: [
        line('我', 'Stok sekarang tinggal berapa?', '现在库存还剩多少？'),
        line('运营', 'Tinggal delapan ratus pcs, Pak.', '只剩 800 件，Pak。'),
        line('我', 'Per jam sekarang jual berapa?', '现在每小时卖多少？'),
        line('运营', 'Sekitar seratus lima puluh pcs per jam.', '大概每小时 150 件。'),
        line('我', 'Berarti masih cukup sekitar lima jam. Ada stok cadangan di gudang?', '那大概只够五小时。仓库有备用库存吗？'),
        line('仓库', 'Cadangan ada tiga ratus pcs, tapi belum masuk sistem.', '备用有 300 件，但还没进系统。'),
        line('我', 'Barang in transit ada berapa dan sampai kapan?', '在途货多少，什么时候到？'),
        line('运营', 'Dua ribu pcs sampai besok siang.', '2000 件明天中午到。'),
        line('我', 'Turunkan ads dulu dan batasi promo. Jangan sampai oversell.', '先降低广告并限制促销。不要超卖。'),
      ],
      replies: [
        pair('Kalau ads tetap jalan, stok habis malam ini.', '如果广告继续跑，今晚库存会卖完。'),
        pair('Stok cadangan belum masuk sistem.', '备用库存还没进系统。'),
        pair('Barang in transit sampai besok siang.', '在途货明天中午到。'),
      ],
      variations: [
        pair('Apakah perlu matikan live product ini dulu?', '需要先在直播里下掉这个产品吗？'),
        pair('Update stok di sistem sekarang.', '现在更新系统库存。'),
        pair('Batasi quantity per customer.', '限制每个客户购买数量。'),
        pair('Kalau stok habis, jangan terima order baru.', '如果库存没了，不要接新订单。'),
      ],
      decisions: [
        {
          situation: '运营不想降广告，因为销量很好。',
          options: [
            pair('Kalau oversell, masalah customer lebih besar. Ads harus diturunkan dulu.', '如果超卖，客户问题更大。广告必须先降。'),
            pair('Kita jaga sales, tapi stok harus aman dulu.', '我们要保销量，但库存必须先安全。'),
          ],
        },
      ],
      localUsage: pair('Oversell 在印尼电商团队也常用，表示卖超库存。', '爆单时更要控库存。'),
      easyMistake: pair('不要只庆祝爆单。要马上问还能卖多久。', '爆单也可能变事故。'),
      trySay: pair('Dengan speed jual sekarang masih cukup berapa jam?', '按现在销售速度，还够卖几个小时？'),
    },
  },
  'EXP-LIF-167': {
    task: '直播间有人看，但是没人买',
    indonesian: 'Penonton ada, tapi order sedikit. Kita cek klik produk, add to cart, dan closing-nya.',
    explanation: '直播有人看没人买时，不简单怪主播，而是看点击、加购、成交、价格、话术和用户问题。',
    harvest: ['penonton ada', 'klik produk', 'add to cart', 'closing'],
    goldenScene: {
      situation: '直播间在线人数不错，但订单很少。团队有人开始怪主播，你要用数据和环节分析。',
      goal: '成功找出直播不成交的关键环节，并确定下一场测试点。',
      dialogue: [
        line('我', 'Penonton live tadi berapa?', '刚才直播观众多少？'),
        line('运营', 'Rata-rata tiga ratus orang, Pak.', '平均 300 人，Pak。'),
        line('我', 'Klik produk berapa, add to cart berapa, order berapa?', '商品点击多少，加购多少，订单多少？'),
        line('运营', 'Klik lumayan, add to cart rendah, order cuma dua belas.', '点击还可以，加购低，订单只有 12。'),
        line('我', 'Hari ini host push produk apa?', '今天主播主推什么产品？'),
        line('运营', 'Produk A, tapi banyak yang tanya ukuran dan garansi.', '产品 A，但很多人问尺寸和保修。'),
        line('我', 'Berarti mungkin info belum jelas, bukan hanya host kurang bagus.', '那可能是信息不清楚，不只是主播不好。'),
        line('主播', 'Saya juga bingung jawab garansi karena belum ada script.', '我也不知道怎么回答保修，因为没有话术。'),
        line('我', 'Next live test: jelaskan ukuran, garansi, dan promo di awal.', '下一场测试：开头说明尺寸、保修和促销。'),
      ],
      replies: [
        pair('Banyak penonton tanya hal yang sama.', '很多观众问同样问题。'),
        pair('Harga dianggap belum menarik.', '价格被认为还不够吸引。'),
        pair('Host butuh script untuk garansi.', '主播需要保修话术。'),
      ],
      variations: [
        pair('Jangan langsung salahkan host dulu.', '不要一上来就怪主播。'),
        pair('Pertanyaan penonton paling banyak apa?', '观众最多问什么？'),
        pair('Bagian mana yang membuat orang tidak checkout?', '哪个环节让人没有结账？'),
        pair('Next live kita test angle baru.', '下一场直播测试新角度。'),
      ],
      decisions: [
        {
          situation: '团队说换主播就好。',
          options: [
            pair('Sebelum ganti host, kita perbaiki script dan offer dulu.', '换主播前，我们先改话术和优惠。'),
            pair('Kalau setelah dua kali test tetap rendah, baru evaluasi host.', '如果两次测试后还是低，再评估主播。'),
          ],
        },
      ],
      localUsage: pair('直播复盘不要只看 penonton，要看 klik、cart、order 这条链路。', '有人看不等于会买。'),
      easyMistake: pair('不要简单怪主播。先看 offer、script、produk、harga。', '问题可能在系统，不只在人。'),
      trySay: pair('Penonton ada, tapi order sedikit. Kita cek klik produk, add to cart, dan closing-nya.', '有人看但订单少。我们查商品点击、加购和成交。'),
    },
  },
  'EXP-LIF-168': {
    task: '主播今天状态很差，我要跟她谈',
    indonesian: 'Hari ini performa live turun. Saya mau tahu, kamu kurang sehat, kurang siap, atau ada masalah lain?',
    explanation: '主播状态差时，既看数据和准备，也尊重人的状态，决定休息、换场或改准备方式。',
    harvest: ['performa live turun', 'kurang sehat', 'kurang siap', 'persiapan live'],
    goldenScene: {
      situation: '今天直播数据下降，主播说话没精神。你需要沟通原因和改进，而不是当场羞辱。',
      goal: '成功了解状态原因，明确下一场准备或是否休息/换场。',
      dialogue: [
        line('我', 'Hari ini performa live turun. Kamu merasa bagaimana?', '今天直播表现下降。你感觉怎么样？'),
        line('主播', 'Maaf Pak, saya agak pusing dari pagi.', '抱歉 Pak，我早上开始有点头晕。'),
        line('我', 'Kamu kurang sehat, kurang siap, atau ada masalah lain?', '你是身体不舒服、准备不足，还是有其他问题？'),
        line('主播', 'Kurang sehat, tapi saya juga belum hafal promo baru.', '身体不太舒服，但我也还没熟悉新促销。'),
        line('我', 'Data turun di mana? Penonton, klik, atau closing?', '数据哪里下降？观众、点击还是成交？'),
        line('运营', 'Closing turun paling besar, Pak.', '成交下降最大，Pak。'),
        line('我', 'Untuk next live, script promo harus siap sebelum mulai.', '下一场直播前，促销话术必须准备好。'),
        line('主播', 'Baik Pak. Kalau boleh saya istirahat satu slot dulu.', '好的 Pak。如果可以，我先休息一场。'),
        line('我', 'Oke, kamu istirahat satu slot. Slot berikutnya kita pakai host cadangan.', '好，你休息一场。下一场用备用主播。'),
      ],
      replies: [
        pair('Saya kurang siap untuk promo baru.', '我对新促销准备不够。'),
        pair('Saya masih bisa live, tapi mungkin tidak maksimal.', '我还能播，但可能状态不够好。'),
        pair('Kalau ada script, saya lebih siap.', '如果有话术，我会更准备好。'),
      ],
      variations: [
        pair('Saya bahas ini supaya next live lebih baik, bukan untuk menyalahkan.', '我谈这个是为了下一场更好，不是为了责怪。'),
        pair('Kalau sakit, bilang sebelum live mulai.', '如果生病，直播前说。'),
        pair('Bagian mana dari script yang belum jelas?', '话术哪部分不清楚？'),
        pair('Kita siapkan host cadangan untuk kondisi seperti ini.', '这种情况我们准备备用主播。'),
      ],
      decisions: [
        {
          situation: '主播坚持继续，但状态明显不好。',
          options: [
            pair('Lebih baik istirahat satu slot daripada performa turun terus.', '与其表现继续下降，不如休息一场。'),
            pair('Kamu ikut briefing dulu, lalu kita lihat apakah siap untuk slot berikutnya.', '你先参加 brief，再看下一场是否准备好。'),
          ],
        },
      ],
      localUsage: pair('评价主播时说 performa turun 比 kamu jelek 更职业，也更不伤人。', '尊重人，但管理结果。'),
      easyMistake: pair('不要把身体状态和工作准备混在一起骂。要分开问。', '先了解，再要求。'),
      trySay: pair('Saya mau tahu, kamu kurang sehat, kurang siap, atau ada masalah lain?', '我想知道，你是身体不舒服、准备不足，还是有其他问题？'),
    },
  },
  'EXP-LIF-169': {
    task: '客户给了一星差评',
    indonesian: 'Jangan minta customer hapus review dulu. Kita pahami masalahnya dan beri solusi dulu.',
    explanation: '一星差评先查订单、问题来源、道歉和解决方案，禁止一上来要求删除差评。',
    harvest: ['review bintang satu', 'cek order', 'minta maaf dulu', 'beri solusi'],
    goldenScene: {
      situation: '客户给了一星差评，客服第一反应想让客户删除。你要先解决问题。',
      goal: '成功查清差评原因、联系客户、提供补发/退款等方案，并内部复盘。',
      dialogue: [
        line('我', 'Review bintang satu ini dari order mana?', '这个一星差评来自哪个订单？'),
        line('客服', 'Order nomor 2381, Pak. Customer bilang barang rusak.', '2381 订单，Pak。客户说商品坏了。'),
        line('我', 'Cek dulu: masalah produk, pengiriman, atau customer service?', '先查：是产品、物流还是客服问题？'),
        line('客服', 'Sepertinya produk pecah saat pengiriman.', '看起来是运输中破损。'),
        line('我', 'Jangan minta customer hapus review dulu.', '先不要让客户删除差评。'),
        line('客服', 'Jadi kami balas bagaimana?', '那我们怎么回复？'),
        line('我', 'Minta maaf dulu, tanya foto dan kondisi barang, lalu tawarkan kirim ulang atau refund.', '先道歉，问照片和商品情况，然后提供补发或退款。'),
        line('客服', 'Baik Pak. Setelah customer puas, baru boleh tanya soal review?', '好的 Pak。客户满意后，才可以问评价吗？'),
        line('我', 'Iya, tapi jangan memaksa. Fokus solusi dulu.', '对，但不要强迫。先专注解决。'),
      ],
      replies: [
        pair('Customer marah karena barang datang pecah.', '客户生气是因为到货破损。'),
        pair('Kami tawarkan kirim ulang hari ini.', '我们提供今天补发。'),
        pair('Setelah selesai, kita cek packing internal.', '解决后，我们检查内部包装。'),
      ],
      variations: [
        pair('Maaf atas pengalaman yang kurang baik.', '很抱歉给您不好的体验。'),
        pair('Boleh kami bantu cek detail ordernya?', '可以让我们帮您查订单详情吗？'),
        pair('Kami bisa kirim ulang atau proses refund.', '我们可以补发或处理退款。'),
        pair('Setelah masalah selesai, baru evaluasi review.', '问题解决后，再评估评价。'),
      ],
      decisions: [
        {
          situation: '客服想先送优惠券换删除评价。',
          options: [
            pair('Jangan langsung tawarkan voucher. Selesaikan masalah barang dulu.', '不要直接给优惠券。先解决商品问题。'),
            pair('Kalau customer sudah puas, voucher bisa jadi tambahan, bukan pengganti solusi.', '客户满意后，优惠券可以是补充，不是替代方案。'),
          ],
        },
      ],
      localUsage: pair('印尼客服里 minta maaf dulu 很重要，但道歉后必须跟 solusi。', '道歉不是结束，是开始。'),
      easyMistake: pair('不要一上来让客户删差评。先解决真实问题。', '差评管理先服务。'),
      trySay: pair('Kita pahami masalahnya dan beri solusi dulu.', '我们先理解问题并提供解决方案。'),
    },
  },
  'EXP-LIF-170': {
    task: '大量客户问同一个问题，客服回答不一致',
    indonesian: 'Kalau pertanyaannya sama, informasi inti harus sama, walaupun bahasanya boleh natural.',
    explanation: '客服回答不一致时，收集聊天记录、找高频问题、制定核心信息，同时允许自然表达。',
    harvest: ['pertanyaan yang sama', 'informasi inti', 'jawaban standar', 'cek chat sample'],
    goldenScene: {
      situation: '很多客户问同一个问题，但客服 A 说可以退，客服 B 说不可以，投诉开始增加。',
      goal: '成功统一核心信息，同时不把客服变成机械复制。',
      dialogue: [
        line('我', 'Pertanyaan customer yang paling sering minggu ini apa?', '这周客户最常问的问题是什么？'),
        line('客服主管', 'Paling banyak soal garansi dan cara retur.', '最多是保修和退货方式。'),
        line('我', 'Tolong kumpulkan lima chat sample.', '请收集五个聊天样本。'),
        line('客服主管', 'Ini Pak. Jawaban tiap CS memang beda-beda.', '这是 Pak。每个客服回答确实不同。'),
        line('我', 'Kalau pertanyaannya sama, informasi inti harus sama.', '如果问题一样，核心信息必须一致。'),
        line('客服', 'Berarti harus copy paste semua?', '那是不是全部都要复制粘贴？'),
        line('我', 'Tidak. Bahasa boleh natural, tapi poin inti tidak boleh berubah.', '不是。表达可以自然，但核心点不能变。'),
        line('客服主管', 'Kita buat jawaban standar untuk garansi dan retur.', '我们做保修和退货的标准回答。'),
        line('我', 'Besok saya mau cek sample chat lagi dan lihat komplain turun atau tidak.', '明天我要再抽查聊天样本，看投诉有没有下降。'),
      ],
      replies: [
        pair('CS bingung karena belum ada panduan inti.', '客服困惑是因为没有核心指南。'),
        pair('Bahasanya boleh beda, tapi informasi harus sama.', '语言可以不同，但信息必须一致。'),
        pair('Kami buat daftar pertanyaan paling sering.', '我们做最高频问题清单。'),
      ],
      variations: [
        pair('Apa jawaban yang paling aman untuk customer?', '对客户最稳妥的回答是什么？'),
        pair('Jangan janji hal yang tidak sesuai policy.', '不要承诺不符合政策的事情。'),
        pair('Tolong audit chat secara random.', '请随机抽查聊天。'),
        pair('Kalau tidak yakin, eskalasi ke supervisor.', '如果不确定，升级给主管。'),
      ],
      decisions: [
        {
          situation: '客服担心标准答案太僵硬。',
          options: [
            pair('Kita standarkan informasi, bukan gaya bicara.', '我们统一信息，不统一说话风格。'),
            pair('Boleh natural, tapi jangan ubah syarat garansi.', '可以自然表达，但不要改变保修条件。'),
          ],
        },
      ],
      localUsage: pair('Informasi inti 是“核心信息”，适合避免客服话术机械化。', '统一事实，不复制机器人。'),
      easyMistake: pair('不要要求所有客服逐字复制。这样容易僵硬，也不解决理解问题。', '标准化的是信息。'),
      trySay: pair('Informasi inti harus sama, walaupun bahasanya boleh natural.', '核心信息必须一致，即使表达可以自然。'),
    },
  },
  'EXP-LIF-171': {
    task: '订单很多，但仓库发货太慢',
    indonesian: 'Order yang belum dikirim berapa, dan order paling lama sudah tertahan berapa hari?',
    explanation: '订单多但发货慢时，查未发数量、最老订单、卡在拣货/打包/人手/系统，并定今天必须发多少。',
    harvest: ['belum dikirim', 'order paling lama', 'tertahan berapa hari', 'target kirim hari ini'],
    goldenScene: {
      situation: '订单堆积，客户催发货。仓库说“lagi diproses”，但你需要具体瓶颈和今天目标。',
      goal: '成功找出发货慢的卡点，临时调人，并确认今晚复盘。',
      dialogue: [
        line('我', 'Order yang belum dikirim berapa?', '未发货订单多少？'),
        line('仓库', 'Sekitar delapan ratus order, Pak.', '大概 800 单，Pak。'),
        line('我', 'Order paling lama sudah tertahan berapa hari?', '最老订单已经卡了几天？'),
        line('仓库', 'Ada yang tiga hari belum keluar.', '有些三天还没发出。'),
        line('我', 'Masalahnya di picking, packing, orang kurang, atau sistem?', '问题在拣货、打包、人不够，还是系统？'),
        line('仓库', 'Picking masih oke, packing yang lambat. Orang kurang dua.', '拣货还可以，打包慢。少两个人。'),
        line('我', 'Hari ini minimal harus kirim berapa order?', '今天最低必须发多少单？'),
        line('仓库', 'Kalau tambah dua orang, bisa kirim lima ratus order.', '如果加两个人，可以发 500 单。'),
        line('我', 'Oke, ambil dua orang dari tim live setelah jam empat. Jam sembilan malam kita review.', '好，四点后从直播团队调两个人。晚上九点复盘。'),
      ],
      replies: [
        pair('Packing lebih lambat daripada picking.', '打包比拣货慢。'),
        pair('Order paling lama tertahan tiga hari.', '最老订单卡了三天。'),
        pair('Kalau tambah orang, target lima ratus order realistis.', '如果加人，500 单目标现实。'),
      ],
      variations: [
        pair('Jangan jawab “lagi proses” saja, kasih angka.', '不要只回答“处理中”，给数字。'),
        pair('Pisahkan order paling lama dulu.', '先把最老订单分出来。'),
        pair('Ada kendala di sistem scan?', '扫码系统有问题吗？'),
        pair('Kirim update progres setiap dua jam.', '每两小时更新进度。'),
      ],
      decisions: [
        {
          situation: '仓库说大家都忙，没有人能调。',
          options: [
            pair('Prioritas hari ini adalah order tertahan. Tim lain bantu packing dulu.', '今天优先是卡住的订单。其他团队先帮打包。'),
            pair('Kalau target tidak tercapai, kita perlu overtime malam ini.', '如果目标达不到，今晚需要加班。'),
          ],
        },
      ],
      localUsage: pair('Order tertahan 很适合表达“卡住未发的订单”。', '仓库问题要看最老订单。'),
      easyMistake: pair('不要只看当天新单。先处理 paling lama，减少投诉。', '老订单优先清。'),
      trySay: pair('Order paling lama sudah tertahan berapa hari?', '最老订单已经卡了几天？'),
    },
  },
  'EXP-LIF-172': {
    task: '平台大促马上开始，团队还没准备好',
    indonesian: 'Campaign mulai besok. Kita cek checklist terakhir: harga, voucher, stok, ads, live, CS, dan gudang.',
    explanation: '大促前主持准备会：活动时间、价格、券、库存、Banner、广告、直播、客服、仓库和负责人。',
    harvest: ['campaign mulai besok', 'checklist terakhir', 'siapa PIC', 'sebelum live'],
    goldenScene: {
      situation: '平台大促明天开始，但团队信息不一致。你需要主持一次上线前 checklist 会议。',
      goal: '成功确认每个模块准备状态、负责人和上线前最后检查。',
      dialogue: [
        line('我', 'Campaign mulai besok jam berapa?', '大促明天几点开始？'),
        line('运营', 'Mulai jam nol-nol, Pak.', '零点开始，Pak。'),
        line('我', 'Kita cek checklist terakhir: harga dan voucher sudah final?', '我们查最后 checklist：价格和券最终了吗？'),
        line('运营', 'Harga sudah, voucher masih tunggu approval platform.', '价格好了，券还等平台批准。'),
        line('我', 'Stok untuk produk utama aman?', '主推产品库存安全吗？'),
        line('仓库', 'Aman untuk dua hari, tapi produk B agak tipis.', '两天内安全，但产品 B 有点紧。'),
        line('我', 'Ads dan live siapa PIC?', '广告和直播谁负责？'),
        line('运营', 'Ads saya, live Bu Lina.', '广告我负责，直播 Lina 女士负责。'),
        line('我', 'CS sudah punya jawaban untuk promo dan retur?', '客服有促销和退货回答了吗？'),
        line('客服', 'Belum lengkap, Pak. Kami butuh template malam ini.', '还不完整，Pak。我们今晚需要模板。'),
        line('我', 'Oke. Jam sembilan malam semua PIC kirim status final di grup.', '好。晚上九点所有 PIC 在群里发最终状态。'),
      ],
      replies: [
        pair('Voucher masih menunggu approval platform.', '优惠券还在等平台批准。'),
        pair('Produk B stoknya agak tipis.', '产品 B 库存有点紧。'),
        pair('CS butuh template jawaban promo.', '客服需要促销回答模板。'),
      ],
      variations: [
        pair('Siapa PIC untuk banner?', 'Banner 谁负责？'),
        pair('Kalau voucher belum approve, plan B apa?', '如果券没批准，B 计划是什么？'),
        pair('Gudang siap tambah orang besok?', '仓库明天准备加人吗？'),
        pair('Sebelum mulai, semua status harus hijau.', '开始前所有状态必须是绿色。'),
      ],
      decisions: [
        {
          situation: '优惠券审批还没下来。',
          options: [
            pair('Siapkan promo alternatif kalau voucher belum aktif jam sepuluh malam.', '如果晚上十点券还没激活，准备替代促销。'),
            pair('Jangan tunggu besok pagi. Follow up platform sekarang.', '不要等明早。现在跟进平台。'),
          ],
        },
      ],
      localUsage: pair('PIC 在印尼办公室常用，表示负责人。Checklist 也常直接用。', '大促靠清单，不靠感觉。'),
      easyMistake: pair('不要只问“ready?” 要逐项问 harga、voucher、stok、ads、live、CS、gudang。', '准备要逐项过。'),
      trySay: pair('Kita cek checklist terakhir: harga, voucher, stok, ads, live, CS, dan gudang.', '我们查最后 checklist：价格、券、库存、广告、直播、客服和仓库。'),
    },
  },
  'EXP-LIF-173': {
    task: '晚上复盘整个电商业务',
    indonesian: 'Kita review harian: GMV, iklan, ROAS, produk terbaik, masalah CS, stok, gudang, dan tiga prioritas besok.',
    explanation: '用简单印尼语完成 Daily E-commerce Review：GMV、广告、ROAS、产品、直播、客服、差评、库存、仓库和明日三件事。',
    harvest: ['review harian', 'produk terbaik', 'masalah CS', 'tiga prioritas besok'],
    goldenScene: {
      situation: '晚上你要带团队复盘一天电商业务，不能只听“hari ini lumayan”。',
      goal: '成功完成一次 Daily E-commerce Review，并定出明天最重要的三件事。',
      dialogue: [
        line('我', 'Kita review harian. GMV hari ini berapa?', '我们做每日复盘。今天 GMV 多少？'),
        line('运营', 'GMV seratus dua puluh juta, naik dua puluh persen dari kemarin.', 'GMV 1.2 亿，比昨天涨 20%。'),
        line('我', 'Spend iklan dan ROAS bagaimana?', '广告花费和 ROAS 怎么样？'),
        line('运营', 'Spend lima belas juta, ROAS rata-rata 3,2.', '花费 1500 万，平均 ROAS 3.2。'),
        line('我', 'Produk terbaik dan produk terburuk apa?', '最好和最差产品是什么？'),
        line('运营', 'Produk A paling bagus, produk C turun karena stok tipis.', '产品 A 最好，产品 C 因库存紧下降。'),
        line('我', 'Live dan CS ada masalah apa?', '直播和客服有什么问题？'),
        line('客服', 'Ada dua komplain soal pengiriman lambat dan satu review bintang satu.', '有两个发货慢投诉和一个一星评价。'),
        line('我', 'Stok dan gudang aman untuk besok?', '明天库存和仓库安全吗？'),
        line('仓库', 'Stok A aman, tapi order pending masih tiga ratus.', 'A 库存安全，但待发订单还有 300。'),
        line('我', 'Besok tiga prioritas: bersihkan order pending, jaga stok produk C, dan optimasi iklan produk A.', '明天三件重点：清待发订单、守住产品 C 库存、优化产品 A 广告。'),
      ],
      replies: [
        pair('Produk terbaik hari ini produk A.', '今天最好产品是 A。'),
        pair('Masalah terbesar ada di pengiriman lambat.', '最大问题在发货慢。'),
        pair('Besok fokus ke order pending dan stok.', '明天重点是待发订单和库存。'),
      ],
      variations: [
        pair('Jangan hanya bilang bagus, kasih angka.', '不要只说好，给数字。'),
        pair('Apa satu masalah yang paling urgent?', '最紧急的一个问题是什么？'),
        pair('Apa yang harus kita stop besok?', '明天什么要停？'),
        pair('Apa tiga prioritas besok?', '明天三个优先事项是什么？'),
      ],
      decisions: [
        {
          situation: '团队给了很多问题，明天事项太多。',
          options: [
            pair('Kita pilih tiga prioritas saja supaya fokus.', '我们只选三个优先事项，保持聚焦。'),
            pair('Yang lain dicatat, tapi tidak jadi prioritas besok.', '其他记下来，但不作为明天优先。'),
          ],
        },
      ],
      localUsage: pair('Daily review 里 jangan hanya bilang bagus, kasih angka 是老板非常实用的控场句。', '复盘要从感觉变成数字。'),
      easyMistake: pair('不要让复盘变成流水账。最后必须落到明天三件事。', '复盘服务于明天行动。'),
      trySay: pair('Besok tiga prioritas: bersihkan order pending, jaga stok, dan optimasi iklan.', '明天三个重点：清待发订单、守库存、优化广告。'),
    },
  },
};
