import type { GoldenSceneContent } from '@/lib/golden-scenes';
import type { LifeCategory } from '@/lib/life-experiences';

export type GoldenExperiencePatch = {
  category?: LifeCategory;
  task: string;
  indonesian: string;
  explanation: string;
  harvest: string[];
  goldenScene: GoldenSceneContent;
};

const line = (speaker: string, indonesian: string, chinese: string) => ({ speaker, indonesian, chinese });
const pair = (indonesian: string, chinese: string) => ({ indonesian, chinese });

export const lifeGoldenBatch6: Record<string, GoldenExperiencePatch> = {
  'EXP-LIF-174': {
    category: 'friends',
    task: '第一次认识印尼朋友，怎么把聊天聊起来',
    indonesian: 'Hai, aku Li. Kamu kenal teman-teman di sini dari mana?',
    explanation: '第一次见面时，不停留在问名字，而是顺着“怎么认识这里的人、住哪里、做什么、来自哪里”找到轻松话题。',
    harvest: ['kenal dari mana', 'tinggal di mana', 'kerja apa', 'asalnya dari mana'],
    goldenScene: {
      situation: '你第一次参加朋友的小聚会，只认识介绍你来的人。你需要把第一次见面的聊天自然聊起来。',
      goal: '第一次见面不冷场，并自然留下继续聊的空间。',
      dialogue: [
        line('我', 'Hai, aku Li. Kamu kenal teman-teman di sini dari mana?', '你好，我是 Li。你是怎么认识这里这些朋友的？'),
        line('朋友', 'Aku kenal dari kampus dulu. Kamu sendiri kenal siapa?', '我以前大学认识的。你呢，认识谁？'),
        line('我', 'Aku kenal Rina dari kerja. Kamu tinggal di daerah sini juga?', '我是在工作上认识 Rina 的。你也住这附近吗？'),
        line('朋友', 'Nggak, aku tinggal di Kemang. Lumayan jauh sih.', '不是，我住 Kemang。其实挺远的。'),
        line('我', 'Oh, Kemang banyak tempat makan enak ya. Kamu kerja di bidang apa?', '哦，Kemang 很多好吃的地方吧。你做什么行业？'),
        line('朋友', 'Aku di marketing. Kamu dari China ya?', '我做市场。你来自中国吧？'),
        line('我', 'Iya. Aku baru belajar ngobrol santai pakai bahasa Indonesia.', '对。我刚开始学习用印尼语轻松聊天。'),
        line('朋友', 'Sudah bagus kok. Santai aja.', '已经不错啦。放轻松。'),
      ],
      replies: [
        pair('Aku kenal dari teman kantor.', '我是通过办公室朋友认识的。'),
        pair('Aku tinggal agak jauh dari sini.', '我住得离这里有点远。'),
        pair('Aku kerja di marketing.', '我做市场。'),
      ],
      variations: [
        pair('Kamu biasanya nongkrong di mana?', '你平时一般在哪里聚？'),
        pair('Kamu asalnya dari mana?', '你老家是哪里？'),
        pair('Aku masih baru di Jakarta.', '我刚来雅加达不久。'),
        pair('Kalau tempat makan enak di sini, ada rekomendasi?', '这附近有什么好吃的推荐吗？'),
      ],
      decisions: [
        {
          situation: '对方反问你为什么来印尼。',
          options: [
            pair('Aku kerja di sini, sambil belajar budaya Indonesia.', '我在这里工作，也顺便学习印尼文化。'),
            pair('Aku sering bolak-balik untuk urusan kerja.', '我经常因为工作往返。'),
          ],
        },
      ],
      localUsage: pair('Kenal dari mana? 比直接问很多私人问题更自然，适合第一次见面破冰。', '先聊关系来源，再慢慢进入个人话题。'),
      easyMistake: pair('不要一上来连续问年龄、工资、婚姻，会像查户口。', '第一次见面先轻松。'),
      trySay: pair('Kamu kenal teman-teman di sini dari mana?', '你是怎么认识这里这些朋友的？'),
    },
  },
  'EXP-LIF-175': {
    category: 'friends',
    task: '找到共同话题，让关系继续',
    indonesian: 'Oh, kamu suka film juga? Biasanya nonton film apa?',
    explanation: '刚认识的人不一定对第一个话题有兴趣。你要会自然换话题，找到共同点，再继续交流。',
    harvest: ['topik yang sama', 'suka apa', 'biasanya nonton', 'aku juga'],
    goldenScene: {
      situation: '你和刚认识的印尼朋友聊天，第一个话题反应一般，需要自然换到双方都有兴趣的话题。',
      goal: '找到一个共同话题，让聊天从客套变成真正交流。',
      dialogue: [
        line('我', 'Kamu sering jalan-jalan ke luar kota?', '你经常去外地玩吗？'),
        line('朋友', 'Jarang sih, akhir-akhir ini sibuk.', '很少，最近挺忙。'),
        line('我', 'Oh begitu. Kalau weekend biasanya ngapain?', '这样啊。那周末一般做什么？'),
        line('朋友', 'Kadang nonton film atau futsal sama teman.', '有时候看电影，或者和朋友踢五人足球。'),
        line('我', 'Oh, kamu suka film juga? Biasanya nonton film apa?', '哦，你也喜欢电影？一般看什么电影？'),
        line('朋友', 'Aku suka film thriller. Kamu?', '我喜欢惊悚片。你呢？'),
        line('我', 'Aku juga suka, tapi kadang belum paham bahasa Indonesianya semua.', '我也喜欢，不过有时候印尼语还不能全听懂。'),
        line('朋友', 'Nanti aku rekomendasi film yang gampang diikuti.', '那我以后推荐你容易跟上的电影。'),
      ],
      replies: [
        pair('Aku kurang suka jalan-jalan.', '我不太喜欢旅行。'),
        pair('Aku lebih sering nonton film.', '我更常看电影。'),
        pair('Kalau kamu suka apa?', '那你喜欢什么？'),
      ],
      variations: [
        pair('Kalau makanan, kamu suka apa?', '如果说吃的，你喜欢什么？'),
        pair('Aku belum terlalu paham sepak bola Indonesia.', '我还不太了解印尼足球。'),
        pair('Film Indonesia yang bagus apa?', '有什么好的印尼电影？'),
        pair('Aku pernah coba makanan itu di Bandung.', '我在万隆试过那个食物。'),
      ],
      decisions: [
        {
          situation: '第一个话题明显聊不动。',
          options: [
            pair('Ganti topik pelan-pelan: kalau weekend biasanya ngapain?', '慢慢换话题：你周末一般做什么？'),
            pair('Share sedikit pengalaman sendiri, lalu tanya pendapat dia.', '先分享一点自己的经历，再问对方看法。'),
          ],
        },
      ],
      localUsage: pair('Biasanya ngapain? 很口语，比“你的爱好是什么”更自然。', '共同话题不是审问出来的，是顺着反应找出来的。'),
      easyMistake: pair('不要对方没兴趣还硬聊同一个话题。印尼聊天很重视轻松感。', '会换话题也是能力。'),
      trySay: pair('Kalau weekend biasanya kamu ngapain?', '周末你一般做什么？'),
    },
  },
  'EXP-LIF-176': {
    category: 'friends',
    task: '从 Pak/Bu 慢慢聊到 Kak/Bro',
    indonesian: 'Kalau boleh, saya panggil Kak Rina saja ya?',
    explanation: '关系变熟以后，称呼可以从 Pak/Bu 变轻松，但要观察年龄、场合和对方反应，不能乱用 Bro。',
    harvest: ['panggil Kak', 'lebih santai', 'tetap sopan', 'jangan terlalu akrab'],
    goldenScene: {
      situation: '你和一个印尼朋友见过几次，想让称呼更自然，但不想显得太随便。',
      goal: '理解正式、半熟、朋友式称呼之间的距离。',
      dialogue: [
        line('我', 'Bu Rina, terima kasih sudah bantu kemarin.', 'Rina 女士，谢谢你昨天帮忙。'),
        line('朋友', 'Santai saja. Panggil Rina juga boleh kok.', '没事。叫我 Rina 也可以。'),
        line('我', 'Kalau boleh, saya panggil Kak Rina saja ya?', '如果可以，我叫你 Kak Rina 好吗？'),
        line('朋友', 'Boleh, lebih santai.', '可以，更轻松。'),
        line('我', 'Kalau di kantor tetap Bu Rina, ya?', '如果在办公室还是叫 Bu Rina，对吧？'),
        line('朋友', 'Iya, kalau formal lebih aman begitu.', '对，正式场合那样更稳妥。'),
        line('我', 'Kalau teman dekat baru bisa panggil nama saja?', '很熟的朋友才直接叫名字吗？'),
        line('朋友', 'Iya. Bro juga bisa, tapi lihat orangnya dulu.', '对。Bro 也可以，但要先看人。'),
      ],
      replies: [
        pair('Panggil Kak saja biar santai.', '叫 Kak 就好，更轻松。'),
        pair('Kalau formal, tetap pakai Bu.', '正式场合还是用 Bu。'),
        pair('Jangan langsung panggil Bro kalau belum dekat.', '还不熟不要直接叫 Bro。'),
      ],
      variations: [
        pair('Saya panggil Mas boleh?', '我叫你 Mas 可以吗？'),
        pair('Kalau di chat boleh lebih santai?', '聊天里可以更轻松一点吗？'),
        pair('Kalau meeting, saya tetap panggil Pak.', '开会时我还是叫 Pak。'),
        pair('Aku panggil nama saja ya?', '我直接叫名字可以吗？'),
      ],
      decisions: [
        {
          situation: '对方比你年长，但聊天很轻松。',
          options: [
            pair('Pakai Kak atau Mas/Mbak dulu.', '先用 Kak 或 Mas/Mbak。'),
            pair('Tanya langsung: saya panggil apa enaknya?', '直接问：我怎么称呼比较合适？'),
          ],
        },
      ],
      localUsage: pair('Saya panggil apa enaknya? 是很自然的称呼确认句。', '称呼不是背规则，是读关系距离。'),
      easyMistake: pair('不要为了显得亲近，刚认识就叫 Bro。可能会让人觉得太随便。', '亲近也要有分寸。'),
      trySay: pair('Saya panggil Kak Rina saja ya?', '我叫你 Kak Rina 好吗？'),
    },
  },
  'EXP-LIF-177': {
    category: 'friends',
    task: '朋友说俚语/开玩笑，我没听懂',
    indonesian: 'Maaf, maksudnya apa ya? Aku belum nangkep.',
    explanation: '别人开玩笑或说俚语时，不要假装懂。自然问意思、确认、再接一句，就能让聊天继续。',
    harvest: ['maksudnya apa', 'belum nangkep', 'baru paham', 'ikut bercanda'],
    goldenScene: {
      situation: '一群朋友突然笑了，你没听懂刚才的俚语或玩笑，但不想让气氛冷掉。',
      goal: '听不懂也能自然问清楚，并成功接住玩笑。',
      dialogue: [
        line('朋友', 'Dia mah buaya darat, hati-hati!', '他可是“陆地鳄鱼”，小心哦！'),
        line('大家', 'Hahaha!', '哈哈哈！'),
        line('我', 'Maaf, maksudnya apa ya? Aku belum nangkep.', '不好意思，什么意思呀？我还没听懂。'),
        line('朋友', 'Buaya darat itu cowok yang suka gombal ke banyak cewek.', 'Buaya darat 是指喜欢到处撩女生的男生。'),
        line('我', 'Oh, baru paham. Jadi bukan buaya beneran ya.', '哦，我懂了。所以不是真的鳄鱼啊。'),
        line('朋友', 'Iya, bukan yang di sungai.', '对，不是河里的那种。'),
        line('我', 'Kalau begitu aku harus hati-hati belajar kata baru ini.', '那我得小心学习这个新词。'),
        line('朋友', 'Nah, sudah bisa bercanda!', '看，已经会接玩笑了！'),
      ],
      replies: [
        pair('Itu cuma bercanda kok.', '那只是开玩笑啦。'),
        pair('Maksudnya orang yang suka gombal.', '意思是喜欢花言巧语的人。'),
        pair('Nggak apa-apa, nanti lama-lama paham.', '没事，慢慢就懂了。'),
      ],
      variations: [
        pair('Aku belum paham slang itu.', '我还不懂那个俚语。'),
        pair('Boleh jelasin pelan-pelan?', '可以慢慢解释一下吗？'),
        pair('Oh, jadi itu bahasa gaul ya?', '哦，所以那是俚语对吧？'),
        pair('Aku catat dulu kata ini.', '我先记下这个词。'),
      ],
      decisions: [
        {
          situation: '你没听懂，但大家都在笑。',
          options: [
            pair('Tanya dengan santai: maksudnya apa ya?', '轻松问：什么意思呀？'),
            pair('Jangan pura-pura paham. Minta contoh.', '不要假装懂，请对方举例。'),
          ],
        },
      ],
      localUsage: pair('Belum nangkep 是很自然的“我还没抓到意思”。', '听不懂不可怕，假装懂才尴尬。'),
      easyMistake: pair('不要说 “saya tidak mengerti bahasa kalian” 太重，会让气氛变硬。', '用轻松语气问。'),
      trySay: pair('Maksudnya apa ya? Aku belum nangkep.', '什么意思呀？我还没听懂。'),
    },
  },
  'EXP-LIF-178': {
    category: 'friends',
    task: '交换 WhatsApp，第一次主动联系',
    indonesian: 'Boleh tukar WhatsApp? Nanti aku kabari soal tempat makan tadi.',
    explanation: '第一次见面聊得不错，交换 WhatsApp 后第一次联系要提醒自己是谁，并延续刚才的话题，不要过度热情。',
    harvest: ['tukar WhatsApp', 'aku yang tadi', 'kabari nanti', 'nggak buru-buru'],
    goldenScene: {
      situation: '你和新朋友聊天不错，想交换 WhatsApp，并在分开后发第一条自然消息。',
      goal: '成功交换联系方式，并发出不过度热情的第一次消息。',
      dialogue: [
        line('我', 'Boleh tukar WhatsApp?', '可以交换 WhatsApp 吗？'),
        line('朋友', 'Boleh, ini nomorku.', '可以，这是我的号码。'),
        line('我', 'Nanti aku kabari soal tempat makan tadi ya.', '等下我把刚才说的餐厅发你。'),
        line('朋友', 'Oke, aku tunggu.', '好，我等你。'),
        line('我', 'Hai, ini Li yang tadi ketemu di acara Rina.', '嗨，我是刚才在 Rina 聚会上见到的 Li。'),
        line('朋友', 'Oh iya, Li. Halo!', '哦对，Li。你好！'),
        line('我', 'Ini tempat makan yang aku cerita tadi. Kalau kapan-kapan sempat, boleh coba.', '这是我刚才说的餐厅。以后有空可以试试。'),
        line('朋友', 'Makasih! Kelihatannya enak.', '谢谢！看起来不错。'),
      ],
      replies: [
        pair('Ini nomorku, save aja.', '这是我的号码，存一下吧。'),
        pair('Oh iya, aku ingat.', '哦对，我记得。'),
        pair('Nanti kalau ada waktu kita coba.', '以后有时间我们去试试。'),
      ],
      variations: [
        pair('Aku save nomormu ya.', '我存一下你的号码。'),
        pair('Ini aku, Li, yang ngobrol soal film tadi.', '我是 Li，刚才聊电影的那个。'),
        pair('Nggak perlu balas cepat kok.', '不用马上回。'),
        pair('Nanti kalau sempat kita lanjut ngobrol.', '以后有空我们继续聊。'),
      ],
      decisions: [
        {
          situation: '对方回复得很慢。',
          options: [
            pair('Jangan kirim pesan bertubi-tubi.', '不要连续轰炸消息。'),
            pair('Cukup tinggalkan satu pesan yang jelas dan santai.', '留一条清楚轻松的消息就够了。'),
          ],
        },
      ],
      localUsage: pair('Aku yang tadi... 是第一次联系时很自然的自我提醒。', '让对方记起你，不要逼近关系。'),
      easyMistake: pair('不要刚加 WhatsApp 就发很多私人问题或连续邀请。', '第一次联系要轻。'),
      trySay: pair('Hai, ini Li yang tadi ketemu di acara Rina.', '嗨，我是刚才在 Rina 聚会上见到的 Li。'),
    },
  },
  'EXP-LIF-179': {
    category: 'friends',
    task: '约朋友喝咖啡 / 吃饭',
    indonesian: 'Kalau kamu sempat, minggu ini mau ngopi atau makan bareng?',
    explanation: '约朋友时，要把模糊的 nanti 变成具体时间和地点，同时保留轻松空间。',
    harvest: ['kalau sempat', 'ngopi bareng', 'hari apa', 'jadi ya'],
    goldenScene: {
      situation: '你想约刚熟悉的朋友喝咖啡或吃饭，对方说 nanti，但还没真正定下来。',
      goal: '把模糊同意变成具体时间、地点和最终确认。',
      dialogue: [
        line('我', 'Kalau kamu sempat, minggu ini mau ngopi atau makan bareng?', '如果你有空，这周要不要一起喝咖啡或吃饭？'),
        line('朋友', 'Boleh, nanti ya.', '可以，之后吧。'),
        line('我', 'Nanti itu kira-kira hari apa?', '“之后”大概是哪天？'),
        line('朋友', 'Hmm, belum tahu. Mungkin Jumat.', '嗯，还不知道。可能周五。'),
        line('我', 'Jumat sore atau Sabtu siang kamu lebih enak?', '周五下午还是周六中午你更方便？'),
        line('朋友', 'Sabtu siang lebih aman.', '周六中午更稳。'),
        line('我', 'Oke, kita coba kafe dekat MRT ya?', '好，我们去 MRT 附近那家咖啡馆？'),
        line('朋友', 'Oke, jadi Sabtu jam satu.', '好，定周六一点。'),
      ],
      replies: [
        pair('Nanti kita lihat jadwal dulu.', '之后先看时间。'),
        pair('Sabtu siang lebih enak.', '周六中午更方便。'),
        pair('Jadi ya, jam satu.', '就定一点。'),
      ],
      variations: [
        pair('Kalau minggu ini penuh, minggu depan juga boleh.', '如果这周满了，下周也可以。'),
        pair('Aku kasih dua pilihan waktu ya.', '我给两个时间选项。'),
        pair('Tempatnya kamu pilih juga boleh.', '地点你选也可以。'),
        pair('Kalau ada perubahan, kabari aku ya.', '如果有变化，告诉我。'),
      ],
      decisions: [
        {
          situation: '对方只说 nanti，不给具体时间。',
          options: [
            pair('Kasih dua pilihan waktu konkret.', '给两个具体时间。'),
            pair('Kalau belum pasti, bilang kita tentukan lagi besok.', '如果还不确定，就说明天再定。'),
          ],
        },
      ],
      localUsage: pair('Jadi ya? 是确认“真的定了没”的自然口语。', '模糊同意不等于约好。'),
      easyMistake: pair('不要把 nanti 理解成确定答应。它常常只是礼貌地留空间。', '约人要落到时间地点。'),
      trySay: pair('Jumat sore atau Sabtu siang kamu lebih enak?', '周五下午还是周六中午你更方便？'),
    },
  },
  'EXP-LIF-180': {
    category: 'friends',
    task: '第一次参加一群印尼朋友的聚会',
    indonesian: 'Boleh aku ikut ngobrol? Tadi kalian bahas tempat makan ya?',
    explanation: '只认识一个人的聚会里，先被介绍、听别人聊，再找一个简单话题加入，不要硬插。',
    harvest: ['ikut ngobrol', 'kenalin dulu', 'bahas apa', 'pamit dulu'],
    goldenScene: {
      situation: '你第一次参加一群印尼朋友的聚会，只认识其中一个人，需要从旁观者进入群体。',
      goal: '自然认识几个人、接上话题，并在离开前体面告别。',
      dialogue: [
        line('朋友', 'Teman-teman, ini Li dari China.', '朋友们，这是来自中国的 Li。'),
        line('我', 'Hai semua, senang kenal kalian.', '大家好，很高兴认识你们。'),
        line('新朋友', 'Kamu sudah lama di Indonesia?', '你在印尼很久了吗？'),
        line('我', 'Belum terlalu lama. Aku masih banyak belajar.', '还不算久。我还在学很多东西。'),
        line('大家', 'Kami tadi bahas tempat makan baru.', '我们刚才在聊新开的餐厅。'),
        line('我', 'Boleh aku ikut ngobrol? Tadi kalian bahas tempat makan ya?', '我可以一起聊吗？刚才你们在聊餐厅对吧？'),
        line('新朋友', 'Iya, kamu suka makanan pedas?', '对，你喜欢辣的吗？'),
        line('我', 'Suka, tapi level pedas Indonesia kadang terlalu kuat buat aku.', '喜欢，但印尼的辣度有时候对我太强了。'),
        line('我', 'Aku pamit dulu ya. Senang bisa kenal kalian.', '我先走啦。很高兴认识大家。'),
      ],
      replies: [
        pair('Ayo, ikut ngobrol saja.', '来，一起聊就好。'),
        pair('Kami lagi bahas makanan.', '我们正在聊吃的。'),
        pair('Nanti ikut lagi ya.', '下次再来哦。'),
      ],
      variations: [
        pair('Aku belum terlalu paham, boleh jelasin sedikit?', '我还不太懂，可以解释一点吗？'),
        pair('Aku pernah coba itu sekali.', '我试过一次那个。'),
        pair('Kalau di China, rasanya agak beda.', '在中国，味道有点不一样。'),
        pair('Aku pamit dulu, terima kasih sudah diajak.', '我先告辞，谢谢邀请我。'),
      ],
      decisions: [
        {
          situation: '大家聊得很快，你只听懂一半。',
          options: [
            pair('Ambil satu kata yang kamu paham lalu tanya.', '抓住一个听懂的词再问。'),
            pair('Jangan diam terus; masuk dengan topik sederhana.', '不要一直沉默，用简单话题加入。'),
          ],
        },
      ],
      localUsage: pair('Pamit dulu 是印尼离开聚会时很常用的礼貌表达。', '进入群体和离开群体都要自然。'),
      easyMistake: pair('不要一进场就只和唯一认识的人说话。要逐步认识旁边的人。', '从旁观者变参与者。'),
      trySay: pair('Boleh aku ikut ngobrol?', '我可以一起聊吗？'),
    },
  },
  'EXP-LIF-181': {
    category: 'friends',
    task: '朋友开始聊家庭和私人生活',
    indonesian: 'Kalau boleh tahu, keluarga kamu tinggal di sini juga?',
    explanation: '朋友聊到家庭时，可以亲近地回应，但不要追问太深；要知道哪些问题适合停住。',
    harvest: ['kalau boleh tahu', 'keluarga', 'jangan terlalu pribadi', 'semoga sehat'],
    goldenScene: {
      situation: '朋友开始聊父母、孩子、家乡和家庭生活。你想回应得亲近，但不冒犯。',
      goal: '在私人话题里保持温度和边界。',
      dialogue: [
        line('朋友', 'Aku weekend biasanya pulang ke rumah orang tua.', '我周末一般回父母家。'),
        line('我', 'Oh, keluarga kamu tinggal di Jakarta juga?', '哦，你家人也住雅加达吗？'),
        line('朋友', 'Iya, orang tuaku di Depok.', '对，我父母在 Depok。'),
        line('我', 'Kalau boleh tahu, kamu sering ketemu mereka?', '方便问的话，你经常见他们吗？'),
        line('朋友', 'Lumayan sering. Di Indonesia keluarga masih dekat.', '还算经常。在印尼家庭关系还是很近。'),
        line('我', 'Bagus ya. Di China juga banyak orang dekat dengan keluarga.', '挺好的。在中国也很多人和家人很亲。'),
        line('朋友', 'Kamu sudah menikah?', '你结婚了吗？'),
        line('我', 'Belum. Tapi pelan-pelan ya, topik ini berat juga.', '还没有。不过慢慢聊吧，这个话题也挺重的。'),
      ],
      replies: [
        pair('Keluargaku tinggal di luar kota.', '我家人住在外地。'),
        pair('Aku dekat dengan adik-adikku.', '我和弟弟妹妹关系很近。'),
        pair('Kalau terlalu pribadi, nggak usah jawab kok.', '如果太私人，不回答也没关系。'),
      ],
      variations: [
        pair('Semoga keluarga kamu sehat semua.', '希望你家人都健康。'),
        pair('Aku belum terlalu berani tanya terlalu dalam.', '我还不太敢问太深。'),
        pair('Kalau di keluarga kamu biasanya kumpul kapan?', '你们家一般什么时候聚？'),
        pair('Maaf kalau pertanyaannya terlalu pribadi.', '如果这个问题太私人，不好意思。'),
      ],
      decisions: [
        {
          situation: '朋友反问你的婚姻或家庭情况，你不想深入。',
          options: [
            pair('Jawab singkat lalu pindah topik dengan halus.', '简短回答，然后温和换话题。'),
            pair('Bilang topiknya agak pribadi tapi tetap ramah.', '说这个话题有点私人，但保持友好。'),
          ],
        },
      ],
      localUsage: pair('Kalau boleh tahu 是进入私人话题前的安全垫。', '亲近不等于追问到底。'),
      easyMistake: pair('不要连续问工资、婚姻、孩子计划，会让对方压力很大。', '私人话题要留空间。'),
      trySay: pair('Maaf kalau pertanyaannya terlalu pribadi.', '如果这个问题太私人，不好意思。'),
    },
  },
  'EXP-LIF-182': {
    category: 'friends',
    task: '朋友请我帮忙，但我不方便',
    indonesian: 'Maaf, kali ini aku belum bisa bantu. Tapi mungkin kamu bisa coba cara ini.',
    explanation: '拒绝朋友帮忙请求时，先听清楚，再温和说明不能帮；如果有替代方案就提供，但不要虚假承诺。',
    harvest: ['belum bisa bantu', 'aku paham', 'alternatif lain', 'semoga lancar'],
    goldenScene: {
      situation: '朋友请你帮忙处理一件事，但你今天确实不方便。你要拒绝，同时保住关系。',
      goal: '明确拒绝不方便的请求，并给出合理解释或替代办法。',
      dialogue: [
        line('朋友', 'Li, besok bisa bantu antar aku ke kantor imigrasi?', 'Li，明天可以帮我去移民局吗？'),
        line('我', 'Besok jam berapa dan kira-kira berapa lama?', '明天几点，大概多久？'),
        line('朋友', 'Pagi sampai siang mungkin.', '可能从早上到中午。'),
        line('我', 'Aku paham, tapi besok pagi aku ada meeting penting.', '我理解，但明早我有重要会议。'),
        line('朋友', 'Nggak bisa sebentar saja?', '短时间也不行吗？'),
        line('我', 'Maaf, kali ini aku belum bisa bantu.', '不好意思，这次我帮不了。'),
        line('我', 'Tapi aku bisa kirim kontak teman yang pernah urus itu.', '但我可以发你一个办过这件事的朋友联系方式。'),
        line('朋友', 'Oke, itu juga membantu. Makasih ya.', '好，那也有帮助。谢谢。'),
      ],
      replies: [
        pair('Aku paham kamu butuh bantuan.', '我理解你需要帮忙。'),
        pair('Kali ini aku benar-benar belum bisa.', '这次我真的不太方便。'),
        pair('Aku coba kasih alternatif lain.', '我试着给你别的办法。'),
      ],
      variations: [
        pair('Maaf, aku belum bisa janji.', '不好意思，我不能先答应。'),
        pair('Aku takut malah bikin kamu menunggu.', '我怕反而让你等。'),
        pair('Kalau hanya tanya info, aku bisa bantu.', '如果只是问信息，我可以帮。'),
        pair('Semoga urusannya lancar ya.', '希望事情顺利。'),
      ],
      decisions: [
        {
          situation: '对方继续要求你帮忙。',
          options: [
            pair('Tetap jelas: aku belum bisa bantu langsung.', '仍然明确：我不能直接帮。'),
            pair('Tawarkan bantuan kecil yang realistis.', '提供一个现实可做到的小帮助。'),
          ],
        },
      ],
      localUsage: pair('Belum bisa bantu 比直接 bilang tidak 更柔和，但仍然清楚。', '拒绝可以温和，但不能虚假承诺。'),
      easyMistake: pair('不要说 nanti aku coba kalau其实完全不可能。会让关系以后更尴尬。', '不要用假希望代替拒绝。'),
      trySay: pair('Maaf, kali ini aku belum bisa bantu.', '不好意思，这次我帮不了。'),
    },
  },
  'EXP-LIF-183': {
    category: 'friends',
    task: '我需要朋友帮忙，怎么自然开口',
    indonesian: 'Kalau kamu sempat, aku mau minta bantuan kecil. Tapi kalau repot, nggak apa-apa.',
    explanation: '求人时先问对方是否方便，再提出具体请求，并给对方拒绝空间；这样更容易维持关系。',
    harvest: ['kalau sempat', 'minta bantuan kecil', 'kalau repot', 'makasih banyak'],
    goldenScene: {
      situation: '你需要朋友帮忙翻译一段印尼语消息，但不想让对方有压力。',
      goal: '自然开口求助，同时给对方可以拒绝的台阶。',
      dialogue: [
        line('我', 'Kamu lagi sibuk nggak?', '你现在忙吗？'),
        line('朋友', 'Lumayan, tapi kenapa?', '有点忙，怎么了？'),
        line('我', 'Kalau kamu sempat, aku mau minta bantuan kecil.', '如果你有空，我想请你帮个小忙。'),
        line('朋友', 'Bantuan apa?', '什么忙？'),
        line('我', 'Aku perlu cek satu pesan bahasa Indonesia. Takut salah paham.', '我需要确认一条印尼语消息，怕理解错。'),
        line('我', 'Tapi kalau repot, nggak apa-apa. Aku bisa tunggu.', '但如果不方便也没关系，我可以等。'),
        line('朋友', 'Kirim saja. Nanti aku lihat setelah selesai kerja.', '发来吧。我下班后看。'),
        line('我', 'Makasih banyak. Nggak buru-buru kok.', '太谢谢了。不着急。'),
      ],
      replies: [
        pair('Aku bisa bantu, tapi nanti malam ya.', '我可以帮，但要晚上。'),
        pair('Maaf, hari ini agak penuh.', '抱歉，今天有点满。'),
        pair('Kirim dulu, nanti aku cek.', '先发来，我等下看。'),
      ],
      variations: [
        pair('Kalau tidak sempat, benar-benar nggak apa-apa.', '如果没空真的没关系。'),
        pair('Aku cuma perlu cek arti umumnya.', '我只是需要确认大概意思。'),
        pair('Boleh bantu lihat sebentar?', '可以帮我看一下吗？'),
        pair('Terima kasih, kamu sudah banyak bantu.', '谢谢，你已经帮了很多。'),
      ],
      decisions: [
        {
          situation: '朋友说不确定有没有时间。',
          options: [
            pair('Jangan tekan. Bilang bisa tunggu.', '不要施压，说可以等。'),
            pair('Cari bantuan lain sambil tetap berterima kasih.', '找别的帮助，同时仍然表示感谢。'),
          ],
        },
      ],
      localUsage: pair('Kalau repot, nggak apa-apa 是给对方台阶的关键句。', '会求人，也要会让别人轻松拒绝。'),
      easyMistake: pair('不要一开口就 “tolong sekarang ya”。朋友不是员工。', '请求要给空间。'),
      trySay: pair('Kalau kamu sempat, aku mau minta bantuan kecil.', '如果你有空，我想请你帮个小忙。'),
    },
  },
  'EXP-LIF-184': {
    category: 'business',
    task: '第一次见潜在客户，不要一上来就卖东西',
    indonesian: 'Saya ingin dengar dulu kebutuhan Bapak, supaya saya tidak langsung menawarkan hal yang tidak cocok.',
    explanation: '第一次见客户先寒暄、听对方业务和需求，再自然介绍自己能做什么，不强行成交。',
    harvest: ['dengar kebutuhan', 'tidak langsung menawarkan', 'cocok atau tidak', 'lanjut diskusi'],
    goldenScene: {
      situation: '你第一次见一个潜在客户，对方还不了解你。你不能一上来就推销。',
      goal: '先建立关系，听出一个真实需求，再约下一步继续聊。',
      dialogue: [
        line('我', 'Terima kasih sudah meluangkan waktu, Pak.', '谢谢您抽时间见我。'),
        line('客户', 'Sama-sama. Silakan, mau bahas apa?', '不客气。请说，想聊什么？'),
        line('我', 'Sebelum saya cerita produk, boleh saya tahu bisnis Bapak sekarang fokus di mana?', '在我介绍产品前，可以先了解您现在业务重点在哪里吗？'),
        line('客户', 'Kami sedang cari cara supaya pengiriman lebih cepat.', '我们正在找让发货更快的方法。'),
        line('我', 'Saya ingin dengar dulu kebutuhan Bapak, supaya saya tidak langsung menawarkan hal yang tidak cocok.', '我想先听您的需求，避免直接推荐不合适的东西。'),
        line('客户', 'Oke, masalah kami biasanya di gudang.', '好，我们的问题通常在仓库。'),
        line('我', 'Kalau begitu mungkin solusi kami relevan untuk proses gudang, bukan semua bagian.', '那我们的方案可能更适合仓库流程，不是所有部分。'),
        line('客户', 'Menarik. Nanti kita lihat detailnya.', '有意思。之后我们看细节。'),
      ],
      replies: [
        pair('Masalah utama kami di operasional.', '我们的主要问题在运营。'),
        pair('Saya belum mau beli dulu, tapi boleh dengar.', '我还不想买，但可以听听。'),
        pair('Kita jadwalkan meeting teknis minggu depan.', '我们下周安排技术会议。'),
      ],
      variations: [
        pair('Boleh saya tanya proses Bapak sekarang?', '可以问一下您现在的流程吗？'),
        pair('Saya tidak ingin langsung hard selling.', '我不想一上来硬推销。'),
        pair('Kalau tidak cocok, tidak perlu dipaksakan.', '如果不合适，不用勉强。'),
        pair('Minggu depan kita bisa bahas lebih detail.', '下周我们可以更详细聊。'),
      ],
      decisions: [
        {
          situation: '客户问你是不是马上要报价。',
          options: [
            pair('Belum, Pak. Saya pahami kebutuhan dulu.', '还不是，先生。我先了解需求。'),
            pair('Kalau sudah jelas, baru saya kirim opsi yang relevan.', '清楚以后我再发相关选项。'),
          ],
        },
      ],
      localUsage: pair('Tidak langsung menawarkan 很适合表达“不急着卖”。', '商务社交先关系，后方案。'),
      easyMistake: pair('不要第一分钟就讲十分钟公司介绍。客户更关心自己的问题。', '先听，再说。'),
      trySay: pair('Boleh saya tahu kebutuhan Bapak sekarang?', '可以了解您现在的需求吗？'),
    },
  },
  'EXP-LIF-185': {
    category: 'business',
    task: '和客户吃饭，什么时候开始聊生意',
    indonesian: 'Nanti kalau Bapak nyaman, kita bahas satu poin bisnis saja, tidak perlu seperti meeting.',
    explanation: '商务饭局不是会议。先聊城市、食物、近况，等对方自然进入工作，再只讨论一个重点。',
    harvest: ['bahas santai', 'satu poin bisnis', 'tidak seperti meeting', 'langkah berikutnya'],
    goldenScene: {
      situation: '你和客户一起吃饭，想聊业务，但不想让整顿饭变成会议。',
      goal: '在合适时机自然进入业务，并约好下一步。',
      dialogue: [
        line('客户', 'Restoran ini biasanya ramai, makanannya lumayan enak.', '这家餐厅一般很热闹，菜还不错。'),
        line('我', 'Iya, saya baru pertama kali ke sini. Menu apa yang paling aman?', '是的，我第一次来。哪个菜比较稳？'),
        line('客户', 'Coba ikan bakar. Ngomong-ngomong, soal proyek kemarin bagaimana?', '试试烤鱼。顺便问下，昨天那个项目怎么样？'),
        line('我', 'Sudah kami cek. Nanti kalau Bapak nyaman, kita bahas satu poin bisnis saja.', '我们已经看过了。等您方便，我们只聊一个业务重点。'),
        line('客户', 'Boleh, tapi jangan terlalu berat ya.', '可以，但别太沉重。'),
        line('我', 'Setuju. Poin utamanya hanya timeline pengiriman.', '同意。重点只是交货时间。'),
        line('客户', 'Kalau timeline jelas, kami bisa lanjut.', '如果时间清楚，我们可以继续。'),
        line('我', 'Besok saya kirim ringkasan, lalu kita meeting singkat minggu depan.', '明天我发总结，然后下周短会。'),
      ],
      replies: [
        pair('Kita makan dulu, nanti baru bahas sedikit.', '先吃饭，之后再简单聊一点。'),
        pair('Saya mau bahas satu poin saja.', '我只想聊一个重点。'),
        pair('Besok saya kirim ringkasan.', '明天我发总结。'),
      ],
      variations: [
        pair('Jangan sampai makan malam ini jadi meeting panjang.', '别让今晚吃饭变成长会议。'),
        pair('Kalau Bapak mau, kita bahas setelah makan.', '如果您愿意，我们饭后聊。'),
        pair('Saya catat dulu, detailnya besok saja.', '我先记下，细节明天再说。'),
        pair('Next step-nya kita jadwalkan terpisah.', '下一步我们另外安排。'),
      ],
      decisions: [
        {
          situation: '客户开始聊业务，但饭刚上来。',
          options: [
            pair('Bahas singkat satu poin, detailnya follow-up.', '简短聊一个点，细节后续跟进。'),
            pair('Ikuti ritme pelanggan, jangan dominasi meja makan.', '跟客户节奏，不要主导整个饭局。'),
          ],
        },
      ],
      localUsage: pair('Tidak perlu seperti meeting 是轻松表达“别太正式”。', '商务饭局的重点是关系和节奏。'),
      easyMistake: pair('不要边吃饭边打开一堆 PPT。容易把轻松关系变压力。', '饭局不是会议室。'),
      trySay: pair('Kita bahas satu poin bisnis saja, tidak perlu seperti meeting.', '我们只聊一个业务点，不用像开会。'),
    },
  },
  'EXP-LIF-186': {
    category: 'business',
    task: '客户说“我考虑一下”，到底是什么意思',
    indonesian: 'Boleh saya tahu, pertimbangan utamanya di harga, waktu, atau approval internal?',
    explanation: '客户说 Saya pikir-pikir dulu 时，不要逼单。要温和确认顾虑来源，并拿到下一次联系时间。',
    harvest: ['pikir-pikir dulu', 'pertimbangan utama', 'approval internal', 'follow up lagi'],
    goldenScene: {
      situation: '客户听完方案后说要考虑一下。你需要判断是真考虑、还在比较，还是礼貌拒绝。',
      goal: '确认主要顾虑，并获得一个清楚的下一步联系时间。',
      dialogue: [
        line('客户', 'Saya pikir-pikir dulu ya.', '我先考虑一下。'),
        line('我', 'Baik, Pak. Saya paham.', '好的，先生。我理解。'),
        line('我', 'Boleh saya tahu, pertimbangan utamanya di harga, waktu, atau approval internal?', '可以了解一下，主要顾虑是价格、时间，还是内部批准？'),
        line('客户', 'Lebih ke approval bos saya.', '更偏向我老板批准。'),
        line('我', 'Berarti Bapak perlu bahan ringkas untuk jelaskan ke beliau?', '那您需要一份简短材料给他说明吗？'),
        line('客户', 'Iya, kalau ada summary lebih enak.', '对，如果有总结会更方便。'),
        line('我', 'Saya kirim summary hari ini. Kapan nyaman saya follow up lagi?', '我今天发总结。什么时候我再跟进比较方便？'),
        line('客户', 'Coba Jumat sore.', '周五下午试试。'),
      ],
      replies: [
        pair('Saya masih bandingkan dengan vendor lain.', '我还在和其他供应商比较。'),
        pair('Harganya masih jadi pertimbangan.', '价格还是一个考虑点。'),
        pair('Saya perlu bicara dengan bos dulu.', '我需要先和老板说。'),
      ],
      variations: [
        pair('Kalau belum cocok, tidak apa-apa Pak.', '如果还不合适也没关系。'),
        pair('Apa yang paling membuat Bapak ragu?', '最让您犹豫的是什么？'),
        pair('Saya tidak mau memaksa, hanya ingin follow up dengan tepat.', '我不想强迫，只想准确跟进。'),
        pair('Saya hubungi lagi Jumat sore ya.', '我周五下午再联系您。'),
      ],
      decisions: [
        {
          situation: '客户一直模糊说再看看。',
          options: [
            pair('Tanya faktor utama dengan pilihan konkret.', '用具体选项问主要因素。'),
            pair('Beri ruang keluar kalau memang belum berminat.', '如果确实没兴趣，给对方退出空间。'),
          ],
        },
      ],
      localUsage: pair('Pertimbangan utamanya di mana? 是温和挖顾虑的商务问法。', '不要逼问，问顾虑。'),
      easyMistake: pair('不要马上说 “jadi beli atau tidak?” 太压迫。', '模糊回应要拆解。'),
      trySay: pair('Pertimbangan utamanya di harga, waktu, atau approval internal?', '主要顾虑是价格、时间，还是内部批准？'),
    },
  },
  'EXP-LIF-187': {
    category: 'business',
    task: '客户很久没回复，怎么跟进又不让人烦',
    indonesian: 'Saya follow up pelan-pelan saja. Kalau belum jadi prioritas, tidak apa-apa.',
    explanation: '客户不回复时，第一次提醒，第二次换理由提供新信息，最后给对方退出空间，保留未来关系。',
    harvest: ['follow up', 'belum ada kabar', 'info tambahan', 'tidak apa-apa'],
    goldenScene: {
      situation: '你发了报价后客户一周没回复。你想跟进，但不想让人觉得烦。',
      goal: '完成两次有理由的跟进，并判断是否暂时放下。',
      dialogue: [
        line('我', 'Pak, saya follow up penawaran minggu lalu ya.', '先生，我跟进一下上周的报价。'),
        line('客户', 'Oh iya, belum sempat cek.', '哦对，还没来得及看。'),
        line('我', 'Baik, tidak apa-apa. Saya kirim juga ringkasan poin utamanya.', '好的，没关系。我也发一份重点总结。'),
        line('客户', 'Oke, kirim saja.', '好，发来吧。'),
        line('我', 'Pak, saya follow up lagi karena ada opsi harga baru untuk volume kecil.', '先生，我再跟进一下，因为小批量有新的价格选项。'),
        line('客户', 'Sekarang masih belum prioritas.', '现在还不是优先事项。'),
        line('我', 'Saya paham. Kalau belum jadi prioritas, tidak apa-apa.', '我理解。如果现在不是优先事项，没关系。'),
        line('我', 'Nanti kalau waktunya sudah pas, saya senang lanjut diskusi.', '以后时机合适了，我很愿意继续聊。'),
      ],
      replies: [
        pair('Belum sempat saya cek.', '我还没来得及看。'),
        pair('Sekarang belum prioritas.', '现在还不是优先事项。'),
        pair('Nanti saya kabari kalau sudah ada update.', '有更新我会告诉你。'),
      ],
      variations: [
        pair('Saya tambahkan info baru supaya lebih mudah dibandingkan.', '我补充新信息，方便您比较。'),
        pair('Kalau tidak relevan sekarang, saya tidak akan push.', '如果现在不相关，我不会硬推。'),
        pair('Boleh saya kontak lagi bulan depan?', '我下个月再联系可以吗？'),
        pair('Terima kasih sudah kasih kabar.', '谢谢您告知情况。'),
      ],
      decisions: [
        {
          situation: '第二次跟进后客户仍然模糊。',
          options: [
            pair('Berhenti push dan minta izin kontak di waktu lain.', '停止推进，请求以后再联系。'),
            pair('Kirim info bernilai, bukan hanya tanya jadi atau tidak.', '发送有价值的信息，而不是只问成不成。'),
          ],
        },
      ],
      localUsage: pair('Belum jadi prioritas 是商务里体面表达“不急/不推进”。', '跟进要有理由，也要会停。'),
      easyMistake: pair('不要每天发 “ada update?” 容易让客户反感。', '跟进不是催命。'),
      trySay: pair('Kalau belum jadi prioritas, tidak apa-apa.', '如果现在还不是优先事项，没关系。'),
    },
  },
  'EXP-LIF-188': {
    category: 'business',
    task: '客户对我们不满意，先把关系稳住',
    indonesian: 'Saya dengarkan dulu keluhan Bapak sampai jelas, setelah itu kita cari solusi konkret.',
    explanation: '客户抱怨时先让他说完，确认具体问题，不急着辩解；承担该承担的部分，并给明确处理时间。',
    harvest: ['dengarkan keluhan', 'masalah konkretnya', 'kami bertanggung jawab', 'solusi konkret'],
    goldenScene: {
      situation: '客户对交付不满意，语气已经有点重。你要先稳住关系，再处理问题。',
      goal: '让客户感到被听见，并拿到一个明确的修复方案和时间。',
      dialogue: [
        line('客户', 'Saya kecewa. Hasilnya tidak sesuai janji.', '我很失望。结果和承诺不一致。'),
        line('我', 'Maaf Pak. Saya dengarkan dulu keluhan Bapak sampai jelas.', '抱歉，先生。我先把您的意见听清楚。'),
        line('客户', 'Delivery telat dua hari, dan report-nya tidak lengkap.', '交付晚了两天，而且报告不完整。'),
        line('我', 'Baik. Jadi ada dua masalah: delivery telat dan report belum lengkap.', '好的。所以两个问题：交付延迟和报告不完整。'),
        line('客户', 'Betul. Jangan cuma kasih alasan.', '对。不要只是给理由。'),
        line('我', 'Untuk report, itu bagian kami. Kami bertanggung jawab revisi hari ini.', '报告这部分是我们的责任。我们今天负责修正。'),
        line('客户', 'Delivery bagaimana?', '交付呢？'),
        line('我', 'Saya cek penyebabnya sekarang, lalu jam empat saya kasih solusi konkret.', '我现在查原因，四点给您具体方案。'),
      ],
      replies: [
        pair('Saya mau solusi, bukan alasan.', '我要解决方案，不是理由。'),
        pair('Report ini belum bisa saya pakai.', '这份报告我还不能用。'),
        pair('Kalau hari ini selesai, masih bisa kami terima.', '如果今天完成，我们还能接受。'),
      ],
      variations: [
        pair('Saya tidak akan debat dulu.', '我先不争辩。'),
        pair('Bagian ini memang perlu kami perbaiki.', '这部分确实需要我们改。'),
        pair('Saya kasih update jam empat.', '我四点给您更新。'),
        pair('Setelah selesai, saya konfirmasi ulang.', '处理完后我再确认。'),
      ],
      decisions: [
        {
          situation: '客户情绪很强，你知道内部也有原因。',
          options: [
            pair('Jangan langsung bela diri. Ringkas masalah dulu.', '不要马上辩解。先总结问题。'),
            pair('Akui bagian yang memang tanggung jawab kita.', '承认确实属于我们的责任部分。'),
          ],
        },
      ],
      localUsage: pair('Saya dengarkan dulu 是降温句，适合客户生气时使用。', '先稳关系，再讲方案。'),
      easyMistake: pair('不要第一句就解释内部原因。客户会觉得你在推责任。', '抱怨场景先听完。'),
      trySay: pair('Saya dengarkan dulu keluhan Bapak sampai jelas.', '我先把您的意见听清楚。'),
    },
  },
  'EXP-LIF-189': {
    category: 'business',
    task: '合作成功以后，怎么继续维护关系',
    indonesian: 'Terima kasih atas kerja samanya. Setelah proyek selesai, saya juga ingin dengar feedback dari Bapak.',
    explanation: '成交不是关系结束。项目结束后感谢、问反馈、适度联系、分享有价值信息，让下一次合作自然出现。',
    harvest: ['kerja sama selesai', 'minta feedback', 'tetap kontak', 'bukan selalu jualan'],
    goldenScene: {
      situation: '一个订单顺利结束。你想维护客户关系，而不是只在要卖东西时联系。',
      goal: '完成感谢、反馈和下一次自然联系的关系维护闭环。',
      dialogue: [
        line('我', 'Terima kasih atas kerja samanya, Pak.', '谢谢这次合作，先生。'),
        line('客户', 'Sama-sama. Secara umum hasilnya baik.', '不客气。整体结果不错。'),
        line('我', 'Setelah proyek selesai, saya juga ingin dengar feedback dari Bapak.', '项目结束后，我也想听听您的反馈。'),
        line('客户', 'Respons tim cepat, tapi dokumentasi bisa lebih rapi.', '团队响应快，但文档可以更整齐。'),
        line('我', 'Baik, itu kami catat untuk perbaikan berikutnya.', '好的，我们记录下来，下次改进。'),
        line('客户', 'Oke.', '好的。'),
        line('我', 'Nanti kalau ada info yang relevan untuk bisnis Bapak, saya share. Tidak selalu soal jualan.', '以后如果有对您业务有用的信息，我会分享。不一定每次都是卖东西。'),
        line('客户', 'Bagus, saya senang kalau ada insight seperti itu.', '很好，我喜欢这种有价值的信息。'),
      ],
      replies: [
        pair('Kami puas, tapi masih ada catatan kecil.', '我们满意，但还有小建议。'),
        pair('Nanti kalau ada kebutuhan baru, saya kabari.', '之后有新需求我告诉你。'),
        pair('Info market seperti itu berguna buat kami.', '这种市场信息对我们有用。'),
      ],
      variations: [
        pair('Apa yang bisa kami perbaiki untuk kerja sama berikutnya?', '下次合作我们可以改进什么？'),
        pair('Saya tidak ingin kontak hanya saat ada penawaran.', '我不想只在有报价时联系。'),
        pair('Selamat hari raya, semoga bisnisnya lancar.', '节日快乐，祝业务顺利。'),
        pair('Saya share laporan singkat yang mungkin berguna.', '我分享一份可能有用的简短报告。'),
      ],
      decisions: [
        {
          situation: '合作结束后你想马上推下一单。',
          options: [
            pair('Tahan dulu. Minta feedback dan rawat hubungan.', '先别急。问反馈，维护关系。'),
            pair('Kalau ada kebutuhan nyata, baru masuk ke peluang baru.', '有真实需求时，再进入新机会。'),
          ],
        },
      ],
      localUsage: pair('Tidak selalu soal jualan 很适合表达“联系不是每次都销售”。', '成交后关系才刚开始。'),
      easyMistake: pair('不要项目刚结束就马上追下一单，容易显得功利。', '长期合作靠信任。'),
      trySay: pair('Saya juga ingin dengar feedback dari Bapak.', '我也想听听您的反馈。'),
    },
  },
  'EXP-LIF-190': {
    category: 'basics',
    task: '去银行办事，结果资料不齐',
    indonesian: 'Maaf, dokumen yang kurang yang mana? Asli atau fotokopi?',
    explanation: '银行资料不齐时，问清缺哪个、原件还是复印件、去哪拿、今天还能否继续、下次要带什么。',
    harvest: ['dokumen kurang', 'asli atau fotokopi', 'bisa lanjut hari ini', 'proses berikutnya'],
    goldenScene: {
      situation: '你去银行办业务，工作人员说资料不齐。你需要问清楚，不要白跑下一次。',
      goal: '确认缺少资料和下一步流程，不规避规定。',
      dialogue: [
        line('我', 'Saya mau urus pembukaan rekening.', '我想办理开户。'),
        line('工作人员', 'Maaf, dokumennya belum lengkap.', '抱歉，资料还不完整。'),
        line('我', 'Dokumen yang kurang yang mana?', '缺的是哪一份资料？'),
        line('工作人员', 'Surat domisili dan fotokopi paspor.', '住址证明和护照复印件。'),
        line('我', 'Perlu yang asli atau fotokopi saja?', '需要原件还是复印件就可以？'),
        line('工作人员', 'Suratnya asli, paspor cukup fotokopi.', '证明要原件，护照复印件即可。'),
        line('我', 'Kalau saya ambil sekarang, hari ini masih bisa lanjut?', '如果我现在去拿，今天还能继续吗？'),
        line('工作人员', 'Bisa, asal kembali sebelum jam tiga.', '可以，只要三点前回来。'),
      ],
      replies: [
        pair('Dokumen ini harus asli.', '这份文件必须是原件。'),
        pair('Fotokopi bisa di sebelah bank.', '复印可以在银行旁边。'),
        pair('Hari ini masih bisa lanjut kalau lengkap.', '今天资料齐了还能继续。'),
      ],
      variations: [
        pair('Saya perlu bawa apa lagi lain kali?', '下次还需要带什么？'),
        pair('Ada formulir yang bisa saya isi dulu?', '有表格我可以先填吗？'),
        pair('Proses berikutnya apa setelah dokumen lengkap?', '资料齐后下一步是什么？'),
        pair('Boleh saya foto daftar dokumennya?', '我可以拍一下资料清单吗？'),
      ],
      decisions: [
        {
          situation: '工作人员说缺资料，但说得很快。',
          options: [
            pair('Minta disebutkan satu per satu.', '请对方逐项说。'),
            pair('Minta daftar tertulis kalau ada.', '如果有，要求书面清单。'),
          ],
        },
      ],
      localUsage: pair('Yang kurang yang mana? 是办事窗口非常实用的追问。', '窗口沟通要拿到具体清单。'),
      easyMistake: pair('不要问“能不能不要这个资料”。应该问清流程和替代材料是否被允许。', '不规避规定。'),
      trySay: pair('Dokumen yang kurang yang mana?', '缺的是哪一份资料？'),
    },
  },
  'EXP-LIF-191': {
    category: 'basics',
    task: '找物业/管理处解决问题',
    indonesian: 'Masalah ini sudah dari pagi. Kapan teknisi bisa datang?',
    explanation: '找物业处理漏水、空调、门禁、电梯等问题时，把 nanti 变成具体时间、人员和跟进安排。',
    harvest: ['lapor masalah', 'sudah dari pagi', 'kapan teknisi datang', 'follow up lagi'],
    goldenScene: {
      situation: '公寓空调坏了，你已经报告过一次，对方只说 nanti。你需要拿到具体安排。',
      goal: '确认谁来、什么时候来、没来如何跟进，直到问题解决。',
      dialogue: [
        line('我', 'Saya mau lapor, AC kamar saya tidak dingin.', '我要报修，我房间空调不冷。'),
        line('管理处', 'Baik Pak, nanti kami cek.', '好的先生，之后我们检查。'),
        line('我', 'Masalah ini sudah dari pagi. Kapan teknisi bisa datang?', '这个问题从早上就有了。维修人员什么时候能来？'),
        line('管理处', 'Mungkin sore.', '可能下午。'),
        line('我', 'Sore jam berapa kira-kira? Saya perlu tunggu di kamar.', '下午大概几点？我需要在房间等。'),
        line('管理处', 'Sekitar jam tiga.', '大概三点。'),
        line('我', 'Kalau jam tiga belum datang, saya follow up ke siapa?', '如果三点还没来，我跟进谁？'),
        line('管理处', 'Hubungi nomor resepsionis ini.', '联系这个前台号码。'),
      ],
      replies: [
        pair('Teknisi datang sekitar jam tiga.', '维修人员大概三点来。'),
        pair('Kami cek dulu jadwalnya.', '我们先查一下排班。'),
        pair('Kalau belum datang, hubungi resepsionis.', '如果还没来，联系前台。'),
      ],
      variations: [
        pair('Masalahnya di kamar 1208.', '问题在 1208 房间。'),
        pair('Sudah saya laporkan tadi pagi.', '我早上已经报告过了。'),
        pair('Siapa yang akan datang cek?', '谁会来检查？'),
        pair('Tolong kasih update kalau ada perubahan.', '如果有变化请通知我。'),
      ],
      decisions: [
        {
          situation: '对方继续只说 nanti。',
          options: [
            pair('Tanya jam dan nama petugas.', '问具体时间和人员。'),
            pair('Minta nomor untuk follow up.', '要一个跟进号码。'),
          ],
        },
      ],
      localUsage: pair('Kapan bisa datang? 比 hanya “cepat ya” 更有效。', '把 nanti 变成安排。'),
      easyMistake: pair('不要只重复 “tolong cepat”。没有时间、负责人就很难跟进。', '具体才可执行。'),
      trySay: pair('Kapan teknisi bisa datang?', '维修人员什么时候能来？'),
    },
  },
  'EXP-LIF-192': {
    category: 'basics',
    task: '快递显示已送达，但我根本没收到',
    indonesian: 'Di aplikasi tertulis sudah delivered, tapi saya belum menerima paketnya.',
    explanation: '快递显示 delivered 但没收到时，查订单、问保安/前台、确认签收照片、联系 courier 和平台。',
    harvest: ['sudah delivered', 'belum menerima', 'siapa yang terima', 'foto bukti'],
    goldenScene: {
      situation: '购物平台显示包裹已送达，但你没有收到。你需要一步步找包裹。',
      goal: '确认包裹是否被前台/保安/他人签收，并拿到解决方案。',
      dialogue: [
        line('我', 'Di aplikasi tertulis sudah delivered, tapi saya belum menerima paketnya.', 'App 上显示已送达，但我还没收到包裹。'),
        line('前台', 'Boleh lihat nomor resinya?', '可以看一下物流单号吗？'),
        line('我', 'Ini resinya. Ada yang terima di resepsionis?', '这是单号。前台有人签收吗？'),
        line('前台', 'Saya cek dulu. Tidak ada nama Anda di daftar paket.', '我查一下。包裹清单里没有您的名字。'),
        line('我', 'Ada foto bukti pengiriman dari kurir?', '快递员有送达照片吗？'),
        line('前台', 'Di aplikasi ada foto, tapi lokasinya seperti tower sebelah.', 'App 有照片，但位置像隔壁楼。'),
        line('我', 'Kalau begitu saya hubungi courier dan seller juga.', '那我联系快递员和卖家。'),
        line('前台', 'Kalau paketnya masuk sini, nanti kami kabari.', '如果包裹到我们这里，我们会通知您。'),
      ],
      replies: [
        pair('Paketnya tidak ada di resepsionis.', '包裹不在前台。'),
        pair('Sepertinya salah tower.', '好像送到错的楼了。'),
        pair('Kurir belum bisa dihubungi.', '快递员还联系不上。'),
      ],
      variations: [
        pair('Siapa yang tanda tangan?', '是谁签收的？'),
        pair('Boleh cek CCTV area depan?', '可以查一下前面区域的监控吗？'),
        pair('Saya akan buat laporan di aplikasi.', '我会在 App 里投诉/申诉。'),
        pair('Tolong kabari kalau paket ditemukan.', '如果找到包裹请通知我。'),
      ],
      decisions: [
        {
          situation: '前台没有记录，但 App 有送达照片。',
          options: [
            pair('Cocokkan foto dengan lokasi gedung.', '把照片和楼的位置对照。'),
            pair('Hubungi courier dan platform dengan bukti.', '带着证据联系快递员和平台。'),
          ],
        },
      ],
      localUsage: pair('Delivered 常在印尼电商直接混用，belum menerima paketnya 是关键申诉句。', '先找证据，再升级平台。'),
      easyMistake: pair('不要一开始就责怪前台。先查记录和证据。', '包裹问题要按链路查。'),
      trySay: pair('Saya belum menerima paketnya.', '我还没有收到包裹。'),
    },
  },
  'EXP-LIF-193': {
    category: 'basics',
    task: '手机卡 / 网络突然不能用了',
    indonesian: 'Nomor saya tiba-tiba tidak ada sinyal. Bisa bantu cek paket dan SIM-nya?',
    explanation: '手机卡没信号或没网络时，说明问题、查套餐、SIM、身份验证、是否换卡和恢复时间。',
    harvest: ['tidak ada sinyal', 'paket internet', 'cek SIM', 'kapan aktif lagi'],
    goldenScene: {
      situation: '你的手机突然不能上网，在运营商柜台需要说明问题并恢复服务。',
      goal: '确认是套餐、SIM 还是网络问题，并完成恢复测试。',
      dialogue: [
        line('我', 'Nomor saya tiba-tiba tidak ada sinyal.', '我的号码突然没有信号。'),
        line('工作人员', 'Boleh saya cek nomornya?', '可以查一下号码吗？'),
        line('我', 'Ini nomornya. Paket internet saya masih ada?', '这是号码。我的流量套餐还有吗？'),
        line('工作人员', 'Paket masih ada, mungkin SIM-nya bermasalah.', '套餐还有，可能 SIM 卡有问题。'),
        line('我', 'Perlu verifikasi identitas?', '需要身份验证吗？'),
        line('工作人员', 'Iya, perlu paspor atau KITAS.', '对，需要护照或 KITAS。'),
        line('我', 'Kalau ganti SIM, berapa lama aktif lagi?', '如果换卡，多久能恢复？'),
        line('工作人员', 'Biasanya langsung aktif. Nanti kita tes internet di sini.', '通常马上恢复。等下我们在这里测试网络。'),
      ],
      replies: [
        pair('Paket internet masih aktif.', '流量套餐还有效。'),
        pair('SIM perlu diganti.', 'SIM 卡需要更换。'),
        pair('Coba restart HP dulu.', '先试着重启手机。'),
      ],
      variations: [
        pair('Internetnya tidak jalan.', '网络不能用。'),
        pair('Sinyalnya hilang terus.', '信号一直没了。'),
        pair('Nomor ini masih aktif?', '这个号码还有效吗？'),
        pair('Bisa tes internet sekarang?', '现在可以测试网络吗？'),
      ],
      decisions: [
        {
          situation: '工作人员说可能要换 SIM。',
          options: [
            pair('Tanya dokumen dan waktu aktif.', '问需要什么文件和恢复时间。'),
            pair('Tes dulu dengan restart dan cek paket.', '先重启并查套餐。'),
          ],
        },
      ],
      localUsage: pair('Tidak ada sinyal / internetnya tidak jalan 是最常用的问题描述。', '先描述现象，再查套餐。'),
      easyMistake: pair('不要只说 HP rusak。可能是套餐、SIM、信号或手机设置。', '网络问题要拆分。'),
      trySay: pair('Bisa bantu cek paket dan SIM-nya?', '可以帮我查一下套餐和 SIM 卡吗？'),
    },
  },
  'EXP-LIF-194': {
    category: 'basics',
    task: '酒店入住以后发现房间有问题',
    indonesian: 'Kamar saya ada masalah. AC-nya tidak dingin dan air panasnya tidak keluar.',
    explanation: '酒店房间有问题时，先联系前台描述问题、要求检查、询问多久，修不好再谈换房或替代方案。',
    harvest: ['kamar ada masalah', 'minta dicek', 'ganti kamar', 'solusi lain'],
    goldenScene: {
      situation: '你入住酒店后发现空调不冷、热水没有，前台说会派人来。',
      goal: '让酒店检查问题；如果修不好，拿到换房或替代方案。',
      dialogue: [
        line('我', 'Halo, kamar saya ada masalah.', '你好，我房间有问题。'),
        line('前台', 'Masalahnya apa, Pak?', '是什么问题，先生？'),
        line('我', 'AC-nya tidak dingin dan air panasnya tidak keluar.', '空调不冷，热水也没有。'),
        line('前台', 'Baik, kami kirim teknisi untuk cek.', '好的，我们派维修人员检查。'),
        line('我', 'Kira-kira berapa lama?', '大概要多久？'),
        line('前台', 'Sekitar tiga puluh menit.', '大概三十分钟。'),
        line('我', 'Kalau tidak bisa diperbaiki, apakah bisa ganti kamar?', '如果修不好，可以换房吗？'),
        line('前台', 'Kami cek ketersediaan kamar dulu, Pak.', '我们先查一下是否有空房。'),
      ],
      replies: [
        pair('Teknisi sedang menuju kamar.', '维修人员正在去房间。'),
        pair('Maaf, kamar penuh malam ini.', '抱歉，今晚房满。'),
        pair('Kami bisa pindahkan ke kamar lain.', '我们可以给您换到另一间。'),
      ],
      variations: [
        pair('Kamar terlalu berisik.', '房间太吵。'),
        pair('Kamar belum bersih.', '房间还不干净。'),
        pair('Saya tunggu sampai jam sembilan.', '我等到九点。'),
        pair('Ada solusi lain kalau tidak bisa ganti kamar?', '如果不能换房，有其他方案吗？'),
      ],
      decisions: [
        {
          situation: '前台说房满，不能换房。',
          options: [
            pair('Minta solusi lain: teknisi, kipas, atau kamar sementara.', '要求其他方案：维修、风扇或临时房间。'),
            pair('Minta update waktu yang jelas.', '要求明确更新时间。'),
          ],
        },
      ],
      localUsage: pair('Kamar saya ada masalah 是酒店前台最简单的开场句。', '先说问题，再谈换房。'),
      easyMistake: pair('不要一开始就发火要求升级房型。先让对方确认问题。', '酒店问题按步骤处理。'),
      trySay: pair('Kalau tidak bisa diperbaiki, apakah bisa ganti kamar?', '如果修不好，可以换房吗？'),
    },
  },
  'EXP-LIF-195': {
    category: 'basics',
    task: '到了陌生地方，问路并确认没走错',
    indonesian: 'Permisi, kalau mau ke stasiun, saya harus lurus atau belok kanan?',
    explanation: '问路时要确认左右、直走、距离和地标；走一段不确定时再问一次，不要硬猜。',
    harvest: ['mau ke', 'lurus atau belok', 'patokan', 'masih jauh'],
    goldenScene: {
      situation: '你到一个陌生地方，地图不清楚，需要向路人问路并确认没走错。',
      goal: '听懂基本方向，确认地标，最终到达目的地。',
      dialogue: [
        line('我', 'Permisi, kalau mau ke stasiun, lewat mana ya?', '不好意思，去车站怎么走？'),
        line('路人', 'Lurus saja, nanti belok kanan setelah minimarket.', '一直走，过便利店后右转。'),
        line('我', 'Maaf, setelah minimarket belok kanan ya?', '不好意思，是过便利店后右转对吧？'),
        line('路人', 'Iya, lalu jalan sedikit lagi.', '对，然后再走一点。'),
        line('我', 'Masih jauh dari sini?', '离这里还远吗？'),
        line('路人', 'Sekitar lima menit jalan kaki.', '走路大概五分钟。'),
        line('我', 'Patokannya minimarket itu ya?', '地标就是那个便利店对吧？'),
        line('路人', 'Betul. Kalau bingung, tanya lagi di sana.', '对。如果不确定，到那边再问一次。'),
      ],
      replies: [
        pair('Lurus terus sampai lampu merah.', '一直走到红绿灯。'),
        pair('Belok kiri setelah masjid.', '过清真寺后左转。'),
        pair('Tidak jauh, jalan kaki bisa.', '不远，可以走路。'),
      ],
      variations: [
        pair('Saya takut salah jalan.', '我怕走错。'),
        pair('Ada patokan yang mudah dilihat?', '有什么容易看到的地标？'),
        pair('Dari sini kira-kira berapa menit?', '从这里大概几分钟？'),
        pair('Saya konfirmasi sekali lagi ya.', '我再确认一次。'),
      ],
      decisions: [
        {
          situation: '你只听懂一半方向。',
          options: [
            pair('Ulangi arah yang kamu dengar untuk konfirmasi.', '重复你听到的方向来确认。'),
            pair('Tanya patokan yang mudah dilihat.', '问一个容易看到的地标。'),
          ],
        },
      ],
      localUsage: pair('Patokan 是“地标/参照物”，问路时非常实用。', '不要只记左右，要记地标。'),
      easyMistake: pair('不要假装听懂然后乱走。礼貌确认一次很正常。', '确认不是麻烦。'),
      trySay: pair('Patokannya apa ya?', '地标是什么？'),
    },
  },
  'EXP-LIF-196': {
    category: 'basics',
    task: '航班延误，整个行程要重新安排',
    indonesian: 'Penerbangan saya delay. Saya perlu atur ulang jemputan, hotel, dan jadwal meeting.',
    explanation: '航班延误会影响接机、酒店、会议等多个安排。你要确认新时间并逐项通知相关人。',
    harvest: ['penerbangan delay', 'jadwal baru', 'atur ulang', 'kabari driver'],
    goldenScene: {
      situation: '机场通知航班延误。你后面还有接机司机、酒店入住和会议安排。',
      goal: '确认新航班信息，并重新安排接机、酒店和会议时间。',
      dialogue: [
        line('我', 'Maaf, penerbangan saya delay berapa lama?', '不好意思，我的航班延误多久？'),
        line('工作人员', 'Sekitar dua jam, Pak.', '大概两小时，先生。'),
        line('我', 'Jadwal berangkat barunya jam berapa?', '新的起飞时间是几点？'),
        line('工作人员', 'Jam delapan malam, gate masih sama.', '晚上八点，登机口不变。'),
        line('我', 'Bagasi saya tetap aman ya?', '我的行李还是正常对吧？'),
        line('工作人员', 'Iya, bagasi tetap ikut penerbangan yang sama.', '对，行李跟同一班航班。'),
        line('我', 'Saya perlu kabari driver dan hotel dulu.', '我需要先通知司机和酒店。'),
        line('司机', 'Baik Pak, saya ubah jam jemput sesuai kedatangan baru.', '好的先生，我按新的到达时间改接机。'),
      ],
      replies: [
        pair('Gate tidak berubah.', '登机口没有变。'),
        pair('Bagasi tetap aman.', '行李仍然正常。'),
        pair('Saya ubah jadwal jemput.', '我更改接机时间。'),
      ],
      variations: [
        pair('Meeting saya harus diundur.', '我的会议需要推迟。'),
        pair('Hotel sudah saya kabari.', '我已经通知酒店。'),
        pair('Tolong tunggu update dari maskapai.', '请等航空公司的更新。'),
        pair('Saya konfirmasi lagi setelah boarding.', '登机后我再确认。'),
      ],
      decisions: [
        {
          situation: '延误影响接机和会议。',
          options: [
            pair('Kabari semua pihak dengan jadwal baru.', '把新时间通知所有相关人。'),
            pair('Prioritaskan driver dan meeting yang paling terdampak.', '优先通知受影响最大的司机和会议。'),
          ],
        },
      ],
      localUsage: pair('Atur ulang 很适合表达“重新安排”。', '航班一变，后面多个安排都要变。'),
      easyMistake: pair('不要只告诉别人 delay，却不给新的预计时间。', '更新要带时间。'),
      trySay: pair('Saya perlu atur ulang jadwal saya.', '我需要重新安排我的行程。'),
    },
  },
  'EXP-LIF-197': {
    category: 'basics',
    task: '发生交通事故，我要冷静处理',
    indonesian: 'Yang penting dulu, ada yang terluka atau tidak?',
    explanation: '交通事故场景只训练语言沟通，不做法律责任判断。先确认人、停车安全、联系司机/保险/警方、拍照记录和下一步。',
    harvest: ['ada yang terluka', 'parkir aman', 'foto bukti', 'jangan mengaku salah dulu'],
    goldenScene: {
      situation: '车辆发生轻微碰撞，现场紧张。你要先处理安全和沟通，不乱承诺责任。',
      goal: '在紧张情况下完成基本沟通：确认伤情、记录证据、联系相关方、确认下一步。',
      dialogue: [
        line('我', 'Yang penting dulu, ada yang terluka atau tidak?', '先确认最重要的，有人受伤吗？'),
        line('对方', 'Tidak ada, tapi mobil saya lecet.', '没有，但我的车刮了。'),
        line('我', 'Baik, kita parkir di tempat aman dulu.', '好，我们先停到安全的地方。'),
        line('司机', 'Saya hubungi asuransi ya, Pak?', '我联系保险，好吗先生？'),
        line('我', 'Iya, hubungi asuransi. Kalau perlu, kita hubungi polisi juga.', '对，联系保险。如果需要，我们也联系警方。'),
        line('对方', 'Kamu yang salah, kan?', '是你错，对吧？'),
        line('我', 'Saya belum bisa pastikan. Kita foto dulu dan catat kronologinya.', '我现在不能确认。我们先拍照并记录经过。'),
        line('我', 'Setelah itu kita tukar nomor dan tunggu arahan asuransi.', '之后我们交换号码，等保险指示。'),
      ],
      replies: [
        pair('Tidak ada yang terluka.', '没有人受伤。'),
        pair('Kita foto posisi mobil dulu.', '我们先拍车辆位置。'),
        pair('Tunggu pihak asuransi datang.', '等保险方来。'),
      ],
      variations: [
        pair('Kita tenang dulu.', '我们先冷静。'),
        pair('Tolong jangan pindahkan mobil sebelum difoto.', '拍照前请不要移动车。'),
        pair('Saya perlu hubungi driver saya.', '我需要联系我的司机。'),
        pair('Kita catat nomor plat dan kontak.', '我们记录车牌和联系方式。'),
      ],
      decisions: [
        {
          situation: '对方要求你马上承认责任。',
          options: [
            pair('Jangan mengaku salah sebelum jelas.', '情况不清楚前不要承认责任。'),
            pair('Fokus ke keselamatan, bukti, dan pihak resmi.', '专注安全、证据和正式渠道。'),
          ],
        },
      ],
      localUsage: pair('Kronologi 是事故或问题处理中常用的“经过”。', '紧张时先人身安全，再事实记录。'),
      easyMistake: pair('不要在不清楚情况下乱说 “saya yang salah”。', '这不是法律判断课，是冷静沟通。'),
      trySay: pair('Ada yang terluka atau tidak?', '有没有人受伤？'),
    },
  },
  'EXP-LIF-198': {
    category: 'basics',
    task: '手机 / 钱包 / 重要东西突然丢了',
    indonesian: 'Saya kehilangan dompet. Terakhir saya lihat di restoran sekitar jam tujuh.',
    explanation: '重要东西丢失时，先冷静回忆最后位置，询问工作人员/司机/酒店/餐厅，描述物品，留联系方式，必要时走正规挂失或报警流程。',
    harvest: ['kehilangan dompet', 'terakhir lihat', 'ciri-cirinya', 'tinggal kontak'],
    goldenScene: {
      situation: '你突然发现钱包不见了，里面有重要证件和银行卡。你需要冷静开始寻找。',
      goal: '完成现实处理：回忆、询问、描述、留联系方式，并安排挂失或报警等下一步。',
      dialogue: [
        line('我', 'Permisi, saya kehilangan dompet.', '不好意思，我的钱包丢了。'),
        line('工作人员', 'Terakhir lihat di mana, Pak?', '最后一次在哪里看到，先生？'),
        line('我', 'Terakhir saya lihat di restoran sekitar jam tujuh.', '最后一次看到是在餐厅，大概七点。'),
        line('工作人员', 'Ciri-cirinya seperti apa?', '有什么特征？'),
        line('我', 'Dompet hitam kecil, ada kartu bank dan identitas.', '黑色小钱包，里面有银行卡和证件。'),
        line('工作人员', 'Kami cek area restoran dan lost and found dulu.', '我们先查餐厅区域和失物招领。'),
        line('我', 'Kalau ada yang menemukan, tolong hubungi nomor ini.', '如果有人找到，请联系这个号码。'),
        line('工作人员', 'Baik. Kalau belum ketemu, Bapak bisa buat laporan resmi.', '好的。如果没找到，您可以做正式报失。'),
        line('我', 'Baik, saya juga akan blokir kartu dulu.', '好的，我也会先挂失银行卡。'),
      ],
      replies: [
        pair('Belum ada barang masuk ke lost and found.', '失物招领还没有收到。'),
        pair('Kami cek CCTV dulu.', '我们先查监控。'),
        pair('Tolong tinggalkan nomor yang bisa dihubungi.', '请留下可以联系的号码。'),
      ],
      variations: [
        pair('Saya kehilangan HP.', '我的手机丢了。'),
        pair('Saya kehilangan paspor.', '我的护照丢了。'),
        pair('Bentuknya kecil dan warnanya hitam.', '形状小，颜色黑。'),
        pair('Saya perlu lapor ke polisi?', '我需要报警吗？'),
      ],
      decisions: [
        {
          situation: '现场暂时找不到钱包。',
          options: [
            pair('Tinggalkan kontak dan lanjut blokir kartu.', '留下联系方式，并继续挂失银行卡。'),
            pair('Tanya prosedur laporan resmi.', '询问正式报失流程。'),
          ],
        },
      ],
      localUsage: pair('Terakhir saya lihat... 是丢东西时最关键的信息。', '先找最后位置，再描述物品。'),
      easyMistake: pair('不要慌到只说 hilang hilang。要给时间、地点、特征和联系方式。', '冷静才能找回。'),
      trySay: pair('Saya sudah melatih 100 kemampuan untuk menangani situasi nyata di Indonesia.', '我已经训练了 100 种在印尼处理真实事情的能力。'),
    },
  },
};
