export const harvestMeaningOverrides: Record<string, string> = {
  'ada yang terluka': '有人受伤了',
  'add to cart': '加入购物车',
  'aku juga': '我也是',
  'aku paham': '我理解',
  'aku yang tadi': '我是刚才那个人',
  'alasan sebenarnya': '真正的原因',
  'alternatif lain': '其他替代办法',
  'ambilkan': '帮我拿一下',
  'approval internal': '内部审批',
  'approve sebelumnya': '之前确认过',
  'asalnya dari mana': '你是哪里人 / 来自哪里',
  'asli atau fotokopi': '原件还是复印件',
  'atur ulang': '重新安排',
  'bahas apa': '聊什么',
  'bahas santai': '轻松地聊',
  'baru paham': '刚明白',
  'batas keputusan': '需要上报/决定的界限',
  'batch yang terdampak': '受影响的这一批货',
  'baterai': '电池 / 电量',
  'beban kerja': '工作负担',
  'belok kanan': '右转',
  'belum ada kabar': '还没有消息',
  'belum bisa bantu': '暂时帮不上忙',
  'belum dikirim': '还没发货',
  'belum menerima': '还没收到',
  'belum nangkep': '还没听懂 / 没 get 到',
  'belum nyala': '还没启动 / 还没亮',
  'benar-benar selesai': '真正完成',
  'berbeda dengan sampel': '和样品不一样',
  'berdasarkan timeline': '按时间线来看',
  'beri solusi': '给出解决方案',
  'biasanya nonton': '平时看什么',
  'biaya siapa': '费用谁承担',
  'bisa dipertimbangkan': '可以考虑',
  'bisa lanjut hari ini': '今天还能继续办理',
  'buka pintu': '开门',
  'bukan punya saya': '不是我的',
  'bukan selalu jualan': '不是一直卖东西',
  'butuh keputusan apa': '需要我做什么决定',
  'butuh resource apa': '需要什么资源',
  'campaign mulai besok': '活动明天开始',
  'catatan kami': '我们的记录',
  'cek chat sample': '抽查聊天样本',
  'cek order': '查订单',
  'cek resi': '查快递单号',
  'cek sim': '检查 SIM 卡',
  'charger': '充电器',
  'checklist terakhir': '最后检查清单',
  'ciri-cirinya': '特征是什么',
  'closing': '促成下单 / 成交',
  'cocok atau tidak': '合不合适',
  'cocokkan invoice': '核对发票',
  'colokan': '插座',
  'conversion turun': '转化率下降',
  'ctr turun': '点击率下降',
  'dengar kebutuhan': '先听需求',
  'dengarkan keluhan': '先听客户抱怨',
  'di po seribu pcs': '订单上是一千件',
  'dibuang di mana': '应该扔在哪里',
  'dokumen kurang': '资料不齐',
  'dp berapa persen': '定金多少比例',
  'ekspektasi gaji': '期望薪资',
  'file versi terbaru': '最新版文件',
  'follow up': '跟进',
  'follow up lagi': '再跟进一次',
  'format pdf': 'PDF 格式',
  'foto bukti': '证据照片',
  'ganti kamar': '换房间',
  'gmv kemarin': '昨天的成交额',
  'habis': '用完了 / 没有了',
  'hanya sembilan ratus lima puluh': '只有 950 件',
  'harga lebih baik': '更好的价格',
  'harga untuk seribu': '一千件的价格',
  'hari apa': '哪一天',
  'hasilnya bagaimana': '结果怎么样',
  'hindari oversell': '避免超卖',
  'hp': '手机',
  'ikut bercanda': '一起开玩笑',
  'ikut ngobrol': '一起聊天',
  'info tambahan': '补充信息',
  'informasi inti': '核心信息',
  'intinya apa': '重点是什么',
  'jadi ya': '就这么定了吧',
  'jadwal baru': '新的时间安排',
  'jangan mengaku salah dulu': '先不要承认责任',
  'jangan saling menyalahkan': '不要互相推责',
  'jangan terlalu akrab': '不要太自来熟',
  'jangan terlalu pribadi': '不要太私人',
  'jawaban jelas': '明确答复',
  'jawaban standar': '标准回答',
  'jumlah lebih besar': '更大的采购数量',
  'kabari driver': '通知司机',
  'kabari nanti': '之后告诉我',
  'kalau boleh tahu': '如果方便问一下',
  'kalau repot': '如果不方便 / 如果麻烦',
  'kalau sempat': '如果有空',
  'kamar ada masalah': '房间有问题',
  'kami bertanggung jawab': '我们会负责',
  'kapan aktif lagi': '什么时候恢复可用',
  'kapan teknisi datang': '技术人员什么时候来',
  'kehilangan dompet': '钱包丢了',
  'kelebihan kamu': '你的优势',
  'keluar hari ini': '今天发出 / 今天出货',
  'keluarga': '家人 / 家庭',
  'kenal dari mana': '从哪里认识的',
  'kenalin dulu': '先介绍一下',
  'kenapa melamar': '为什么来应聘',
  'kerja apa': '做什么工作',
  'kerja sama jangka panjang': '长期合作',
  'kerja sama panjang': '长期合作',
  'kerja sama selama ini': '这段时间的合作',
  'kerja sama selesai': '合作完成后',
  'kirim susulan atau refund': '补发还是退款',
  'kirim ulang': '重新发送',
  'kita mulai dulu': '我们先开始',
  'klik produk': '点击商品',
  'komitmen tertulis': '书面承诺',
  'kondisi lebih baik': '更好的合作条件',
  'kunci': '钥匙',
  'kurang sehat': '身体不太舒服',
  'kurang siap': '准备不充分',
  'kurir': '快递员 / 骑手',
  'langkah berikutnya': '下一步',
  'lanjut diskusi': '继续讨论',
  'lapor lebih cepat': '更早汇报',
  'lapor masalah': '报告问题',
  'lebih santai': '更轻松一点',
  'lima menit lagi': '再五分钟',
  'lima ratus pcs': '五百件',
  'lurus atau belok': '直走还是转弯',
  'lurus saja': '一直往前 / 直走就行',
  'makasih banyak': '非常感谢',
  'maksudnya apa': '什么意思',
  'masalah cs': '客服问题',
  'masalah konkretnya': '具体问题',
  'masalah utamanya': '主要问题',
  'masih jauh': '还远吗',
  'masih proses': '还在处理中',
  'mau ke': '想去 / 要去',
  'minimal balas': '至少回复一下',
  'minta bantuan kecil': '请帮一个小忙',
  'minta dicek': '请检查一下',
  'minta feedback': '请给反馈',
  'minta maaf dulu': '先道歉',
  'moq-nya berapa': '最低起订量是多少',
  'nggak bisa dibuka': '打不开',
  'nggak buru-buru': '不着急',
  'nggak ketemu': '找不到',
  'ngopi bareng': '一起喝咖啡',
  'order paling lama': '最久未处理的订单',
  'organik': '厨余 / 有机垃圾',
  'paham masalahnya': '理解问题',
  'paket internet': '流量套餐',
  'pamit dulu': '先告辞',
  'panggil kak': '叫 Kak',
  'parkir aman': '安全停车',
  'patokan': '地标 / 参照物',
  'pelunasan kapan': '什么时候付尾款',
  'penerbangan delay': '航班延误',
  'pengalaman kerja sebelumnya': '以前的工作经验',
  'penonton ada': '有人在看',
  'penurunan terbesar': '下降最多的部分',
  'performa live turun': '直播表现下降',
  'persiapan live': '直播准备',
  'pertanyaan yang sama': '同一个问题',
  'pertimbangan utama': '主要考虑点',
  'pesan kerja': '工作消息',
  'pesan urgent': '紧急消息',
  'pikir-pikir dulu': '先考虑一下',
  'pintu': '门',
  'pisah': '分开放',
  'powerbank': '充电宝',
  'produk terbaik': '表现最好的产品',
  'proses berikutnya': '下一步流程',
  'remote': '遥控器',
  'review bintang satu': '一星差评',
  'review harian': '每日复盘',
  'risiko seperti ini': '这种风险',
  'roas masih masuk': '广告回报还划算',
  'salah alamat': '地址错了 / 送错地址',
  'saldo akhir': '最终余额',
  'satu poin bisnis': '一个生意重点',
  'saya bandingkan dulu': '我先比较一下',
  'saya mengerti masalahnya': '我理解这个问题',
  'sebelum jam tiga': '三点之前',
  'sebelum live': '开播之前',
  'sebentar': '等一下 / 一会儿',
  'selesai kapan': '什么时候完成',
  'semoga lancar': '希望顺利',
  'semoga sehat': '希望身体健康',
  'setelah barang diterima': '收到货之后',
  'siapa pic': '谁是负责人',
  'siapa ya': '请问是谁',
  'siapa yang tanggung jawab': '谁负责',
  'siapa yang terima': '谁签收的',
  'sisa lima puluh': '剩下 50 件',
  'sofa': '沙发',
  'solusi konkret': '具体解决方案',
  'solusi lain': '其他解决办法',
  'solusi yang diusulkan': '建议的解决方案',
  'solusinya bagaimana': '解决方案是什么',
  'speed jual': '销售速度',
  'spend iklan': '广告花费',
  'spesifikasinya': '具体规格',
  'standar selesai': '完成标准',
  'stok cadangan': '备用库存',
  'stok tinggal berapa': '库存还剩多少',
  'stop campaign': '停止广告活动',
  'sudah coba apa': '已经试过什么',
  'sudah dari pagi': '从早上就这样',
  'sudah delivered': '显示已送达',
  'sudah dibaca': '已经读了',
  'sudah sebagian': '完成了一部分',
  'suka apa': '喜欢什么',
  'tahu lebih awal': '更早知道',
  'tanda tangan': '签收 / 签名',
  'tanya harga': '问价格',
  'target kirim hari ini': '今天必须发出的目标',
  'tempat sampah': '垃圾桶',
  'tempo pembayaran': '账期 / 付款期限',
  'terakhir lihat': '最后一次看到',
  'terlalu tinggi': '太高了',
  'tertahan berapa hari': '卡了几天',
  'tetap kontak': '保持联系',
  'tetap sopan': '保持礼貌',
  'tidak ada sinyal': '没有信号',
  'tidak apa-apa': '没关系',
  'tidak langsung menawarkan': '不要马上推销',
  'tidak seperti meeting': '不要像正式会议',
  'tiga prioritas besok': '明天三件最重要的事',
  'tinggal di mana': '住在哪里',
  'tinggal kontak': '留下联系方式',
  'tisu toilet': '卫生纸',
  'toiletnya': '厕所 / 洗手间',
  'tolong kabari': '请通知我',
  'topik yang sama': '共同话题',
  'total tagihan': '账单总额',
  'traffic turun': '流量下降',
  'trial order': '试单',
  'tukar whatsapp': '交换 WhatsApp',
  'tv': '电视',
  'urutkan fakta': '把事实按顺序理清',
  'volume akan naik': '采购量会增加',
  'water heater': '热水器',
  'posisi bapak': '您现在的位置',
  'ubah rute': '改变路线',
  'macetnya parah': '堵车很严重',
  'share location': '发送定位',
  'masuk dari': '从哪里进去',
  'beberapa tujuan': '几个目的地',
  'terminal 3': '3 号航站楼',
  'gasnya habis': '煤气用完了',
  'beberapa hal penting': '几件重要的事',
  'dicuci terpisah': '分开洗',
  'sebelum dijelaskan': '说明之前',
  'coba ulangi': '试着重复一遍',
  'hal penting': '重要事项',
  'tiga tugas utama': '三项主要任务',
  'kurang alat': '工具不够',
  'bicara baik-baik': '好好沟通',
  'soal gaji': '关于工资',
  'dengar alasannya': '听听原因',
  'penjelasan lengkap': '完整说明',
  'dengarkan satu-satu': '一个一个听',
  'briefing lima menit': '五分钟简短会议',
  'masalah utama': '主要问题',
  'target seribu pcs': '目标一千件',
  'realisasinya hanya': '实际只完成',
  'penyebab utama': '主要原因',
  'tahan pengiriman': '暂停发货',
  'mesinnya berhenti': '机器停了',
  'estimasi perbaikan': '预计维修时间',
  'bahan baku tinggal': '原材料只剩',
  'fisiknya hanya': '实物数量只有',
  'berhenti sebentar': '先停一下',
  'order urgent': '紧急订单',
  'ubah prioritas': '调整优先级',
  'permisi': '不好意思 / 打扰一下',
  'tambah': '再加 / 增加',
  'air panas': '热水',
  'teknisi': '维修人员 / 技术人员',
  'paket': '包裹 / 快递',
  'maaf': '抱歉 / 不好意思',
};
