import type { LifeCategory, LifeExperience } from '@/lib/life-experiences';
import type { WorkplacePattern } from '@/lib/workplace-patterns';

const experience = (
  id: string,
  category: LifeCategory,
  task: string,
  indonesian: string,
  explanation: string,
  harvest: string[],
  pattern: WorkplacePattern,
): LifeExperience => ({ id, category, task, chinese: task, indonesian, explanation, harvest, pattern });

const p = (indonesian: string, chinese: string): WorkplacePattern => ({ indonesian, chinese });

// Business conversations: short, natural messages for daily professional contact in Indonesia.
export const businessExperiences: LifeExperience[] = [
  experience('EXP-LIF-144', 'business', '我想预约拜访您。', 'Pak, saya mau buat janji untuk berkunjung.', '第一次联系客户或合作方时，礼貌提出拜访预约。', ['buat janji（预约）', 'berkunjung（拜访）', 'Pak（先生）'], p('Saya mau buat janji untuk [kegiatan].', '我想预约[事项]。')),
  experience('EXP-LIF-145', 'business', '您明天上午有时间吗？', 'Besok pagi Bapak ada waktu nggak?', '约见前先确认对方次日上午是否方便。', ['besok pagi（明天上午）', 'ada waktu（有时间）', 'Bapak（您、先生）'], p('[Waktu] Bapak ada waktu nggak?', '[时间]您有空吗？')),
  experience('EXP-LIF-146', 'business', '我十点过去。', 'Saya ke sana jam sepuluh ya.', '确认见面时间后，告诉对方预计到达时间。', ['ke sana（过去那里）', 'jam sepuluh（十点）', 'ya（语气词）'], p('Saya ke sana jam [waktu] ya.', '我[时间]过去。')),
  experience('EXP-LIF-147', 'business', '我们可以在您办公室见吗？', 'Kita ketemu di kantor Bapak aja bisa?', '约客户见面时，询问能否到对方办公室。', ['ketemu（见面）', 'kantor（办公室）', 'aja（就）'], p('Kita ketemu di [tempat] aja bisa?', '我们在[地点]见可以吗？')),
  experience('EXP-LIF-148', 'business', '会议改到下午可以吗？', 'Rapatnya pindah ke sore bisa nggak?', '临时需要改会议时间时，先礼貌征求意见。', ['rapat（会议）', 'pindah（改到）', 'sore（下午）'], p('[Acara]nya pindah ke [waktu] bisa nggak?', '[事项]改到[时间]可以吗？')),
  experience('EXP-LIF-149', 'business', '不好意思，我会晚十分钟到。', 'Maaf ya, saya telat sekitar sepuluh menit.', '路上耽搁时，尽早告知对方预计迟到时间。', ['maaf ya（不好意思）', 'telat（迟到）', 'sekitar（大约）'], p('Maaf ya, saya telat sekitar [waktu].', '不好意思，我会晚[时间]到。')),
  experience('EXP-LIF-150', 'business', '您到了吗？', 'Bapak sudah sampai?', '约好会面时，简短确认对方是否到达。', ['sudah sampai（已经到了）', 'Bapak（您、先生）'], p('[Orang] sudah sampai?', '[某人]到了吗？')),
  experience('EXP-LIF-151', 'business', '我在大厅等您。', 'Saya tunggu di lobi ya, Pak.', '到达办公楼后，告诉对方自己的等候位置。', ['tunggu（等）', 'lobi（大厅）', 'Pak（先生）'], p('Saya tunggu di [tempat] ya.', '我在[地点]等您。')),
  experience('EXP-LIF-152', 'business', '这位是我们公司的经理。', 'Ini manajer dari perusahaan kami.', '商务见面时，向对方介绍本方同事。', ['manajer（经理）', 'perusahaan（公司）', 'kami（我们）'], p('Ini [jabatan] dari perusahaan kami.', '这位是我们公司的[职位]。')),
  experience('EXP-LIF-153', 'business', '很高兴认识您。', 'Senang bisa kenal dengan Bapak.', '第一次正式见面时使用的自然寒暄。', ['senang（高兴）', 'kenal（认识）', 'Bapak（您、先生）'], p('Senang bisa kenal dengan [orang].', '很高兴认识[某人]。')),
  experience('EXP-LIF-154', 'business', '路上还顺利吗？', 'Perjalanannya lancar, Pak?', '客户或供应商到访时，用一句自然寒暄打开话题。', ['perjalanan（路程）', 'lancar（顺利）', 'Pak（先生）'], p('Perjalanannya [keadaan]?', '路上[状态]吗？')),
  experience('EXP-LIF-155', 'business', '您要喝咖啡还是茶？', 'Mau kopi atau teh, Pak?', '商务来访时，主动询问饮品更显自然。', ['mau（想要）', 'kopi（咖啡）', 'teh（茶）'], p('Mau [pilihan satu] atau [pilihan dua]?', '您要[选项一]还是[选项二]？')),
  experience('EXP-LIF-156', 'business', '这是我们的公司介绍。', 'Ini profil perusahaan kami, Pak.', '见面开始时，将公司资料交给对方。', ['profil perusahaan（公司介绍）', 'kami（我们）', 'Pak（先生）'], p('Ini [dokumen] kami.', '这是我们的[文件]。')),
  experience('EXP-LIF-157', 'business', '这是我们的报价。', 'Ini penawaran harga dari kami.', '讨论价格前，把正式报价提供给对方。', ['penawaran harga（报价）', 'dari kami（我们提供的）'], p('Ini [dokumen] dari kami.', '这是我们提供的[文件]。')),
  experience('EXP-LIF-158', 'business', '这个价格还可以商量吗？', 'Harganya masih bisa dibicarakan lagi nggak?', '谈合作时，礼貌询问价格是否还能讨论。', ['harga（价格）', 'masih bisa（还可以）', 'dibicarakan lagi（再谈）'], p('[Hal]nya masih bisa dibicarakan lagi nggak?', '[事项]还可以再谈吗？')),
  experience('EXP-LIF-159', 'business', '最低价格是多少？', 'Harga paling bawahnya berapa?', '需要进一步谈价时，直接但不失礼貌地询问。', ['harga paling bawah（最低价格）', 'berapa（多少）'], p('[Harga] paling bawahnya berapa?', '[价格]最低是多少？')),
  experience('EXP-LIF-160', 'business', '交货期大概多久？', 'Waktu kirimnya kira-kira berapa lama?', '确认供应能力时，询问预计交货时间。', ['waktu kirim（交货时间）', 'kira-kira（大概）', 'berapa lama（多久）'], p('[Waktu]nya kira-kira berapa lama?', '[时间]大概多久？')),
  experience('EXP-LIF-161', 'business', '我们需要内部确认一下。', 'Kami perlu diskusi internal dulu ya.', '当场不能决定时，说明需要回公司内部讨论。', ['perlu（需要）', 'diskusi internal（内部讨论）', 'dulu（先）'], p('Kami perlu [kegiatan] dulu ya.', '我们需要先[做某事]。')),
  experience('EXP-LIF-162', 'business', '我晚点给您回复。', 'Nanti saya kabari lagi ya, Pak.', '尚未能立刻确认时，承诺后续给对方消息。', ['nanti（晚点）', 'kabari（通知）', 'lagi（再）'], p('Nanti saya [kegiatan] lagi ya.', '我晚点再[做某事]。')),
  experience('EXP-LIF-163', 'business', '我已经把资料发给您了。', 'Datanya sudah saya kirim ya, Bu.', '通过 WhatsApp 或邮件发送资料后，简短提醒对方查看。', ['data（资料）', 'sudah（已经）', 'kirim（发送）'], p('[Barang]nya sudah saya kirim ya.', '[东西]我已经发给您了。')),
  experience('EXP-LIF-164', 'business', '麻烦您看一下。', 'Tolong dicek ya, Pak.', '发出报价或文件后，请对方抽空核对。', ['tolong（麻烦）', 'dicek（看一下、核对）', 'Pak（先生）'], p('Tolong [kegiatan] ya.', '麻烦您[做某事]。')),
  experience('EXP-LIF-165', 'business', '这个方案您觉得怎么样？', 'Menurut Bapak, usulan ini gimana?', '讨论方案时，邀请对方直接发表意见。', ['menurut（根据、依您看）', 'usulan（方案）', 'gimana（怎么样）'], p('Menurut [orang], [hal] ini gimana?', '[某人]觉得这个[事项]怎么样？')),
  experience('EXP-LIF-166', 'business', '我们可以先试一下。', 'Kita coba dulu aja ya.', '合作尚未完全确定时，提议先小范围尝试。', ['coba（试）', 'dulu（先）', 'aja（就）'], p('Kita coba dulu aja ya.', '我们先试一下吧。')),
  experience('EXP-LIF-167', 'business', '供应商什么时候能回复？', 'Pemasoknya kapan bisa kasih jawaban?', '等待供应商确认时，询问回复时间。', ['pemasok（供应商）', 'kapan（什么时候）', 'kasih jawaban（给答复）'], p('[Orang] kapan bisa kasih jawaban?', '[某人]什么时候能回复？')),
  experience('EXP-LIF-168', 'business', '我们下午去工厂看一下。', 'Sore ini kita lihat pabriknya ya.', '安排现场拜访时，说明当天的工厂参观计划。', ['sore ini（今天下午）', 'lihat（看）', 'pabrik（工厂）'], p('[Waktu] kita lihat [tempat]nya ya.', '[时间]我们去看看[地点]。')),
  experience('EXP-LIF-169', 'business', '需要提前安排车辆吗？', 'Perlu disiapkan kendaraan dulu nggak?', '客户或同事来访前，确认是否需要安排交通。', ['perlu（需要）', 'disiapkan（准备）', 'kendaraan（车辆）'], p('Perlu disiapkan [barang] dulu nggak?', '需要提前安排[物品]吗？')),
  experience('EXP-LIF-170', 'business', '谢谢您今天的时间。', 'Terima kasih sudah meluangkan waktu hari ini, Pak.', '会面结束时，感谢对方专门抽时间见面。', ['terima kasih（谢谢）', 'meluangkan waktu（抽出时间）', 'hari ini（今天）'], p('Terima kasih sudah meluangkan waktu.', '谢谢您抽出时间。')),
  experience('EXP-LIF-171', 'business', '今天的讨论很有帮助。', 'Diskusi hari ini sangat membantu.', '结束商务会谈时，肯定本次交流的价值。', ['diskusi（讨论）', 'sangat（非常）', 'membantu（有帮助）'], p('[Kegiatan] hari ini sangat membantu.', '今天的[活动]很有帮助。')),
  experience('EXP-LIF-172', 'business', '我们下周再见面吧。', 'Minggu depan kita ketemu lagi ya.', '需要继续讨论时，约定下周再次见面。', ['minggu depan（下周）', 'ketemu lagi（再见面）'], p('[Waktu] kita ketemu lagi ya.', '[时间]我们再见面吧。')),
  experience('EXP-LIF-173', 'business', '方便留个联系方式吗？', 'Boleh tukar kontak, Pak?', '第一次合作或见面结束时，礼貌交换联系方式。', ['boleh（可以吗）', 'tukar kontak（交换联系方式）', 'Pak（先生）'], p('Boleh tukar [informasi]?', '方便交换[信息]吗？')),
];

// Dating conversations are intentionally respectful, modern, and suitable for everyday Indonesian chat.
export const datingExperiences: LifeExperience[] = [
  experience('EXP-LIF-174', 'dating', '你好，我是小李。', 'Hai, aku Li.', '第一次在线或线下认识时，简单自然地自我介绍。', ['hai（你好）', 'aku（我）'], p('Hai, aku [nama].', '你好，我是[名字]。')),
  experience('EXP-LIF-175', 'dating', '你怎么称呼？', 'Aku panggil kamu siapa?', '初次认识时，用自然方式问对方怎么称呼。', ['panggil（称呼）', 'kamu（你）', 'siapa（谁）'], p('Aku panggil kamu siapa?', '我怎么称呼你？')),
  experience('EXP-LIF-176', 'dating', '很高兴认识你。', 'Senang kenal kamu.', '认识新朋友后，简短表达友好。', ['senang（高兴）', 'kenal（认识）', 'kamu（你）'], p('Senang kenal kamu.', '很高兴认识你。')),
  experience('EXP-LIF-177', 'dating', '你住在哪里？', 'Kamu tinggal di mana?', '聊天刚开始时，轻松了解对方住在哪个区域。', ['tinggal（住）', 'di mana（在哪里）'], p('Kamu tinggal di mana?', '你住在哪里？')),
  experience('EXP-LIF-178', 'dating', '你今天怎么样？', 'Hari ini kamu gimana?', '平时聊天时，自然地关心对方一天过得如何。', ['hari ini（今天）', 'gimana（怎么样）'], p('Hari ini kamu gimana?', '你今天怎么样？')),
  experience('EXP-LIF-179', 'dating', '你在忙吗？', 'Lagi sibuk nggak?', '发消息前先确认对方现在是否方便聊天。', ['lagi（正在）', 'sibuk（忙）'], p('Lagi [keadaan] nggak?', '你现在[状态]吗？')),
  experience('EXP-LIF-180', 'dating', '你吃饭了吗？', 'Kamu sudah makan belum?', '印尼年轻人日常聊天中常用的关心问候。', ['sudah makan（吃过饭）', 'belum（还没）'], p('Kamu sudah [kegiatan] belum?', '你已经[做某事]了吗？')),
  experience('EXP-LIF-181', 'dating', '我刚下班。', 'Aku baru selesai kerja nih.', '下班后告诉对方自己刚有空。', ['baru（刚）', 'selesai kerja（下班）', 'nih（提示语气）'], p('Aku baru selesai [kegiatan] nih.', '我刚[做完某事]。')),
  experience('EXP-LIF-182', 'dating', '要不要一起喝咖啡？', 'Mau ngopi bareng nggak?', '想轻松约对方见面时，咖啡是自然的邀请。', ['mau（想要）', 'ngopi（喝咖啡）', 'bareng（一起）'], p('Mau [kegiatan] bareng nggak?', '要不要一起[做某事]？')),
  experience('EXP-LIF-183', 'dating', '这周末有空吗？', 'Akhir pekan ini kamu ada waktu nggak?', '约周末活动前，先确认对方是否有时间。', ['akhir pekan（周末）', 'ada waktu（有时间）'], p('[Waktu] kamu ada waktu nggak?', '[时间]你有空吗？')),
  experience('EXP-LIF-184', 'dating', '我们去吃饭吧。', 'Kita makan bareng yuk.', '自然邀请对方一起吃饭。', ['makan（吃饭）', 'bareng（一起）', 'yuk（一起吧）'], p('Kita [kegiatan] bareng yuk.', '我们一起[做某事]吧。')),
  experience('EXP-LIF-185', 'dating', '你想吃什么？', 'Kamu pengin makan apa?', '约饭时直接问对方想吃什么。', ['pengin（想）', 'makan（吃）', 'apa（什么）'], p('Kamu pengin [kegiatan] apa?', '你想[做什么]？')),
  experience('EXP-LIF-186', 'dating', '我们去看电影吧。', 'Nonton film yuk.', '约电影时简短、自然地提出邀请。', ['nonton film（看电影）', 'yuk（一起吧）'], p('[Kegiatan] yuk.', '一起[做某事]吧。')),
  experience('EXP-LIF-187', 'dating', '你想看哪一部？', 'Kamu mau nonton yang mana?', '选电影时问对方更想看哪一部。', ['mau nonton（想看）', 'yang mana（哪一个）'], p('Kamu mau [kegiatan] yang mana?', '你想[做某事]哪一个？')),
  experience('EXP-LIF-188', 'dating', '我来订位吧。', 'Aku yang pesan tempatnya ya.', '确定吃饭地点后，主动说自己来订位。', ['aku yang（我来）', 'pesan tempat（订位）'], p('Aku yang [kegiatan] ya.', '我来[做某事]吧。')),
  experience('EXP-LIF-189', 'dating', '我到了。', 'Aku sudah sampai nih.', '到约会地点后，简短通知对方。', ['sudah sampai（已经到了）', 'nih（提示语气）'], p('Aku sudah sampai nih.', '我到了。')),
  experience('EXP-LIF-190', 'dating', '我在门口。', 'Aku di depan ya.', '到餐厅或电影院后，说自己在门口等。', ['di depan（在门口）', 'aku（我）'], p('Aku di [tempat] ya.', '我在[地点]。')),
  experience('EXP-LIF-191', 'dating', '不好意思，我会晚一点。', 'Maaf ya, aku agak telat.', '预计迟到时，尽快简短地通知对方。', ['maaf ya（不好意思）', 'agak（有点）', 'telat（迟到）'], p('Maaf ya, aku agak [keadaan].', '不好意思，我有点[状态]。')),
  experience('EXP-LIF-192', 'dating', '没关系，慢慢来。', 'Nggak apa-apa kok, santai aja.', '对方迟到或紧张时，用自然口语安慰。', ['nggak apa-apa kok（没关系）', 'santai aja（放轻松）'], p('Nggak apa-apa kok, [ungkapan].', '没关系，[表达]。')),
  experience('EXP-LIF-193', 'dating', '我今天有点累。', 'Hari ini aku agak capek.', '聊天中自然表达自己今天有点累。', ['hari ini（今天）', 'agak（有点）', 'capek（累）'], p('Hari ini aku agak [keadaan].', '我今天有点[状态]。')),
  experience('EXP-LIF-194', 'dating', '你还好吗？', 'Kamu nggak apa-apa?', '发现对方情绪不对或不舒服时，直接关心。', ['nggak apa-apa（没事吧）', 'kamu（你）'], p('Kamu nggak apa-apa?', '你还好吗？')),
  experience('EXP-LIF-195', 'dating', '别想太多。', 'Jangan kebanyakan mikir ya.', '对方烦恼时，用温和的口气安慰。', ['jangan（不要）', 'kebanyakan mikir（想太多）'], p('Jangan kebanyakan [kegiatan] ya.', '别太[做某事]。')),
  experience('EXP-LIF-196', 'dating', '我在这里陪你。', 'Aku temenin kamu kok.', '对方需要陪伴时，表达自己会在身边。', ['temenin（陪伴）', 'kamu（你）', 'kok（强调语气）'], p('Aku temenin kamu kok.', '我陪着你。')),
  experience('EXP-LIF-197', 'dating', '你今天很好看。', 'Kamu hari ini cantik banget.', '见面时用自然、不过分的方式称赞对方。', ['cantik（漂亮）', 'banget（非常）', 'hari ini（今天）'], p('Kamu hari ini [pujian] banget.', '你今天非常[称赞]。')),
  experience('EXP-LIF-198', 'dating', '你的新发型很好看。', 'Rambut barumu cocok banget.', '注意到对方的新发型时，给出具体称赞。', ['rambut baru（新发型）', 'cocok（适合）', 'banget（非常）'], p('[Hal] barumu cocok banget.', '你的新[东西]很好看。')),
  experience('EXP-LIF-199', 'dating', '跟你聊天很开心。', 'Chat sama kamu seru banget.', '聊天氛围不错时，表达喜欢和对方聊天。', ['chat（聊天）', 'sama kamu（和你）', 'seru（开心、有趣）'], p('[Kegiatan] sama kamu seru banget.', '和你[做某事]很开心。')),
  experience('EXP-LIF-200', 'dating', '我喜欢和你在一起的感觉。', 'Aku suka kalau lagi sama kamu.', '关系更熟悉后，温和表达好感。', ['suka（喜欢）', 'kalau（当……时）', 'sama kamu（和你）'], p('Aku suka kalau lagi sama kamu.', '我喜欢和你在一起。')),
  experience('EXP-LIF-201', 'dating', '我想更了解你。', 'Aku pengin kenal kamu lebih jauh.', '想认真发展关系时，表达希望更多了解对方。', ['pengin（想）', 'kenal（了解）', 'lebih jauh（更多）'], p('Aku pengin kenal kamu lebih jauh.', '我想更了解你。')),
  experience('EXP-LIF-202', 'dating', '你愿意和我交往吗？', 'Kamu mau jadi pacarku nggak?', '明确表达心意时，直接而尊重地询问对方。', ['mau（愿意）', 'jadi pacarku（做我恋人）'], p('Kamu mau jadi [hubungan] nggak?', '你愿意做我的[关系]吗？')),
  experience('EXP-LIF-203', 'dating', '不用急着回答。', 'Nggak usah jawab sekarang kok.', '表白后给对方空间，不催促决定。', ['nggak usah（不用）', 'jawab（回答）', 'sekarang（现在）'], p('Nggak usah [kegiatan] sekarang kok.', '不用现在[做某事]。')),
  experience('EXP-LIF-204', 'dating', '对不起，我刚才说话不太好。', 'Maaf ya, tadi aku ngomongnya kurang enak.', '说话不妥后，承认并真诚道歉。', ['maaf ya（对不起）', 'tadi（刚才）', 'kurang enak（不太好）'], p('Maaf ya, tadi aku [kegiatan]nya kurang enak.', '对不起，我刚才[做某事]不太好。')),
  experience('EXP-LIF-205', 'dating', '我不是那个意思。', 'Aku nggak maksud begitu kok.', '发生误会时，马上澄清自己的本意。', ['nggak maksud（不是那个意思）', 'begitu（那样）', 'kok（强调）'], p('Aku nggak maksud begitu kok.', '我不是那个意思。')),
  experience('EXP-LIF-206', 'dating', '我们晚点再聊吧。', 'Nanti kita lanjut chat lagi ya.', '现在不方便继续聊时，温和结束话题。', ['nanti（晚点）', 'lanjut chat（继续聊）', 'lagi（再）'], p('Nanti kita lanjut [kegiatan] lagi ya.', '我们晚点再继续[做某事]吧。')),
  experience('EXP-LIF-207', 'dating', '你到家了跟我说一声。', 'Kalau sudah sampai rumah, kabari aku ya.', '约会结束后，关心对方是否安全到家。', ['sampai rumah（到家）', 'kabari（告诉）', 'aku（我）'], p('Kalau sudah sampai [tempat], kabari aku ya.', '到了[地点]告诉我一声。')),
  experience('EXP-LIF-208', 'dating', '今天谢谢你。', 'Makasih ya buat hari ini.', '约会结束后，用轻松的语气表达感谢。', ['makasih（谢谢）', 'buat hari ini（为了今天）'], p('Makasih ya buat [hal].', '谢谢你[事情]。')),
  experience('EXP-LIF-209', 'dating', '我今天很开心。', 'Aku senang banget hari ini.', '见面结束后，告诉对方自己度过了愉快的一天。', ['senang（开心）', 'banget（非常）', 'hari ini（今天）'], p('Aku [perasaan] banget hari ini.', '我今天很[感受]。')),
  experience('EXP-LIF-210', 'dating', '下次我们再去吧。', 'Lain kali kita ke sana lagi ya.', '喜欢今天的地点或活动时，轻松约下次再来。', ['lain kali（下次）', 'ke sana（去那里）', 'lagi（再）'], p('Lain kali kita ke sana lagi ya.', '下次我们再去吧。')),
  experience('EXP-LIF-211', 'dating', '明天见。', 'Sampai ketemu besok ya.', '约好隔天见面后，自然地道别。', ['sampai ketemu（见面）', 'besok（明天）'], p('Sampai ketemu [waktu] ya.', '[时间]见。')),
  experience('EXP-LIF-212', 'dating', '晚安，早点休息。', 'Selamat malam, istirahat ya.', '晚上聊天结束时，温柔但日常地道晚安。', ['selamat malam（晚安）', 'istirahat（休息）'], p('Selamat malam, [ungkapan] ya.', '晚安，[表达]。')),
  experience('EXP-LIF-213', 'dating', '你怎么还没回我？', 'Kok belum balas chat aku?', '熟悉后询问对方为何还没回复消息，语气仍保持轻松。', ['kok（怎么）', 'belum balas（还没回复）', 'chat（消息）'], p('Kok belum balas [pesan] aku?', '你怎么还没回复我的[消息]？')),
  experience('EXP-LIF-214', 'dating', '刚才在开会，没看到消息。', 'Tadi lagi rapat, jadi belum lihat chatnya.', '晚回消息时，简短说明刚才没看到。', ['tadi（刚才）', 'lagi rapat（在开会）', 'belum lihat（没看到）'], p('Tadi lagi [kegiatan], jadi belum lihat [pesan].', '刚才在[做某事]，所以没看到[消息]。')),
  experience('EXP-LIF-215', 'dating', '没事，你有空再回。', 'Nggak apa-apa, balas kalau sudah sempat ya.', '对方忙时，表示理解并给对方空间。', ['nggak apa-apa（没事）', 'balas（回复）', 'sempat（有空）'], p('[Kegiatan] kalau sudah sempat ya.', '有空再[做某事]。')),
  experience('EXP-LIF-216', 'dating', '今天不太方便见面。', 'Hari ini aku belum bisa ketemu.', '临时不方便见面时，直接但礼貌地说明。', ['hari ini（今天）', 'belum bisa（还不能）', 'ketemu（见面）'], p('[Waktu] aku belum bisa [kegiatan].', '[时间]我还不能[做某事]。')),
  experience('EXP-LIF-217', 'dating', '我们改天吧。', 'Kita lain kali aja ya.', '需要取消或延期见面时，用轻松的语气改约。', ['lain kali（改天）', 'aja（就）'], p('Kita lain kali aja ya.', '我们改天吧。')),
  experience('EXP-LIF-218', 'dating', '祝你生日快乐！', 'Selamat ulang tahun ya!', '对方生日当天，使用最常见自然的祝福。', ['selamat ulang tahun（生日快乐）', 'ya（语气词）'], p('Selamat ulang tahun ya!', '祝你生日快乐！')),
  experience('EXP-LIF-219', 'dating', '希望你喜欢这个。', 'Semoga kamu suka ya.', '送小礼物时，简洁表达自己的心意。', ['semoga（希望）', 'suka（喜欢）'], p('Semoga kamu suka ya.', '希望你喜欢。')),
  experience('EXP-LIF-220', 'dating', '节日快乐！', 'Selamat merayakan ya!', '节日期间，向对方送上不限定宗教的祝福。', ['selamat merayakan（节日快乐）', 'ya（语气词）'], p('Selamat merayakan ya!', '节日快乐！')),
  experience('EXP-LIF-221', 'dating', '到家后告诉我。', 'Sampai rumah, kabari aku ya.', '送对方回家或分别后，关心对方安全到家。', ['sampai rumah（到家）', 'kabari（告诉）', 'aku（我）'], p('Sampai [tempat], kabari aku ya.', '到了[地点]告诉我。')),
  experience('EXP-LIF-222', 'dating', '我送你回家吧。', 'Aku antar kamu pulang ya.', '约会结束时，礼貌提出送对方回家。', ['antar（送）', 'pulang（回家）', 'ya（语气词）'], p('Aku antar kamu [tujuan] ya.', '我送你[目的地]吧。')),
  experience('EXP-LIF-223', 'dating', '路上小心。', 'Hati-hati di jalan ya.', '分别时最常用、自然的关心表达。', ['hati-hati（小心）', 'di jalan（路上）', 'ya（语气词）'], p('Hati-hati di [tempat] ya.', '在[地点]小心。')),
];
