import type { LifeExperience } from '@/lib/life-experiences';
import type { GoldenSceneContent } from '@/lib/golden-scenes';
import type { WorkplacePattern } from '@/lib/workplace-patterns';

const pattern = (indonesian: string, chinese: string): WorkplacePattern => ({ indonesian, chinese });

const scene = (
  id: string,
  task: string,
  indonesian: string,
  explanation: string,
  harvest: string[],
  patternText: WorkplacePattern,
  goldenScene: GoldenSceneContent,
): LifeExperience => ({
  id,
  category: 'rumah-harian',
  task,
  chinese: task,
  indonesian,
  explanation,
  harvest,
  pattern: patternText,
  goldenScene,
});

export const goldenLifeExperiences: LifeExperience[] = [
  scene(
    'EXP-LIF-224',
    '问厕所在哪里',
    'Permisi, toiletnya di mana?',
    'Digunakan saat sopan menanyakan lokasi toilet di rumah, kos, atau tempat umum.',
    ['permisi', 'toiletnya', 'di mana', 'lurus saja', 'belok kanan'],
    pattern('Permisi, [tempat] di mana?', '不好意思，[地点]在哪里？'),
    {
      situation: 'Kamu sedang di rumah orang, kos, atau tempat umum dan perlu menanyakan lokasi toilet dengan sopan.',
      dialogue: [
        { speaker: '我', indonesian: 'Permisi, toiletnya di mana?', chinese: '不好意思，请问厕所在哪里？' },
        { speaker: '对方', indonesian: 'Lurus saja, lalu belok kanan di ujung lorong.', chinese: '一直走，然后在走廊尽头右转。' },
        { speaker: '我', indonesian: 'Oh, dekat dapur ya?', chinese: '哦，在厨房附近吗？' },
        { speaker: '对方', indonesian: 'Iya, sebelah kanan dapur.', chinese: '对，在厨房右边。' },
        { speaker: '我', indonesian: 'Terima kasih.', chinese: '谢谢。' },
      ],
      replies: [
        { indonesian: 'Di sebelah kanan dapur.', chinese: '在厨房右边。' },
        { indonesian: 'Di ujung lorong.', chinese: '在走廊尽头。' },
        { indonesian: 'Lurus saja lalu belok kanan.', chinese: '一直走然后右转。' },
        { indonesian: 'Dekat kamar belakang.', chinese: '在后面的房间附近。' },
      ],
      variations: [
        { indonesian: 'Permisi, kamar mandinya di mana?', chinese: '不好意思，洗手间在哪里？' },
        { indonesian: 'Permisi, toilet tamu di mana?', chinese: '不好意思，客用厕所在哪里？' },
        { indonesian: 'Permisi, WC-nya di mana?', chinese: '不好意思，厕所在哪里？' },
        { indonesian: 'Permisi, toilet umum di mana?', chinese: '不好意思，公共厕所在哪里？' },
      ],
      localUsage: { indonesian: 'Toiletnya di mana ya?', chinese: '更口语一点也可以直接这样问。' },
      easyMistake: { indonesian: 'WC ada di mana?', chinese: '能懂，但对陌生人来说稍微太硬。' },
      trySay: { indonesian: 'Permisi, toiletnya di mana?', chinese: '不好意思，请问厕所在哪里？' },
    },
  ),
  scene(
    'EXP-LIF-225',
    '厕所没有卫生纸',
    'Tisu toiletnya habis.',
    'Digunakan saat要说明 toilet 纸已经用完，需要补充。',
    ['tisu toilet', 'habis', 'stok', 'tambah', 'ambilkan'],
    pattern('Tisu [barang]nya habis.', '[物品]已经用完了。'),
    {
      situation: 'Kamu发现厕所里的卫生纸没了，需要提醒家人、室友或管理员补上。',
      dialogue: [
        { speaker: '我', indonesian: 'Tisu toiletnya habis.', chinese: '厕所纸用完了。' },
        { speaker: '对方', indonesian: 'Oh, saya ambilkan sebentar.', chinese: '哦，我马上拿来。' },
        { speaker: '我', indonesian: 'Kalau ada stoknya, boleh ditambah juga.', chinese: '如果还有库存，也可以顺便补一下。' },
        { speaker: '对方', indonesian: 'Iya, saya isi lagi.', chinese: '好，我再补上。' },
        { speaker: '我', indonesian: 'Terima kasih.', chinese: '谢谢。' },
      ],
      replies: [
        { indonesian: 'Sebentar, saya ambil dulu.', chinese: '等一下，我先去拿。' },
        { indonesian: 'Saya isi lagi ya.', chinese: '我再补一下。' },
        { indonesian: 'Masih ada di lemari.', chinese: '柜子里还有。' },
        { indonesian: 'Oke, saya cek.', chinese: '好，我看看。' },
      ],
      variations: [
        { indonesian: 'Sabunnya juga habis.', chinese: '洗手液也用完了。' },
        { indonesian: 'Tisunya tinggal sedikit.', chinese: '纸巾只剩一点了。' },
        { indonesian: 'Stok tisu harus ditambah.', chinese: '卫生纸库存要补了。' },
        { indonesian: 'Kalau ada, tolong isi ya.', chinese: '如果有的话，请帮忙补上。' },
      ],
      localUsage: { indonesian: 'Tisunya habis.', chinese: '更自然的简短说法。' },
      easyMistake: { indonesian: 'Permisi, tisu toilet belum ada habisnya.', chinese: '句子不自然，像中文直译。' },
      trySay: { indonesian: 'Tisu toiletnya habis.', chinese: '厕所纸用完了。' },
    },
  ),
  scene(
    'EXP-LIF-226',
    '洗澡没有热水',
    'Air panasnya belum nyala.',
    'Dipakai saat mau mandi tetapi water heater belum menyala atau air masih dingin.',
    ['air panas', 'belum nyala', 'water heater', 'cek', 'teknisi'],
    pattern('Air [kondisi]nya belum nyala.', '[状态]还没有打开。'),
    {
      situation: 'Kamu mau mandi, tapi air panas belum keluar dan perlu meminta bantuan.',
      dialogue: [
        { speaker: '我', indonesian: 'Air panasnya belum nyala.', chinese: '热水还没开。' },
        { speaker: '对方', indonesian: 'Oh, saya cek dulu ya.', chinese: '哦，我先检查一下。' },
        { speaker: '我', indonesian: 'Kalau bisa, tolong bantu nyalakan sekarang.', chinese: '如果可以，请现在帮我打开。' },
        { speaker: '对方', indonesian: 'Baik, sebentar.', chinese: '好的，稍等。' },
        { speaker: '我', indonesian: 'Terima kasih.', chinese: '谢谢。' },
      ],
      replies: [
        { indonesian: 'Water heater-nya belum menyala.', chinese: '热水器还没开。' },
        { indonesian: 'Saya panggil teknisi dulu.', chinese: '我先叫维修人员。' },
        { indonesian: 'Sebentar, saya periksa.', chinese: '等一下，我检查一下。' },
        { indonesian: 'Nanti saya kabari lagi.', chinese: '等下我再通知你。' },
      ],
      variations: [
        { indonesian: 'Airnya dingin.', chinese: '水是冷的。' },
        { indonesian: 'Air panasnya tidak keluar.', chinese: '热水没有出来。' },
        { indonesian: 'Tolong cek air panasnya.', chinese: '请检查一下热水。' },
        { indonesian: 'Water heater-nya belum nyala.', chinese: '热水器还没打开。' },
      ],
      localUsage: { indonesian: 'Air panasnya belum keluar.', chinese: '更口语一点。' },
      easyMistake: { indonesian: 'Kalau air panas belum kering, tolong cepat.', chinese: '语义错误，混淆了“热水”和“干不干”。' },
      trySay: { indonesian: 'Air panasnya belum nyala.', chinese: '热水还没开。' },
    },
  ),
  scene(
    'EXP-LIF-227',
    '手机没电，找充电器',
    'HP saya hampir habis baterainya.',
    'Dipakai saat baterai HP hampir habis dan perlu charger atau colokan.',
    ['HP', 'baterai', 'charger', 'colokan', 'powerbank'],
    pattern('HP saya [kondisi].', '我的手机[状态]。'),
    {
      situation: 'Kamu butuh charger atau colokan karena baterai HP hampir habis.',
      dialogue: [
        { speaker: '我', indonesian: 'HP saya hampir habis baterainya.', chinese: '我的手机电量快没了。' },
        { speaker: '对方', indonesian: 'Ada charger di meja.', chinese: '桌上有充电器。' },
        { speaker: '我', indonesian: 'Boleh pinjam sebentar?', chinese: '可以借我一下吗？' },
        { speaker: '对方', indonesian: 'Iya, silakan.', chinese: '可以，请用吧。' },
        { speaker: '我', indonesian: 'Terima kasih.', chinese: '谢谢。' },
      ],
      replies: [
        { indonesian: 'Colokannya di sebelah kanan.', chinese: '插座在右边。' },
        { indonesian: 'Powerbank ada di tas.', chinese: '充电宝在包里。' },
        { indonesian: 'Chargernya sedang dipakai.', chinese: '充电器正在用。' },
        { indonesian: 'Saya carikan dulu ya.', chinese: '我先帮你找一下。' },
      ],
      variations: [
        { indonesian: 'HP-ku lowbat.', chinese: '我的手机快没电了。' },
        { indonesian: 'Ada charger nggak?', chinese: '有充电器吗？' },
        { indonesian: 'Bisa pinjam colokan?', chinese: '可以借用插座吗？' },
        { indonesian: 'Saya butuh powerbank sebentar.', chinese: '我暂时需要充电宝。' },
      ],
      localUsage: { indonesian: 'Lowbat banget.', chinese: '非常口语的说法。' },
      easyMistake: { indonesian: 'HP-ku mati listrik.', chinese: '直译不自然，手机不会“停电”。' },
      trySay: { indonesian: 'HP saya hampir habis baterainya.', chinese: '我的手机电量快没了。' },
    },
  ),
  scene(
    'EXP-LIF-228',
    '找不到遥控器',
    'Remote-nya nggak ketemu.',
    'Dipakai saat remote TV atau AC tidak ditemukan di rumah.',
    ['remote', 'nggak ketemu', 'sofa', 'meja', 'TV'],
    pattern('[Barang]nya nggak ketemu.', '[物品]找不到了。'),
    {
      situation: 'Kamu mencari remote TV atau AC tetapi tidak ketemu di rumah.',
      dialogue: [
        { speaker: '我', indonesian: 'Remote-nya nggak ketemu.', chinese: '遥控器找不到了。' },
        { speaker: '对方', indonesian: 'Coba cari di sofa.', chinese: '试着在沙发上找找。' },
        { speaker: '我', indonesian: 'Oh iya, ada di meja kecil.', chinese: '哦，对了，在小桌子上。' },
        { speaker: '对方', indonesian: 'Iya, tadi saya taruh di situ.', chinese: '对，我刚才放在那里了。' },
        { speaker: '我', indonesian: 'Ketemu juga.', chinese: '终于找到了。' },
      ],
      replies: [
        { indonesian: 'Di sofa mungkin.', chinese: '可能在沙发上。' },
        { indonesian: 'Di meja sebelah TV.', chinese: '在电视旁边的桌子上。' },
        { indonesian: 'Coba cari di kamar.', chinese: '试着在房间里找找。' },
        { indonesian: 'Saya lihat tadi di ruang tamu.', chinese: '我刚才在客厅看到过。' },
      ],
      variations: [
        { indonesian: 'Kuncinya nggak ketemu.', chinese: '钥匙找不到了。' },
        { indonesian: 'HP-ku nggak ketemu.', chinese: '我的手机找不到了。' },
        { indonesian: 'Coba cari di meja dulu.', chinese: '先在桌子上找找。' },
        { indonesian: 'Remote TV-nya di mana ya?', chinese: '电视遥控器在哪里呢？' },
      ],
      localUsage: { indonesian: 'Nggak ketemu.', chinese: '很口语，就是“找不到”。' },
      easyMistake: { indonesian: 'Remote tidak ada kemarin.', chinese: '时间和意思都不自然。' },
      trySay: { indonesian: 'Remote-nya nggak ketemu.', chinese: '遥控器找不到了。' },
    },
  ),
  scene(
    'EXP-LIF-229',
    '门打不开',
    'Pintunya nggak bisa dibuka.',
    'Dipakai saat pintu macet, terkunci, atau sulit dibuka di rumah atau kos.',
    ['pintu', 'nggak bisa dibuka', 'kunci', 'macet', 'tolong'],
    pattern('Pintunya nggak bisa dibuka.', '门打不开。'),
    {
      situation: 'Kamu mencoba membuka pintu rumah atau kos tetapi pintunya macet.',
      dialogue: [
        { speaker: '我', indonesian: 'Pintunya nggak bisa dibuka.', chinese: '门打不开。' },
        { speaker: '对方', indonesian: 'Coba putar kuncinya pelan-pelan.', chinese: '试着慢慢转钥匙。' },
        { speaker: '我', indonesian: 'Sudah, tapi tetap macet.', chinese: '转了，但还是卡住。' },
        { speaker: '对方', indonesian: 'Biar saya bantu lihat.', chinese: '我来帮你看看。' },
        { speaker: '我', indonesian: 'Terima kasih.', chinese: '谢谢。' },
      ],
      replies: [
        { indonesian: 'Kuncinya mungkin seret.', chinese: '钥匙可能有点卡。' },
        { indonesian: 'Saya bantu buka ya.', chinese: '我帮你打开。' },
        { indonesian: 'Coba dorong sedikit.', chinese: '试着推一下。' },
        { indonesian: 'Mungkin pintunya ketahan.', chinese: '可能门被挡住了。' },
      ],
      variations: [
        { indonesian: 'Pintunya macet.', chinese: '门卡住了。' },
        { indonesian: 'Kuncinya nggak muter.', chinese: '钥匙转不动。' },
        { indonesian: 'Bisa bantu buka pintu?', chinese: '可以帮忙开门吗？' },
        { indonesian: 'Kayaknya pintunya ketahan.', chinese: '好像门被卡住了。' },
      ],
      localUsage: { indonesian: 'Pintunya seret.', chinese: '很自然，表示门不好开。' },
      easyMistake: { indonesian: 'Pintu tidak terbuka.', chinese: '太书面，不如前者自然。' },
      trySay: { indonesian: 'Pintunya nggak bisa dibuka.', chinese: '门打不开。' },
    },
  ),
  scene(
    'EXP-LIF-230',
    '有人敲门',
    'Siapa ya?',
    'Dipakai saat ada yang mengetuk pintu dan kita ingin tahu siapa yang datang.',
    ['siapa ya', 'permisi', 'sebentar', 'buka pintu', 'tamu'],
    pattern('Siapa ya?', '谁呀？'),
    {
      situation: 'Ada orang mengetuk pintu rumah atau kamar, dan kamu ingin memastikan siapa yang datang.',
      dialogue: [
        { speaker: '我', indonesian: 'Siapa ya?', chinese: '谁呀？' },
        { speaker: '对方', indonesian: 'Saya, Pak RT.', chinese: '我，居委会的 Pak RT。' },
        { speaker: '我', indonesian: 'Oh, sebentar ya.', chinese: '哦，稍等一下。' },
        { speaker: '对方', indonesian: 'Oke.', chinese: '好的。' },
        { speaker: '我', indonesian: 'Silakan masuk.', chinese: '请进。' },
      ],
      replies: [
        { indonesian: 'Saya, paket.', chinese: '我，送快递的。' },
        { indonesian: 'Saya dari depan.', chinese: '我是前面的。' },
        { indonesian: 'Pak RT, mau kasih info.', chinese: 'Pak RT，来通知消息。' },
        { indonesian: 'Tetangga, boleh masuk?', chinese: '邻居，可以进来吗？' },
      ],
      variations: [
        { indonesian: 'Permisi, siapa di luar?', chinese: '不好意思，外面是谁？' },
        { indonesian: 'Sebentar, saya buka.', chinese: '等一下，我来开门。' },
        { indonesian: 'Ada tamu di depan.', chinese: '前面有客人。' },
        { indonesian: 'Siapa, ya?', chinese: '请问是谁呀？' },
      ],
      localUsage: { indonesian: 'Siapa, ya?', chinese: '更温和一点。' },
      easyMistake: { indonesian: 'Ada yang ketok.', chinese: '能懂，但不如直接确认是谁。' },
      trySay: { indonesian: 'Siapa ya?', chinese: '谁呀？' },
    },
  ),
  scene(
    'EXP-LIF-231',
    '收快递',
    'Pak, paketnya sudah sampai.',
    'Dipakai saat menerima paket dari kurir atau orang yang mengantar barang.',
    ['paket', 'sudah sampai', 'kurir', 'terima kasih', 'tanda tangan'],
    pattern('Paketnya sudah sampai.', '包裹已经到了。'),
    {
      situation: 'Kamu menerima paket dari kurir di rumah atau kos.',
      dialogue: [
        { speaker: '我', indonesian: 'Pak, paketnya sudah sampai.', chinese: '先生，包裹到了。' },
        { speaker: '对方', indonesian: 'Oh, terima kasih. Saya ambil sekarang.', chinese: '哦，谢谢。我现在拿。' },
        { speaker: '我', indonesian: 'Tolong tanda tangan di sini ya.', chinese: '请在这里签名。' },
        { speaker: '对方', indonesian: 'Baik.', chinese: '好的。' },
        { speaker: '我', indonesian: 'Terima kasih juga.', chinese: '也谢谢您。' },
      ],
      replies: [
        { indonesian: 'Silakan diterima.', chinese: '请收下。' },
        { indonesian: 'Ini paket untuk Anda.', chinese: '这是给您的包裹。' },
        { indonesian: 'Tolong cek isinya ya.', chinese: '请检查一下里面的内容。' },
        { indonesian: 'Boleh tanda tangan di sini.', chinese: '可以在这里签名。' },
      ],
      variations: [
        { indonesian: 'Ada paket buat saya?', chinese: '有给我的包裹吗？' },
        { indonesian: 'Kurirnya sudah datang?', chinese: '快递员到了吗？' },
        { indonesian: 'Tolong taruh di depan saja.', chinese: '请放在门口就好。' },
        { indonesian: 'Saya terima dulu ya.', chinese: '我先收下。' },
      ],
      localUsage: { indonesian: 'Paketnya sudah datang.', chinese: '更口语的说法。' },
      easyMistake: { indonesian: 'Saya menerima paket.', chinese: '过于书面，不像日常对话。' },
      trySay: { indonesian: 'Pak, paketnya sudah sampai.', chinese: '先生，包裹到了。' },
    },
  ),
  scene(
    'EXP-LIF-232',
    '快递送错',
    'Maaf, paket ini bukan punya saya.',
    'Dipakai saat paket yang datang ternyata tertukar atau salah alamat.',
    ['maaf', 'bukan punya saya', 'salah alamat', 'cek resi', 'kurir'],
    pattern('Maaf, paket ini bukan punya saya.', '不好意思，这个包裹不是我的。'),
    {
      situation: 'Kamu menerima paket tetapi ternyata nama atau alamatnya tidak cocok.',
      dialogue: [
        { speaker: '我', indonesian: 'Maaf, paket ini bukan punya saya.', chinese: '不好意思，这个包裹不是我的。' },
        { speaker: '对方', indonesian: 'Oh, maaf. Nomornya berapa ya?', chinese: '哦，抱歉。号码是多少？' },
        { speaker: '我', indonesian: 'Alamatnya beda.', chinese: '地址不一样。' },
        { speaker: '对方', indonesian: 'Baik, saya cek ke kurir dulu.', chinese: '好的，我先和快递员确认。' },
        { speaker: '我', indonesian: 'Terima kasih.', chinese: '谢谢。' },
      ],
      replies: [
        { indonesian: 'Maaf, mungkin salah alamat.', chinese: '不好意思，可能地址错了。' },
        { indonesian: 'Coba cek resinya dulu ya.', chinese: '先查一下物流单号。' },
        { indonesian: 'Sepertinya tertukar.', chinese: '好像弄错了。' },
        { indonesian: 'Saya hubungi kurirnya.', chinese: '我联系快递员。' },
      ],
      variations: [
        { indonesian: 'Alamatnya tidak sesuai.', chinese: '地址不一致。' },
        { indonesian: 'Paketnya salah kirim.', chinese: '包裹送错了。' },
        { indonesian: 'Ini paket orang lain.', chinese: '这是别人的包裹。' },
        { indonesian: 'Tolong cek lagi ya.', chinese: '请再确认一下。' },
      ],
      localUsage: { indonesian: 'Paketnya salah kirim.', chinese: '很自然，表示快递送错。' },
      easyMistake: { indonesian: 'Kalau baju belum kering-nya rusak, bisa diganti?', chinese: '语义明显串位，不能用。' },
      trySay: { indonesian: 'Maaf, paket ini bukan punya saya.', chinese: '不好意思，这个包裹不是我的。' },
    },
  ),
  scene(
    'EXP-LIF-233',
    '垃圾放哪里',
    'Sampahnya dibuang di mana?',
    'Dipakai saat ingin tahu tempat membuang sampah di rumah, kos, atau lingkungan sekitar.',
    ['sampah', 'dibuang di mana', 'tempat sampah', 'pisah', 'organik'],
    pattern('Sampahnya dibuang di mana?', '垃圾要扔在哪里？'),
    {
      situation: 'Kamu ingin memastikan sampah rumah dibuang ke tempat yang benar.',
      dialogue: [
        { speaker: '我', indonesian: 'Sampahnya dibuang di mana?', chinese: '垃圾要扔在哪里？' },
        { speaker: '对方', indonesian: 'Di tong sampah depan, ya.', chinese: '放在前面的垃圾桶里。' },
        { speaker: '我', indonesian: 'Yang plastik dipisah juga?', chinese: '塑料也要分开吗？' },
        { speaker: '对方', indonesian: 'Iya, dipisah saja.', chinese: '对，分开就好。' },
        { speaker: '我', indonesian: 'Baik, terima kasih.', chinese: '好的，谢谢。' },
      ],
      replies: [
        { indonesian: 'Di belakang rumah.', chinese: '在房子后面。' },
        { indonesian: 'Pisahkan organik dan plastik.', chinese: '把有机和塑料分开。' },
        { indonesian: 'Masukkan ke tong hijau.', chinese: '放进绿色垃圾桶。' },
        { indonesian: 'Di dekat pintu belakang.', chinese: '在后门附近。' },
      ],
      variations: [
        { indonesian: 'Sampah ini dibuang ke mana?', chinese: '这个垃圾要扔到哪里？' },
        { indonesian: 'Tempat sampahnya di mana?', chinese: '垃圾桶在哪里？' },
        { indonesian: 'Yang organik ke mana?', chinese: '有机垃圾放哪里？' },
        { indonesian: 'Yang plastik dipisah ya?', chinese: '塑料要分开吗？' },
      ],
      localUsage: { indonesian: 'Buang sampahnya ke mana?', chinese: '更短的口语说法。' },
      easyMistake: { indonesian: 'Sampahnya taruh di mana?', chinese: '能懂但不如“dibuang di mana”清楚。' },
      trySay: { indonesian: 'Sampahnya dibuang di mana?', chinese: '垃圾要扔在哪里？' },
    },
  ),
];

