import { normalizeHarvestForAchievement } from '@/lib/learning-achievements';
import { vocabularyCategoryLabels, type VocabularyCategory, type VocabularyV2 } from '@/lib/v2/vocabulary';

export type VocabularyLibraryItem = VocabularyV2 & { usageNoteZh?: string };
type Seed = readonly [id: string, textId: string, textZh: string, tags?: string[], usageNoteZh?: string];

const seed = (category: VocabularyCategory, rows: readonly Seed[]): VocabularyLibraryItem[] => rows.map(([id, textId, textZh, tags = [], usageNoteZh]) => ({
  id, textId, textZh, normalizedKey: normalizeHarvestForAchievement(textId), category, tags: [vocabularyCategoryLabels[category], ...tags], pronunciationText: textId,
  difficultyLevel: category === 'OFFICE' || category === 'AIRPORT' ? 'L2' : 'L1', requiredMembershipTier: 'TRIAL', status: 'PUBLISHED', usageNoteZh,
}));

const time = seed('TIME', [
  ['VOC-TIME-001','hari ini','今天'],['VOC-TIME-002','besok','明天'],['VOC-TIME-003','kemarin','昨天'],['VOC-TIME-004','sekarang','现在'],['VOC-TIME-005','nanti','等一下、之后'],['VOC-TIME-006','dulu','先'],['VOC-TIME-007','sebentar','一会儿'],['VOC-TIME-008','sebentar lagi','马上'],['VOC-TIME-009','pagi','早上'],['VOC-TIME-010','siang','中午'],['VOC-TIME-011','sore','下午、傍晚'],['VOC-TIME-012','malam','晚上'],['VOC-TIME-013','malam ini','今晚'],['VOC-TIME-014','jam berapa','几点钟'],['VOC-TIME-015','jam satu','一点钟'],['VOC-TIME-016','setengah','一半、半点'],['VOC-TIME-017','setengah delapan','七点半'],['VOC-TIME-018','lebih awal','更早'],['VOC-TIME-019','terlambat','迟到、延误'],['VOC-TIME-020','tepat waktu','准时'],['VOC-TIME-021','setiap hari','每天'],['VOC-TIME-022','minggu ini','这周'],['VOC-TIME-023','minggu depan','下周'],['VOC-TIME-024','akhir pekan','周末'],['VOC-TIME-025','bulan ini','这个月'],['VOC-TIME-026','bulan depan','下个月'],['VOC-TIME-027','tahun ini','今年'],['VOC-TIME-028','baru saja','刚刚'],['VOC-TIME-029','belum lama','不久'],['VOC-TIME-030','seharian','一整天'],
]);
const numbers = seed('NUMBERS', [
  ['VOC-NUM-001','nol','零'],['VOC-NUM-002','satu','一'],['VOC-NUM-003','dua','二'],['VOC-NUM-004','tiga','三'],['VOC-NUM-005','empat','四'],['VOC-NUM-006','lima','五'],['VOC-NUM-007','enam','六'],['VOC-NUM-008','tujuh','七'],['VOC-NUM-009','delapan','八'],['VOC-NUM-010','sembilan','九'],['VOC-NUM-011','sepuluh','十'],['VOC-NUM-012','sebelas','十一'],['VOC-NUM-013','dua belas','十二'],['VOC-NUM-014','lima belas','十五'],['VOC-NUM-015','dua puluh','二十'],['VOC-NUM-016','tiga puluh','三十'],['VOC-NUM-017','lima puluh','五十'],['VOC-NUM-018','seratus','一百'],['VOC-NUM-019','seribu','一千'],['VOC-NUM-020','sejuta','一百万'],['VOC-NUM-021','berapa','多少'],['VOC-NUM-022','beberapa','几个、一些'],['VOC-NUM-023','semua','全部'],['VOC-NUM-024','seperempat','四分之一'],['VOC-NUM-025','satu per satu','一个一个地'],['VOC-NUM-026','dua kali','两次'],['VOC-NUM-027','sekali','一次、非常'],['VOC-NUM-028','lebih dari','超过'],['VOC-NUM-029','kurang dari','少于'],['VOC-NUM-030','jumlah','数量'],
]);
const colors = seed('COLORS', [
  ['VOC-COLOR-001','merah','红色'],['VOC-COLOR-002','biru','蓝色'],['VOC-COLOR-003','kuning','黄色'],['VOC-COLOR-004','hijau','绿色'],['VOC-COLOR-005','hitam','黑色'],['VOC-COLOR-006','putih','白色'],['VOC-COLOR-007','abu-abu','灰色'],['VOC-COLOR-008','cokelat','棕色'],['VOC-COLOR-009','oranye','橙色'],['VOC-COLOR-010','ungu','紫色'],['VOC-COLOR-011','merah muda','粉红色'],['VOC-COLOR-012','emas','金色'],['VOC-COLOR-013','perak','银色'],['VOC-COLOR-014','warna','颜色'],['VOC-COLOR-015','warna apa','什么颜色'],['VOC-COLOR-016','terang','亮的'],['VOC-COLOR-017','gelap','深的、暗的'],['VOC-COLOR-018','pucat','淡的'],['VOC-COLOR-019','warna muda','浅色'],['VOC-COLOR-020','warna tua','深色'],['VOC-COLOR-021','transparan','透明的'],['VOC-COLOR-022','bening','透明、清澈'],['VOC-COLOR-023','berwarna','有颜色的'],['VOC-COLOR-024','sama warnanya','颜色一样'],['VOC-COLOR-025','beda warna','颜色不同'],['VOC-COLOR-026','merah tua','深红色'],['VOC-COLOR-027','biru tua','深蓝色'],['VOC-COLOR-028','hijau muda','浅绿色'],['VOC-COLOR-029','kuning muda','浅黄色'],['VOC-COLOR-030','pilih warna','选颜色'],
]);
const directions = seed('DIRECTIONS', [
  ['VOC-DIRECTION-001','di mana','在哪里'],['VOC-DIRECTION-002','ke mana','去哪里'],['VOC-DIRECTION-003','di sini','在这里'],['VOC-DIRECTION-004','di sana','在那里'],['VOC-DIRECTION-005','di depan','前面、门口'],['VOC-DIRECTION-006','di belakang','后面'],['VOC-DIRECTION-007','di sebelah kiri','左边'],['VOC-DIRECTION-008','di sebelah kanan','右边'],['VOC-DIRECTION-009','di dekat sini','在这附近'],['VOC-DIRECTION-010','jauh','远'],['VOC-DIRECTION-011','dekat','近'],['VOC-DIRECTION-012','lurus','直走'],['VOC-DIRECTION-013','belok kiri','左转'],['VOC-DIRECTION-014','belok kanan','右转'],['VOC-DIRECTION-015','putar balik','掉头'],['VOC-DIRECTION-016','lewat mana','从哪里走'],['VOC-DIRECTION-017','jalan terus','一直走'],['VOC-DIRECTION-018','naik','上去、乘坐'],['VOC-DIRECTION-019','turun','下来、下车'],['VOC-DIRECTION-020','masuk','进去'],['VOC-DIRECTION-021','keluar','出去'],['VOC-DIRECTION-022','di atas','上面'],['VOC-DIRECTION-023','di bawah','下面'],['VOC-DIRECTION-024','di tengah','中间'],['VOC-DIRECTION-025','di samping','旁边'],['VOC-DIRECTION-026','pojok','角落'],['VOC-DIRECTION-027','seberang','对面'],['VOC-DIRECTION-028','arah','方向'],['VOC-DIRECTION-029','lokasi','位置'],['VOC-DIRECTION-030','alamat','地址'],
]);
const people = seed('PEOPLE_AND_TITLES', [
  ['VOC-PERSON-001','Pak','先生、师傅',['称呼'],'用于成年男性、职场男性或服务人员；自然且礼貌。'],['VOC-PERSON-002','Bapak','先生、父亲',['称呼'],'比 Pak 更正式，常用于正式称呼或完整称谓。'],['VOC-PERSON-003','Bu','女士、阿姨',['称呼'],'用于成年女性、职场女性；自然且礼貌。'],['VOC-PERSON-004','Ibu','女士、母亲',['称呼'],'比 Bu 更正式，也常用于正式称谓。'],['VOC-PERSON-005','Mas','大哥、先生',['称呼'],'常用于年轻男性服务人员或熟人，爪哇地区尤其常见。'],['VOC-PERSON-006','Mbak','小姐、女士',['称呼'],'常用于年轻女性服务人员或熟人。'],['VOC-PERSON-007','Kak','哥、姐',['称呼'],'不确定对方年龄时的友好称呼，适合较年轻成人。'],['VOC-PERSON-008','Adik','弟弟、妹妹',['称呼'],'用于比自己明显年幼的人；不宜随意称呼同龄陌生成人。'],['VOC-PERSON-009','Om','叔叔',['称呼'],'对父辈男性或熟悉年长男性的口语称呼。'],['VOC-PERSON-010','Tante','阿姨',['称呼'],'对父辈女性或熟悉年长女性的口语称呼。'],['VOC-PERSON-011','Bos','老板',['称呼'],'口语称呼老板或店主，熟悉场合更自然。'],['VOC-PERSON-012','teman','朋友'],['VOC-PERSON-013','karyawan','员工'],['VOC-PERSON-014','atasan','上级、主管'],['VOC-PERSON-015','pelanggan','客户、顾客'],['VOC-PERSON-016','sopir','司机'],['VOC-PERSON-017','ART','家政人员',['称呼'],'Asisten Rumah Tangga 的缩写，较中性、礼貌。'],['VOC-PERSON-018','pembantu','帮佣',['称呼'],'旧称或口语用法，可能显得不够尊重；优先使用 ART。'],['VOC-PERSON-019','rekan kerja','同事'],['VOC-PERSON-020','tetangga','邻居'],['VOC-PERSON-021','tamu','客人'],['VOC-PERSON-022','penjual','卖家'],['VOC-PERSON-023','pembeli','买家'],['VOC-PERSON-024','dokter','医生'],['VOC-PERSON-025','perawat','护士'],['VOC-PERSON-026','satpam','保安'],['VOC-PERSON-027','manajer','经理'],['VOC-PERSON-028','supervisor','主管'],['VOC-PERSON-029','operator','操作员'],['VOC-PERSON-030','pemasok','供应商'],
]);
const verbs = seed('COMMON_VERBS', [
  ['VOC-VERB-001','makan','吃饭'],['VOC-VERB-002','minum','喝'],['VOC-VERB-003','pergi','去'],['VOC-VERB-004','datang','来、到'],['VOC-VERB-005','pulang','回家'],['VOC-VERB-006','beli','买'],['VOC-VERB-007','bayar','支付'],['VOC-VERB-008','bawa','带、拿'],['VOC-VERB-009','ambil','拿、取'],['VOC-VERB-010','taruh','放'],['VOC-VERB-011','cari','找'],['VOC-VERB-012','tunggu','等'],['VOC-VERB-013','jemput','接人'],['VOC-VERB-014','antar','送'],['VOC-VERB-015','duduk','坐'],['VOC-VERB-016','berdiri','站'],['VOC-VERB-017','pakai','使用、穿'],['VOC-VERB-018','cuci','洗'],['VOC-VERB-019','buka','打开'],['VOC-VERB-020','tutup','关闭'],['VOC-VERB-021','mulai','开始'],['VOC-VERB-022','selesai','完成、结束'],['VOC-VERB-023','kerja','工作'],['VOC-VERB-024','belajar','学习'],['VOC-VERB-025','bicara','说话'],['VOC-VERB-026','bilang','说、告诉'],['VOC-VERB-027','tanya','问'],['VOC-VERB-028','jawab','回答'],['VOC-VERB-029','bantu','帮助'],['VOC-VERB-030','cek','检查'],
]);
const office = seed('OFFICE', [
  ['VOC-OFFICE-001','kantor','办公室、公司'],['VOC-OFFICE-002','meja','桌子'],['VOC-OFFICE-003','kursi','椅子'],['VOC-OFFICE-004','komputer','电脑'],['VOC-OFFICE-005','laptop','笔记本电脑'],['VOC-OFFICE-006','keyboard','键盘'],['VOC-OFFICE-007','mouse','鼠标'],['VOC-OFFICE-008','printer','打印机'],['VOC-OFFICE-009','kertas','纸'],['VOC-OFFICE-010','pulpen','笔'],['VOC-OFFICE-011','dokumen','文件'],['VOC-OFFICE-012','berkas','资料、文件'],['VOC-OFFICE-013','file','文件'],['VOC-OFFICE-014','email','邮件'],['VOC-OFFICE-015','rapat','会议'],['VOC-OFFICE-016','jadwal','日程'],['VOC-OFFICE-017','laporan','报告'],['VOC-OFFICE-018','tanda tangan','签名'],['VOC-OFFICE-019','stempel','印章'],['VOC-OFFICE-020','ruang rapat','会议室'],['VOC-OFFICE-021','resepionis','前台接待'],['VOC-OFFICE-022','lantai','楼层'],['VOC-OFFICE-023','lift','电梯'],['VOC-OFFICE-024','internet','网络'],['VOC-OFFICE-025','Wi-Fi','无线网络'],['VOC-OFFICE-026','telepon','电话'],['VOC-OFFICE-027','nomor telepon','电话号码'],['VOC-OFFICE-028','alamat email','邮箱地址'],['VOC-OFFICE-029','izin','许可、请假'],['VOC-OFFICE-030','istirahat','休息'],
]);
const kitchen = seed('KITCHEN', [
  ['VOC-KITCHEN-001','dapur','厨房'],['VOC-KITCHEN-002','masak','做饭'],['VOC-KITCHEN-003','makan malam','晚饭'],['VOC-KITCHEN-004','sarapan','早餐'],['VOC-KITCHEN-005','makan siang','午饭'],['VOC-KITCHEN-006','nasi','米饭'],['VOC-KITCHEN-007','mie','面条'],['VOC-KITCHEN-008','telur','鸡蛋'],['VOC-KITCHEN-009','ayam','鸡肉'],['VOC-KITCHEN-010','ikan','鱼'],['VOC-KITCHEN-011','sayur','蔬菜'],['VOC-KITCHEN-012','buah','水果'],['VOC-KITCHEN-013','garam','盐'],['VOC-KITCHEN-014','gula','糖'],['VOC-KITCHEN-015','cabai','辣椒'],['VOC-KITCHEN-016','minyak','油'],['VOC-KITCHEN-017','air','水'],['VOC-KITCHEN-018','susu','牛奶'],['VOC-KITCHEN-019','kopi','咖啡'],['VOC-KITCHEN-020','teh','茶'],['VOC-KITCHEN-021','piring','盘子'],['VOC-KITCHEN-022','sendok','勺子'],['VOC-KITCHEN-023','garpu','叉子'],['VOC-KITCHEN-024','gelas','杯子'],['VOC-KITCHEN-025','pisau','刀'],['VOC-KITCHEN-026','panci','锅'],['VOC-KITCHEN-027','wajan','平底锅'],['VOC-KITCHEN-028','kulkas','冰箱'],['VOC-KITCHEN-029','kompor','炉灶'],['VOC-KITCHEN-030','jangan pedas','不要辣'],
]);
const transport = seed('TRANSPORT', [
  ['VOC-TRANSPORT-001','mobil','汽车'],['VOC-TRANSPORT-002','motor','摩托车'],['VOC-TRANSPORT-003','ojek','摩托车载客服务'],['VOC-TRANSPORT-004','taksi','出租车'],['VOC-TRANSPORT-005','bus','公交车'],['VOC-TRANSPORT-006','kereta','火车'],['VOC-TRANSPORT-007','stasiun','车站'],['VOC-TRANSPORT-008','halte','公交站'],['VOC-TRANSPORT-009','terminal','客运站、航站楼'],['VOC-TRANSPORT-010','jalan','路'],['VOC-TRANSPORT-011','jalan tol','收费公路'],['VOC-TRANSPORT-012','macet','堵车'],['VOC-TRANSPORT-013','lancar','顺畅'],['VOC-TRANSPORT-014','parkir','停车'],['VOC-TRANSPORT-015','tempat parkir','停车位'],['VOC-TRANSPORT-016','bensin','汽油'],['VOC-TRANSPORT-017','pom bensin','加油站'],['VOC-TRANSPORT-018','isi bensin','加油'],['VOC-TRANSPORT-019','helm','头盔'],['VOC-TRANSPORT-020','sabuk pengaman','安全带'],['VOC-TRANSPORT-021','lampu merah','红绿灯'],['VOC-TRANSPORT-022','lampu hijau','绿灯'],['VOC-TRANSPORT-023','persimpangan','路口'],['VOC-TRANSPORT-024','tujuan','目的地'],['VOC-TRANSPORT-025','perjalanan','路程、行程'],['VOC-TRANSPORT-026','sampai','到达'],['VOC-TRANSPORT-027','sudah sampai','已经到了'],['VOC-TRANSPORT-028','pelan-pelan','慢一点'],['VOC-TRANSPORT-029','cepat','快'],['VOC-TRANSPORT-030','berhenti','停下'],
]);
const airport = seed('AIRPORT', [
  ['VOC-AIRPORT-001','bandara','机场'],['VOC-AIRPORT-002','lobi bandara','机场大厅'],['VOC-AIRPORT-003','penerbangan','航班'],['VOC-AIRPORT-004','pesawat','飞机'],['VOC-AIRPORT-005','tiket','机票、票'],['VOC-AIRPORT-006','paspor','护照'],['VOC-AIRPORT-007','visa','签证'],['VOC-AIRPORT-008','check-in','办理值机'],['VOC-AIRPORT-009','boarding pass','登机牌'],['VOC-AIRPORT-010','gerbang','登机口'],['VOC-AIRPORT-011','bagasi','行李'],['VOC-AIRPORT-012','koper','行李箱'],['VOC-AIRPORT-013','tas','包'],['VOC-AIRPORT-014','ambil bagasi','取行李'],['VOC-AIRPORT-015','bea cukai','海关'],['VOC-AIRPORT-016','imigrasi','移民局、入境检查'],['VOC-AIRPORT-017','kedatangan','到达'],['VOC-AIRPORT-018','keberangkatan','出发'],['VOC-AIRPORT-019','ruang tunggu','候机室'],['VOC-AIRPORT-020','jadwal penerbangan','航班时间表'],['VOC-AIRPORT-021','ubah jadwal','改期'],['VOC-AIRPORT-022','dibatalkan','被取消'],['VOC-AIRPORT-023','naik pesawat','登机'],['VOC-AIRPORT-024','turun dari pesawat','下飞机'],['VOC-AIRPORT-025','jemput di bandara','去机场接人'],['VOC-AIRPORT-026','sudah mendarat','已经降落'],['VOC-AIRPORT-027','pintu keluar','出口'],['VOC-AIRPORT-028','taksi bandara','机场出租车'],['VOC-AIRPORT-029','antar ke bandara','送去机场'],['VOC-AIRPORT-030','nomor penerbangan','航班号'],
]);

export const vocabularyLibrary: readonly VocabularyLibraryItem[] = [...time, ...numbers, ...colors, ...directions, ...people, ...verbs, ...office, ...kitchen, ...transport, ...airport];
export const vocabularyLibraryCategories = Object.keys(vocabularyCategoryLabels).filter((key): key is VocabularyCategory => ['TIME','NUMBERS','COLORS','DIRECTIONS','PEOPLE_AND_TITLES','COMMON_VERBS','OFFICE','KITCHEN','TRANSPORT','AIRPORT'].includes(key));

const vocabularyByNormalizedKey = new Map(vocabularyLibrary.map((item) => [item.normalizedKey, item]));

/** Compatibility bridge for gradual Harvest → stable vocabularyId migration. */
export function findVocabularyForHarvest(harvestText: string): VocabularyLibraryItem | undefined {
  return vocabularyByNormalizedKey.get(normalizeHarvestForAchievement(harvestText));
}

export function isVocabularyFavorite(favoriteId: string) { return favoriteId.startsWith('VOC-'); }
