import Link from 'next/link';
import { notFound } from 'next/navigation';
import ExperienceActions from '@/components/ExperienceActions';
import ExperienceNavLink from '@/components/ExperienceNavLink';
import { getNannyExperiences } from '@/lib/nanny-experiences';
import { nannyWorkflow, getNannyWorkflow, isNannyWorkflow } from '@/lib/nanny-workflow';

export default async function NannyDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ workflow?: string }> }) {
  const { id } = await params; const { workflow } = await searchParams; const all = getNannyExperiences(); const item = all.find((entry) => entry.id === `EXP-NAN-${id}`); if (!item) notFound();
  const completed = all.filter((entry) => !entry.missing); const index = completed.findIndex((entry) => entry.id === item.id); const previous = index > 0 ? completed[index - 1] : undefined; const next = index >= 0 ? completed[index + 1] : undefined; const current = getNannyWorkflow(item.id); const selected = isNannyWorkflow(workflow) ? workflow : current?.slug; const listHref = selected ? `/nanny?workflow=${selected}` : '/nanny';
  return <main className="mx-auto min-h-screen w-full max-w-4xl px-5 pb-12 pt-10 sm:px-8 sm:pt-14"><Link href={listHref} className="text-sm text-stone-500 hover:text-stone-900">← Asisten Rumah Tangga（保姆）</Link><header className="mt-7 rounded-2xl border border-stone-200 bg-stone-50 px-5 py-5"><p className="text-xs text-stone-400">Alur Rumah（家庭分类）</p><nav className="mt-3 grid gap-2 sm:grid-cols-3">{nannyWorkflow.map((stage) => <Link key={stage.slug} href={`/nanny?workflow=${stage.slug}`} className={`flex min-h-10 items-center rounded-lg border px-3 py-2 text-xs font-medium transition duration-200 ${current?.slug === stage.slug ? 'border-stone-900 bg-stone-900 text-white' : 'border-stone-200 bg-white text-stone-600 hover:bg-stone-100 hover:shadow-sm'}`}>{stage.indonesian}<span className="ml-1 text-stone-400">（{stage.chinese}）</span></Link>)}</nav></header><section className="mt-7 rounded-2xl border border-stone-200 bg-white px-6 py-7 shadow-sm sm:px-8"><p className="text-sm text-stone-400">{item.id}</p>{item.missing ? <><h1 className="mt-2 text-2xl font-semibold">Belum tersedia</h1><p className="mt-5 text-sm leading-6 text-stone-500">该内容将在后续版本补充。</p></> : <><h1 className="mt-2 text-2xl font-semibold">{item.task}</h1><p className="mt-5 text-xs text-stone-400">Bahasa Indonesia（印尼语）</p><p className="mt-2 rounded-xl bg-stone-50 p-4 text-lg leading-8">{item.indonesian}</p><p className="mt-5 text-xs text-stone-400">Penjelasan（中文说明）</p><p className="mt-2 text-sm leading-6 text-stone-700">{item.explanation}</p><p className="mt-6 text-xs text-stone-400">Kata Penting Hari Ini（今日重点词汇）</p><ul className="mt-2 space-y-1 text-sm text-stone-700">{item.harvest.map((word) => <li key={word}>• {word}</li>)}</ul><ExperienceActions experienceId={item.id} indonesian={item.indonesian} factory /></>}</section><nav className="mt-6 flex items-center justify-between gap-3">{previous ? <ExperienceNavLink href={`/nanny/${previous.id.slice(-3)}?workflow=${selected ?? ''}`} experienceId={item.id} action="previous_clicked" className="cursor-pointer rounded-xl border border-stone-300 px-4 py-2 text-sm font-medium transition duration-200 hover:bg-stone-50 hover:shadow-sm">← Sebelumnya（上一条）</ExperienceNavLink> : <span />}{next ? <ExperienceNavLink href={`/nanny/${next.id.slice(-3)}?workflow=${selected ?? ''}`} experienceId={item.id} action="next_clicked" className="cursor-pointer rounded-xl border border-stone-300 px-4 py-2 text-sm font-medium transition duration-200 hover:bg-stone-50 hover:shadow-sm">Berikutnya（下一条） →</ExperienceNavLink> : <span />}</nav></main>;
}
