import Link from 'next/link';
import { chineseCategories, getChineseExperiences } from '@/lib/chinese-experiences';
import { chinaCities } from '@/lib/china-cities';

export default function ChineseLearningPage({ searchParams }: { searchParams: Promise<{ category?: string }> }) {
  return <ChineseLearningContent searchParams={searchParams} />;
}

async function ChineseLearningContent({ searchParams }: { searchParams: Promise<{ category?: string }> }) {
  const { category } = await searchParams; const selected = chineseCategories.find((item) => item.slug === category)?.slug; const lessons = getChineseExperiences().filter((item) => !selected || item.category === selected);
  return <main className="mx-auto min-h-screen w-full max-w-5xl px-5 pb-12 pt-10 sm:px-8 sm:pt-14"><Link href="/" className="text-sm text-stone-500 hover:text-stone-900">← IndoBrain</Link><header className="mt-7 rounded-2xl border border-stone-200 bg-stone-950 px-5 py-6 text-white"><p className="text-xs text-stone-400">IndoBrain · Bahasa Mandarin untuk kerja</p><h1 className="mt-2 text-3xl font-semibold">中文沟通 <span className="text-lg font-normal text-stone-300">（Komunikasi Mandarin）</span></h1><p className="mt-3 max-w-2xl text-sm leading-6 text-stone-300">给在中资企业、办公室、工厂和商务场景中与中国人沟通的印尼学习者。先理解场景，再开口说完整中文。</p><p className="mt-4 text-xs text-stone-400">{getChineseExperiences().length} 条 Experience · 中文主句 · 拼音 · 印尼语理解</p></header><nav className="mt-6 grid gap-2 sm:grid-cols-2" aria-label="Chinese learning modules">{chineseCategories.map((item) => <Link key={item.slug} href={`/chinese?category=${item.slug}`} className={`min-h-16 rounded-xl border px-4 py-3 transition duration-200 hover:shadow-sm ${selected === item.slug ? 'border-stone-900 bg-stone-900 text-white' : 'border-stone-200 bg-white text-stone-700 hover:bg-stone-50'}`}><span className="mr-2">{item.icon}</span><span className="font-medium">{item.chinese}</span><span className={`mt-1 block text-xs ${selected === item.slug ? 'text-stone-300' : 'text-stone-500'}`}>{item.indonesian}</span></Link>)}</nav><section className="mt-8"><div className="flex items-end justify-between gap-4"><h2 className="text-xl font-semibold">Experience</h2><Link href="/chinese" className="text-sm text-stone-500 hover:text-stone-900">全部课程</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{lessons.map((lesson) => <Link key={lesson.id} href={`/chinese/${lesson.id}`} className="flex min-h-44 cursor-pointer flex-col rounded-xl border border-stone-200 bg-white px-5 py-5 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:bg-stone-50 hover:shadow-md"><p className="text-xs font-medium text-stone-400">{lesson.id}</p><h3 className="mt-3 text-lg font-semibold">{lesson.title}</h3><p className="mt-1 text-sm text-stone-500">{lesson.pinyin}</p><p className="mt-auto pt-4 text-sm leading-6 text-stone-600">{lesson.scenario}</p></Link>)}</div></section><section className="mt-10"><h2 className="text-xl font-semibold">认识中国 <span className="text-base font-normal text-stone-500">（Mengenal Tiongkok）</span></h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{chinaCities.map((city) => <Link key={city.slug} href={`/chinese/china/${city.slug}`} className="min-h-32 rounded-xl border border-stone-200 bg-stone-50 px-5 py-5 shadow-sm transition duration-200 hover:bg-white hover:shadow-md"><p className="font-semibold">{city.chinese} <span className="text-sm font-normal text-stone-500">{city.pinyin}</span></p><p className="mt-1 text-sm text-stone-500">{city.indonesian}</p><p className="mt-3 text-sm leading-6 text-stone-600">{city.region}</p></Link>)}</div></section></main>;
}
